from typing import overload, Any, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class AppearanceSettings:
    @overload
    @staticmethod
    def DefaultPaintColor(whichColor: PaintColor) -> Color: ...
    @overload
    @staticmethod
    def DefaultPaintColor(whichColor: PaintColor, darkMode: bool) -> Color: ...
    @overload
    @staticmethod
    def DefaultWidgetColor(whichColor: WidgetColor) -> Color: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def CommandPromptBackgroundColor(cls) -> Color: ...
    @property
    @classmethod
    def CommandPromptFontSize(cls) -> int: ...
    @property
    @classmethod
    def CommandPromptHypertextColor(cls) -> Color: ...
    @property
    @classmethod
    def CommandPromptPosition(cls) -> CommandPromptPosition: ...
    @property
    @classmethod
    def CommandPromptTextColor(cls) -> Color: ...
    @property
    @classmethod
    def CrosshairColor(cls) -> Color: ...
    @property
    @classmethod
    def CurrentLayerBackgroundColor(cls) -> Color: ...
    @property
    @classmethod
    def DefaultFontFaceName(cls) -> str: ...
    @property
    @classmethod
    def DefaultLayerColor(cls) -> Color: ...
    @property
    @classmethod
    def DefaultObjectColor(cls) -> Color: ...
    @property
    @classmethod
    def DirectionArrowIconHeadSize(cls) -> int: ...
    @property
    @classmethod
    def DirectionArrowIconShaftSize(cls) -> int: ...
    @property
    @classmethod
    def EchoCommandsToHistoryWindow(cls) -> bool: ...
    @property
    @classmethod
    def EchoPromptsToHistoryWindow(cls) -> bool: ...
    @property
    @classmethod
    def EditCandidateColor(cls) -> Color: ...
    @property
    @classmethod
    def FeedbackColor(cls) -> Color: ...
    @property
    @classmethod
    def FrameBackgroundColor(cls) -> Color: ...
    @property
    @classmethod
    def GridThickLineColor(cls) -> Color: ...
    @property
    @classmethod
    def GridThinLineColor(cls) -> Color: ...
    @property
    @classmethod
    def GridXAxisLineColor(cls) -> Color: ...
    @property
    @classmethod
    def GridYAxisLineColor(cls) -> Color: ...
    @property
    @classmethod
    def GridZAxisLineColor(cls) -> Color: ...
    @property
    @classmethod
    def LanguageIdentifier(cls) -> int: ...
    @property
    @classmethod
    def LockedObjectColor(cls) -> Color: ...
    @property
    @classmethod
    def MenuVisible(cls) -> bool: ...
    @property
    @classmethod
    def PageviewPaperColor(cls) -> Color: ...
    @property
    @classmethod
    def PreviousLanguageIdentifier(cls) -> int: ...
    @property
    @classmethod
    def SelectedObjectColor(cls) -> Color: ...
    @property
    @classmethod
    def SelectionWindowCrossingFillColor(cls) -> Color: ...
    @property
    @classmethod
    def SelectionWindowCrossingStrokeColor(cls) -> Color: ...
    @property
    @classmethod
    def SelectionWindowFillColor(cls) -> Color: ...
    @property
    @classmethod
    def SelectionWindowStrokeColor(cls) -> Color: ...
    @property
    @classmethod
    def ShowCrosshairs(cls) -> bool: ...
    @property
    @classmethod
    def ShowFullPathInTitleBar(cls) -> bool: ...
    @property
    @classmethod
    def ShowLayoutDropShadow(cls) -> bool: ...
    @property
    @classmethod
    def ShowOsnapBar(cls) -> bool: ...
    @property
    @classmethod
    def ShowSelectionFilterBar(cls) -> bool: ...
    @property
    @classmethod
    def ShowSideBar(cls) -> bool: ...
    @property
    @classmethod
    def ShowStatusBar(cls) -> bool: ...
    @property
    @classmethod
    def ShowTitleBar(cls) -> bool: ...
    @property
    @classmethod
    def ShowViewportTitles(cls) -> bool: ...
    @property
    @classmethod
    def TrackingColor(cls) -> Color: ...
    @property
    @classmethod
    def UsePaintColors(cls) -> bool: ...
    @property
    @classmethod
    def ViewportBackgroundColor(cls) -> Color: ...
    @property
    @classmethod
    def ViewportTabsVisibleAtStart(cls) -> bool: ...
    @property
    @classmethod
    def WorldCoordIconXAxisColor(cls) -> Color: ...
    @property
    @classmethod
    def WorldCoordIconYAxisColor(cls) -> Color: ...
    @property
    @classmethod
    def WorldCoordIconZAxisColor(cls) -> Color: ...
    @overload
    @staticmethod
    def GetCurrentState() -> AppearanceSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> AppearanceSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState(darkMode: bool) -> AppearanceSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetPaintColor(whichColor: PaintColor) -> Color: ...
    @overload
    @staticmethod
    def GetPaintColor(whichColor: PaintColor, compute: bool) -> Color: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def GetWidgetColor(whichColor: WidgetColor) -> Color: ...
    @overload
    @staticmethod
    def InitialMainWindowPosition() -> Tuple[bool, Rectangle]: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @CommandPromptBackgroundColor.setter
    @classmethod
    def CommandPromptBackgroundColor(clsvalue: Color) -> None: ...
    @CommandPromptFontSize.setter
    @classmethod
    def CommandPromptFontSize(clsvalue: int) -> None: ...
    @CommandPromptHypertextColor.setter
    @classmethod
    def CommandPromptHypertextColor(clsvalue: Color) -> None: ...
    @CommandPromptPosition.setter
    @classmethod
    def CommandPromptPosition(clsvalue: CommandPromptPosition) -> None: ...
    @CommandPromptTextColor.setter
    @classmethod
    def CommandPromptTextColor(clsvalue: Color) -> None: ...
    @CrosshairColor.setter
    @classmethod
    def CrosshairColor(clsvalue: Color) -> None: ...
    @CurrentLayerBackgroundColor.setter
    @classmethod
    def CurrentLayerBackgroundColor(clsvalue: Color) -> None: ...
    @DefaultLayerColor.setter
    @classmethod
    def DefaultLayerColor(clsvalue: Color) -> None: ...
    @DefaultObjectColor.setter
    @classmethod
    def DefaultObjectColor(clsvalue: Color) -> None: ...
    @DirectionArrowIconHeadSize.setter
    @classmethod
    def DirectionArrowIconHeadSize(clsvalue: int) -> None: ...
    @DirectionArrowIconShaftSize.setter
    @classmethod
    def DirectionArrowIconShaftSize(clsvalue: int) -> None: ...
    @EchoCommandsToHistoryWindow.setter
    @classmethod
    def EchoCommandsToHistoryWindow(clsvalue: bool) -> None: ...
    @EchoPromptsToHistoryWindow.setter
    @classmethod
    def EchoPromptsToHistoryWindow(clsvalue: bool) -> None: ...
    @EditCandidateColor.setter
    @classmethod
    def EditCandidateColor(clsvalue: Color) -> None: ...
    @FeedbackColor.setter
    @classmethod
    def FeedbackColor(clsvalue: Color) -> None: ...
    @FrameBackgroundColor.setter
    @classmethod
    def FrameBackgroundColor(clsvalue: Color) -> None: ...
    @GridThickLineColor.setter
    @classmethod
    def GridThickLineColor(clsvalue: Color) -> None: ...
    @GridThinLineColor.setter
    @classmethod
    def GridThinLineColor(clsvalue: Color) -> None: ...
    @GridXAxisLineColor.setter
    @classmethod
    def GridXAxisLineColor(clsvalue: Color) -> None: ...
    @GridYAxisLineColor.setter
    @classmethod
    def GridYAxisLineColor(clsvalue: Color) -> None: ...
    @GridZAxisLineColor.setter
    @classmethod
    def GridZAxisLineColor(clsvalue: Color) -> None: ...
    @LanguageIdentifier.setter
    @classmethod
    def LanguageIdentifier(clsvalue: int) -> None: ...
    @LockedObjectColor.setter
    @classmethod
    def LockedObjectColor(clsvalue: Color) -> None: ...
    @MenuVisible.setter
    @classmethod
    def MenuVisible(clsvalue: bool) -> None: ...
    @PageviewPaperColor.setter
    @classmethod
    def PageviewPaperColor(clsvalue: Color) -> None: ...
    @PreviousLanguageIdentifier.setter
    @classmethod
    def PreviousLanguageIdentifier(clsvalue: int) -> None: ...
    @SelectedObjectColor.setter
    @classmethod
    def SelectedObjectColor(clsvalue: Color) -> None: ...
    @SelectionWindowCrossingFillColor.setter
    @classmethod
    def SelectionWindowCrossingFillColor(clsvalue: Color) -> None: ...
    @SelectionWindowCrossingStrokeColor.setter
    @classmethod
    def SelectionWindowCrossingStrokeColor(clsvalue: Color) -> None: ...
    @SelectionWindowFillColor.setter
    @classmethod
    def SelectionWindowFillColor(clsvalue: Color) -> None: ...
    @SelectionWindowStrokeColor.setter
    @classmethod
    def SelectionWindowStrokeColor(clsvalue: Color) -> None: ...
    @ShowCrosshairs.setter
    @classmethod
    def ShowCrosshairs(clsvalue: bool) -> None: ...
    @ShowFullPathInTitleBar.setter
    @classmethod
    def ShowFullPathInTitleBar(clsvalue: bool) -> None: ...
    @ShowLayoutDropShadow.setter
    @classmethod
    def ShowLayoutDropShadow(clsvalue: bool) -> None: ...
    @ShowOsnapBar.setter
    @classmethod
    def ShowOsnapBar(clsvalue: bool) -> None: ...
    @ShowSelectionFilterBar.setter
    @classmethod
    def ShowSelectionFilterBar(clsvalue: bool) -> None: ...
    @ShowSideBar.setter
    @classmethod
    def ShowSideBar(clsvalue: bool) -> None: ...
    @ShowStatusBar.setter
    @classmethod
    def ShowStatusBar(clsvalue: bool) -> None: ...
    @ShowTitleBar.setter
    @classmethod
    def ShowTitleBar(clsvalue: bool) -> None: ...
    @ShowViewportTitles.setter
    @classmethod
    def ShowViewportTitles(clsvalue: bool) -> None: ...
    @TrackingColor.setter
    @classmethod
    def TrackingColor(clsvalue: Color) -> None: ...
    @ViewportBackgroundColor.setter
    @classmethod
    def ViewportBackgroundColor(clsvalue: Color) -> None: ...
    @ViewportTabsVisibleAtStart.setter
    @classmethod
    def ViewportTabsVisibleAtStart(clsvalue: bool) -> None: ...
    @WorldCoordIconXAxisColor.setter
    @classmethod
    def WorldCoordIconXAxisColor(clsvalue: Color) -> None: ...
    @WorldCoordIconYAxisColor.setter
    @classmethod
    def WorldCoordIconYAxisColor(clsvalue: Color) -> None: ...
    @WorldCoordIconZAxisColor.setter
    @classmethod
    def WorldCoordIconZAxisColor(clsvalue: Color) -> None: ...
    @overload
    @staticmethod
    def SetPaintColor(whichColor: PaintColor, c: Color) -> None: ...
    @overload
    @staticmethod
    def SetPaintColor(whichColor: PaintColor, c: Color, forceUiUpdate: bool) -> None: ...
    @overload
    @staticmethod
    def SetToDarkMode() -> bool: ...
    @overload
    @staticmethod
    def SetToLightMode() -> bool: ...
    @overload
    @staticmethod
    def SetWidgetColor(whichColor: WidgetColor, c: Color) -> None: ...
    @overload
    @staticmethod
    def SetWidgetColor(whichColor: WidgetColor, c: Color, forceUiUpdate: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: AppearanceSettingsState) -> None: ...
    @overload
    @staticmethod
    def UsingDefaultDarkModeColors() -> bool: ...
    @overload
    @staticmethod
    def UsingDefaultLightModeColors() -> bool: ...


class AppearanceSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def CommandPromptBackgroundColor(self) -> Color: ...
    @property
    def CommandPromptFontName(self) -> str: ...
    @property
    def CommandPromptFontSize(self) -> int: ...
    @property
    def CommandPromptHypertextColor(self) -> Color: ...
    @property
    def CommandPromptTextColor(self) -> Color: ...
    @property
    def CrosshairColor(self) -> Color: ...
    @property
    def CurrentLayerBackgroundColor(self) -> Color: ...
    @property
    def DefaultFontFaceName(self) -> str: ...
    @property
    def DefaultLayerColor(self) -> Color: ...
    @property
    def DefaultObjectColor(self) -> Color: ...
    @property
    def DirectionArrowIconHeadSize(self) -> int: ...
    @property
    def DirectionArrowIconShaftSize(self) -> int: ...
    @property
    def EchoCommandsToHistoryWindow(self) -> bool: ...
    @property
    def EchoPromptsToHistoryWindow(self) -> bool: ...
    @property
    def EditCandidateColor(self) -> Color: ...
    @property
    def FeedbackColor(self) -> Color: ...
    @property
    def FrameBackgroundColor(self) -> Color: ...
    @property
    def GridThickLineColor(self) -> Color: ...
    @property
    def GridThinLineColor(self) -> Color: ...
    @property
    def GridXAxisLineColor(self) -> Color: ...
    @property
    def GridYAxisLineColor(self) -> Color: ...
    @property
    def GridZAxisLineColor(self) -> Color: ...
    @property
    def LockedObjectColor(self) -> Color: ...
    @property
    def MenuVisible(self) -> bool: ...
    @property
    def PageviewPaperColor(self) -> Color: ...
    @property
    def SelectedObjectColor(self) -> Color: ...
    @property
    def SelectionWindowCrossingFillColor(self) -> Color: ...
    @property
    def SelectionWindowCrossingStrokeColor(self) -> Color: ...
    @property
    def SelectionWindowFillColor(self) -> Color: ...
    @property
    def SelectionWindowStrokeColor(self) -> Color: ...
    @property
    def ShowCrosshairs(self) -> bool: ...
    @property
    def ShowFullPathInTitleBar(self) -> bool: ...
    @property
    def ShowLayoutDropShadow(self) -> bool: ...
    @property
    def ShowStatusBar(self) -> bool: ...
    @property
    def ShowTitleBar(self) -> bool: ...
    @property
    def ShowViewportTitles(self) -> bool: ...
    @property
    def TrackingColor(self) -> Color: ...
    @property
    def ViewportBackgroundColor(self) -> Color: ...
    @property
    def ViewportTabsVisibleAtStart(self) -> bool: ...
    @property
    def WorldCoordIconXAxisColor(self) -> Color: ...
    @property
    def WorldCoordIconYAxisColor(self) -> Color: ...
    @property
    def WorldCoordIconZAxisColor(self) -> Color: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @CommandPromptBackgroundColor.setter
    def CommandPromptBackgroundColor(self, value: Color) -> None: ...
    @CommandPromptFontName.setter
    def CommandPromptFontName(self, value: str) -> None: ...
    @CommandPromptFontSize.setter
    def CommandPromptFontSize(self, value: int) -> None: ...
    @CommandPromptHypertextColor.setter
    def CommandPromptHypertextColor(self, value: Color) -> None: ...
    @CommandPromptTextColor.setter
    def CommandPromptTextColor(self, value: Color) -> None: ...
    @CrosshairColor.setter
    def CrosshairColor(self, value: Color) -> None: ...
    @CurrentLayerBackgroundColor.setter
    def CurrentLayerBackgroundColor(self, value: Color) -> None: ...
    @DefaultFontFaceName.setter
    def DefaultFontFaceName(self, value: str) -> None: ...
    @DefaultLayerColor.setter
    def DefaultLayerColor(self, value: Color) -> None: ...
    @DefaultObjectColor.setter
    def DefaultObjectColor(self, value: Color) -> None: ...
    @DirectionArrowIconHeadSize.setter
    def DirectionArrowIconHeadSize(self, value: int) -> None: ...
    @DirectionArrowIconShaftSize.setter
    def DirectionArrowIconShaftSize(self, value: int) -> None: ...
    @EchoCommandsToHistoryWindow.setter
    def EchoCommandsToHistoryWindow(self, value: bool) -> None: ...
    @EchoPromptsToHistoryWindow.setter
    def EchoPromptsToHistoryWindow(self, value: bool) -> None: ...
    @EditCandidateColor.setter
    def EditCandidateColor(self, value: Color) -> None: ...
    @FeedbackColor.setter
    def FeedbackColor(self, value: Color) -> None: ...
    @FrameBackgroundColor.setter
    def FrameBackgroundColor(self, value: Color) -> None: ...
    @GridThickLineColor.setter
    def GridThickLineColor(self, value: Color) -> None: ...
    @GridThinLineColor.setter
    def GridThinLineColor(self, value: Color) -> None: ...
    @GridXAxisLineColor.setter
    def GridXAxisLineColor(self, value: Color) -> None: ...
    @GridYAxisLineColor.setter
    def GridYAxisLineColor(self, value: Color) -> None: ...
    @GridZAxisLineColor.setter
    def GridZAxisLineColor(self, value: Color) -> None: ...
    @LockedObjectColor.setter
    def LockedObjectColor(self, value: Color) -> None: ...
    @MenuVisible.setter
    def MenuVisible(self, value: bool) -> None: ...
    @PageviewPaperColor.setter
    def PageviewPaperColor(self, value: Color) -> None: ...
    @SelectedObjectColor.setter
    def SelectedObjectColor(self, value: Color) -> None: ...
    @SelectionWindowCrossingFillColor.setter
    def SelectionWindowCrossingFillColor(self, value: Color) -> None: ...
    @SelectionWindowCrossingStrokeColor.setter
    def SelectionWindowCrossingStrokeColor(self, value: Color) -> None: ...
    @SelectionWindowFillColor.setter
    def SelectionWindowFillColor(self, value: Color) -> None: ...
    @SelectionWindowStrokeColor.setter
    def SelectionWindowStrokeColor(self, value: Color) -> None: ...
    @ShowCrosshairs.setter
    def ShowCrosshairs(self, value: bool) -> None: ...
    @ShowFullPathInTitleBar.setter
    def ShowFullPathInTitleBar(self, value: bool) -> None: ...
    @ShowLayoutDropShadow.setter
    def ShowLayoutDropShadow(self, value: bool) -> None: ...
    @ShowStatusBar.setter
    def ShowStatusBar(self, value: bool) -> None: ...
    @ShowTitleBar.setter
    def ShowTitleBar(self, value: bool) -> None: ...
    @ShowViewportTitles.setter
    def ShowViewportTitles(self, value: bool) -> None: ...
    @TrackingColor.setter
    def TrackingColor(self, value: Color) -> None: ...
    @ViewportBackgroundColor.setter
    def ViewportBackgroundColor(self, value: Color) -> None: ...
    @ViewportTabsVisibleAtStart.setter
    def ViewportTabsVisibleAtStart(self, value: bool) -> None: ...
    @WorldCoordIconXAxisColor.setter
    def WorldCoordIconXAxisColor(self, value: Color) -> None: ...
    @WorldCoordIconYAxisColor.setter
    def WorldCoordIconYAxisColor(self, value: Color) -> None: ...
    @WorldCoordIconZAxisColor.setter
    def WorldCoordIconZAxisColor(self, value: Color) -> None: ...
    @overload
    def ToString(self) -> str: ...


class ChooseOneObjectSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def AutomaticResize(cls) -> bool: ...
    @property
    @classmethod
    def DynamicHighlight(cls) -> bool: ...
    @property
    @classmethod
    def FollowCursor(cls) -> bool: ...
    @property
    @classmethod
    def HighlightColor(cls) -> Color: ...
    @property
    @classmethod
    def MaxAutoResizeItems(cls) -> int: ...
    @property
    @classmethod
    def ShowAllOption(cls) -> bool: ...
    @property
    @classmethod
    def ShowObjectColor(cls) -> bool: ...
    @property
    @classmethod
    def ShowObjectLayer(cls) -> bool: ...
    @property
    @classmethod
    def ShowObjectName(cls) -> bool: ...
    @property
    @classmethod
    def ShowObjectType(cls) -> bool: ...
    @property
    @classmethod
    def ShowObjectTypeDetails(cls) -> bool: ...
    @property
    @classmethod
    def ShowTitlebarAndBorder(cls) -> bool: ...
    @property
    @classmethod
    def UseCustomColor(cls) -> bool: ...
    @property
    @classmethod
    def XOffset(cls) -> int: ...
    @property
    @classmethod
    def YOffset(cls) -> int: ...
    @overload
    @staticmethod
    def GetCurrentState() -> ChooseOneObjectSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> ChooseOneObjectSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @AutomaticResize.setter
    @classmethod
    def AutomaticResize(clsvalue: bool) -> None: ...
    @DynamicHighlight.setter
    @classmethod
    def DynamicHighlight(clsvalue: bool) -> None: ...
    @FollowCursor.setter
    @classmethod
    def FollowCursor(clsvalue: bool) -> None: ...
    @HighlightColor.setter
    @classmethod
    def HighlightColor(clsvalue: Color) -> None: ...
    @MaxAutoResizeItems.setter
    @classmethod
    def MaxAutoResizeItems(clsvalue: int) -> None: ...
    @ShowAllOption.setter
    @classmethod
    def ShowAllOption(clsvalue: bool) -> None: ...
    @ShowObjectColor.setter
    @classmethod
    def ShowObjectColor(clsvalue: bool) -> None: ...
    @ShowObjectLayer.setter
    @classmethod
    def ShowObjectLayer(clsvalue: bool) -> None: ...
    @ShowObjectName.setter
    @classmethod
    def ShowObjectName(clsvalue: bool) -> None: ...
    @ShowObjectType.setter
    @classmethod
    def ShowObjectType(clsvalue: bool) -> None: ...
    @ShowObjectTypeDetails.setter
    @classmethod
    def ShowObjectTypeDetails(clsvalue: bool) -> None: ...
    @ShowTitlebarAndBorder.setter
    @classmethod
    def ShowTitlebarAndBorder(clsvalue: bool) -> None: ...
    @UseCustomColor.setter
    @classmethod
    def UseCustomColor(clsvalue: bool) -> None: ...
    @XOffset.setter
    @classmethod
    def XOffset(clsvalue: int) -> None: ...
    @YOffset.setter
    @classmethod
    def YOffset(clsvalue: int) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: ChooseOneObjectSettingsState) -> None: ...


class ChooseOneObjectSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AutomaticResize(self) -> bool: ...
    @property
    def DynamicHighlight(self) -> bool: ...
    @property
    def FollowCursor(self) -> bool: ...
    @property
    def HighlightColor(self) -> Color: ...
    @property
    def MaxAutoResizeItems(self) -> int: ...
    @property
    def ShowAllOption(self) -> bool: ...
    @property
    def ShowObjectColor(self) -> bool: ...
    @property
    def ShowObjectLayer(self) -> bool: ...
    @property
    def ShowObjectName(self) -> bool: ...
    @property
    def ShowObjectType(self) -> bool: ...
    @property
    def ShowObjectTypeDetails(self) -> bool: ...
    @property
    def ShowTitlebarAndBorder(self) -> bool: ...
    @property
    def UseCustomColor(self) -> bool: ...
    @property
    def XOffset(self) -> int: ...
    @property
    def YOffset(self) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AutomaticResize.setter
    def AutomaticResize(self, value: bool) -> None: ...
    @DynamicHighlight.setter
    def DynamicHighlight(self, value: bool) -> None: ...
    @FollowCursor.setter
    def FollowCursor(self, value: bool) -> None: ...
    @HighlightColor.setter
    def HighlightColor(self, value: Color) -> None: ...
    @MaxAutoResizeItems.setter
    def MaxAutoResizeItems(self, value: int) -> None: ...
    @ShowAllOption.setter
    def ShowAllOption(self, value: bool) -> None: ...
    @ShowObjectColor.setter
    def ShowObjectColor(self, value: bool) -> None: ...
    @ShowObjectLayer.setter
    def ShowObjectLayer(self, value: bool) -> None: ...
    @ShowObjectName.setter
    def ShowObjectName(self, value: bool) -> None: ...
    @ShowObjectType.setter
    def ShowObjectType(self, value: bool) -> None: ...
    @ShowObjectTypeDetails.setter
    def ShowObjectTypeDetails(self, value: bool) -> None: ...
    @ShowTitlebarAndBorder.setter
    def ShowTitlebarAndBorder(self, value: bool) -> None: ...
    @UseCustomColor.setter
    def UseCustomColor(self, value: bool) -> None: ...
    @XOffset.setter
    def XOffset(self, value: int) -> None: ...
    @YOffset.setter
    def YOffset(self, value: int) -> None: ...
    @overload
    def ToString(self) -> str: ...


class ClipboardState(Enum):
    KeepData = 0
    DeleteData = 1
    PromptWhenBig = 2


from .Generic import Dictionary
class CommandAliasList:
    @overload
    @staticmethod
    def Add(alias: str, macro: str) -> bool: ...
    @overload
    @staticmethod
    def Clear() -> None: ...
    @overload
    @staticmethod
    def Delete(alias: str) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def Count(cls) -> int: ...
    @overload
    @staticmethod
    def GetDefaults() -> Dictionary: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetMacro(alias: str) -> str: ...
    @overload
    @staticmethod
    def GetNames() -> Iterable[str]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def IsAlias(alias: str) -> bool: ...
    @overload
    @staticmethod
    def IsDefault() -> bool: ...
    @overload
    @staticmethod
    def SetMacro(alias: str, macro: str) -> bool: ...
    @overload
    @staticmethod
    def ToDictionary() -> Dictionary: ...
    @overload
    def ToString(self) -> str: ...


class CommandPromptPosition(Enum):
    Top = 0
    Bottom = 1
    Floating = 2
    Hidden = 3


class CursorMode(Enum):
    # None = 0
    BlackOnWhite = 1
    WhiteOnBlack = 2


class CursorTooltipSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def AutoSuppress(cls) -> bool: ...
    @property
    @classmethod
    def BackgroundColor(cls) -> Color: ...
    @property
    @classmethod
    def CommandPromptPane(cls) -> bool: ...
    @property
    @classmethod
    def DistancePane(cls) -> bool: ...
    @property
    @classmethod
    def EnableGumballToolTips(cls) -> bool: ...
    @property
    @classmethod
    def Offset(cls) -> Point: ...
    @property
    @classmethod
    def OsnapPane(cls) -> bool: ...
    @property
    @classmethod
    def PointPane(cls) -> bool: ...
    @property
    @classmethod
    def RelativePointPane(cls) -> bool: ...
    @property
    @classmethod
    def TextColor(cls) -> Color: ...
    @property
    @classmethod
    def TooltipsEnabled(cls) -> bool: ...
    @overload
    @staticmethod
    def GetCurrentState() -> CursorTooltipSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> CursorTooltipSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AutoSuppress.setter
    @classmethod
    def AutoSuppress(clsvalue: bool) -> None: ...
    @BackgroundColor.setter
    @classmethod
    def BackgroundColor(clsvalue: Color) -> None: ...
    @CommandPromptPane.setter
    @classmethod
    def CommandPromptPane(clsvalue: bool) -> None: ...
    @DistancePane.setter
    @classmethod
    def DistancePane(clsvalue: bool) -> None: ...
    @EnableGumballToolTips.setter
    @classmethod
    def EnableGumballToolTips(clsvalue: bool) -> None: ...
    @Offset.setter
    @classmethod
    def Offset(clsvalue: Point) -> None: ...
    @OsnapPane.setter
    @classmethod
    def OsnapPane(clsvalue: bool) -> None: ...
    @PointPane.setter
    @classmethod
    def PointPane(clsvalue: bool) -> None: ...
    @RelativePointPane.setter
    @classmethod
    def RelativePointPane(clsvalue: bool) -> None: ...
    @TextColor.setter
    @classmethod
    def TextColor(clsvalue: Color) -> None: ...
    @TooltipsEnabled.setter
    @classmethod
    def TooltipsEnabled(clsvalue: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...


class CursorTooltipSettingsState:
    @overload
    def __init__(self): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AutoSuppress(self) -> bool: ...
    @property
    def BackgroundColor(self) -> Color: ...
    @property
    def CommandPromptPane(self) -> bool: ...
    @property
    def DistancePane(self) -> bool: ...
    @property
    def EnableGumballToolTips(self) -> bool: ...
    @property
    def Offset(self) -> Point: ...
    @property
    def OsnapPane(self) -> bool: ...
    @property
    def PointPane(self) -> bool: ...
    @property
    def RelativePointPane(self) -> bool: ...
    @property
    def TextColor(self) -> Color: ...
    @property
    def TooltipsEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AutoSuppress.setter
    def AutoSuppress(self, value: bool) -> None: ...
    @BackgroundColor.setter
    def BackgroundColor(self, value: Color) -> None: ...
    @CommandPromptPane.setter
    def CommandPromptPane(self, value: bool) -> None: ...
    @DistancePane.setter
    def DistancePane(self, value: bool) -> None: ...
    @EnableGumballToolTips.setter
    def EnableGumballToolTips(self, value: bool) -> None: ...
    @Offset.setter
    def Offset(self, value: Point) -> None: ...
    @OsnapPane.setter
    def OsnapPane(self, value: bool) -> None: ...
    @PointPane.setter
    def PointPane(self, value: bool) -> None: ...
    @RelativePointPane.setter
    def RelativePointPane(self, value: bool) -> None: ...
    @TextColor.setter
    def TextColor(self, value: Color) -> None: ...
    @TooltipsEnabled.setter
    def TooltipsEnabled(self, value: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...


class CurvatureAnalysisSettings:
    @overload
    @staticmethod
    def CalculateCurvatureAutoRange(meshes: Iterable[Mesh], settings: CurvatureAnalysisSettingsState) -> Tuple[bool, CurvatureAnalysisSettingsState]: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def GaussRange(cls) -> Interval: ...
    @property
    @classmethod
    def MaxRadiusRange(cls) -> Interval: ...
    @property
    @classmethod
    def MeanRange(cls) -> Interval: ...
    @property
    @classmethod
    def MinRadiusRange(cls) -> Interval: ...
    @property
    @classmethod
    def Style(cls) -> CurvatureStyle: ...
    @overload
    @staticmethod
    def GetCurrentState() -> CurvatureAnalysisSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> CurvatureAnalysisSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @GaussRange.setter
    @classmethod
    def GaussRange(clsvalue: Interval) -> None: ...
    @MaxRadiusRange.setter
    @classmethod
    def MaxRadiusRange(clsvalue: Interval) -> None: ...
    @MeanRange.setter
    @classmethod
    def MeanRange(clsvalue: Interval) -> None: ...
    @MinRadiusRange.setter
    @classmethod
    def MinRadiusRange(clsvalue: Interval) -> None: ...
    @Style.setter
    @classmethod
    def Style(clsvalue: CurvatureStyle) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: CurvatureAnalysisSettingsState) -> None: ...


class CurvatureAnalysisSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def GaussRange(self) -> Interval: ...
    @property
    def MaxRadiusRange(self) -> Interval: ...
    @property
    def MeanRange(self) -> Interval: ...
    @property
    def MinRadiusRange(self) -> Interval: ...
    @property
    def Style(self) -> CurvatureStyle: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @GaussRange.setter
    def GaussRange(self, value: Interval) -> None: ...
    @MaxRadiusRange.setter
    def MaxRadiusRange(self, value: Interval) -> None: ...
    @MeanRange.setter
    def MeanRange(self, value: Interval) -> None: ...
    @MinRadiusRange.setter
    def MinRadiusRange(self, value: Interval) -> None: ...
    @Style.setter
    def Style(self, value: CurvatureStyle) -> None: ...
    @overload
    def ToString(self) -> str: ...


class CurvatureGraphSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def CurveHairColor(cls) -> Color: ...
    @property
    @classmethod
    def HairDensity(cls) -> int: ...
    @property
    @classmethod
    def HairScale(cls) -> int: ...
    @property
    @classmethod
    def SampleDensity(cls) -> int: ...
    @property
    @classmethod
    def SrfUHair(cls) -> bool: ...
    @property
    @classmethod
    def SrfVHair(cls) -> bool: ...
    @property
    @classmethod
    def SurfaceUHairColor(cls) -> Color: ...
    @property
    @classmethod
    def SurfaceVHairColor(cls) -> Color: ...
    @overload
    @staticmethod
    def GetCurrentState() -> CurvatureGraphSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> CurvatureGraphSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @CurveHairColor.setter
    @classmethod
    def CurveHairColor(clsvalue: Color) -> None: ...
    @HairDensity.setter
    @classmethod
    def HairDensity(clsvalue: int) -> None: ...
    @HairScale.setter
    @classmethod
    def HairScale(clsvalue: int) -> None: ...
    @SampleDensity.setter
    @classmethod
    def SampleDensity(clsvalue: int) -> None: ...
    @SrfUHair.setter
    @classmethod
    def SrfUHair(clsvalue: bool) -> None: ...
    @SrfVHair.setter
    @classmethod
    def SrfVHair(clsvalue: bool) -> None: ...
    @SurfaceUHairColor.setter
    @classmethod
    def SurfaceUHairColor(clsvalue: Color) -> None: ...
    @SurfaceVHairColor.setter
    @classmethod
    def SurfaceVHairColor(clsvalue: Color) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: CurvatureGraphSettingsState) -> None: ...


class CurvatureGraphSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def CurveHairColor(self) -> Color: ...
    @property
    def HairDensity(self) -> int: ...
    @property
    def HairScale(self) -> int: ...
    @property
    def SampleDensity(self) -> int: ...
    @property
    def SrfUHair(self) -> bool: ...
    @property
    def SrfVHair(self) -> bool: ...
    @property
    def SurfaceUHairColor(self) -> Color: ...
    @property
    def SurfaceVHairColor(self) -> Color: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @CurveHairColor.setter
    def CurveHairColor(self, value: Color) -> None: ...
    @HairDensity.setter
    def HairDensity(self, value: int) -> None: ...
    @HairScale.setter
    def HairScale(self, value: int) -> None: ...
    @SampleDensity.setter
    def SampleDensity(self, value: int) -> None: ...
    @SrfUHair.setter
    def SrfUHair(self, value: bool) -> None: ...
    @SrfVHair.setter
    def SrfVHair(self, value: bool) -> None: ...
    @SurfaceUHairColor.setter
    def SurfaceUHairColor(self, value: Color) -> None: ...
    @SurfaceVHairColor.setter
    def SurfaceVHairColor(self, value: Color) -> None: ...
    @overload
    def ToString(self) -> str: ...


class CurvatureStyle(Enum):
    Gaussian = 0
    Mean = 1
    MinRadius = 2
    MaxRadius = 3


class DraftAngleAnalysisSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def AngleRange(cls) -> Interval: ...
    @property
    @classmethod
    def ShowIsoCurves(cls) -> bool: ...
    @property
    @classmethod
    def UpDirection(cls) -> Vector3d: ...
    @overload
    @staticmethod
    def GetCurrentState() -> DraftAngleAnalysisSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> DraftAngleAnalysisSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @AngleRange.setter
    @classmethod
    def AngleRange(clsvalue: Interval) -> None: ...
    @ShowIsoCurves.setter
    @classmethod
    def ShowIsoCurves(clsvalue: bool) -> None: ...
    @UpDirection.setter
    @classmethod
    def UpDirection(clsvalue: Vector3d) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: DraftAngleAnalysisSettingsState) -> None: ...


class DraftAngleAnalysisSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AngleRange(self) -> Interval: ...
    @property
    def ShowIsoCurves(self) -> bool: ...
    @property
    def UpDirection(self) -> Vector3d: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AngleRange.setter
    def AngleRange(self, value: Interval) -> None: ...
    @ShowIsoCurves.setter
    def ShowIsoCurves(self, value: bool) -> None: ...
    @UpDirection.setter
    def UpDirection(self, value: Vector3d) -> None: ...
    @overload
    def ToString(self) -> str: ...


class EdgeAnalysisSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def ShowEdgeColor(cls) -> Color: ...
    @property
    @classmethod
    def ShowEdges(cls) -> int: ...
    @overload
    @staticmethod
    def GetCurrentState() -> EdgeAnalysisSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> EdgeAnalysisSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @ShowEdgeColor.setter
    @classmethod
    def ShowEdgeColor(clsvalue: Color) -> None: ...
    @ShowEdges.setter
    @classmethod
    def ShowEdges(clsvalue: int) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: EdgeAnalysisSettingsState) -> None: ...


class EdgeAnalysisSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ShowEdgeColor(self) -> Color: ...
    @property
    def ShowEdges(self) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @ShowEdgeColor.setter
    def ShowEdgeColor(self, value: Color) -> None: ...
    @ShowEdges.setter
    def ShowEdges(self, value: int) -> None: ...
    @overload
    def ToString(self) -> str: ...


from System import TimeSpan
class FileSettings:
    @overload
    @staticmethod
    def AddSearchPath(folder: str, index: int) -> int: ...
    @overload
    @staticmethod
    def AutoSaveBeforeCommands() -> Iterable[str]: ...
    @overload
    @staticmethod
    def DefaultTemplateFolderForLanguageID(languageID: int) -> str: ...
    @overload
    @staticmethod
    def DeleteSearchPath(folder: str) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def FindFile(fileName: str) -> str: ...
    @property
    @classmethod
    def AutoSaveEnabled(cls) -> bool: ...
    @property
    @classmethod
    def AutoSaveFile(cls) -> str: ...
    @property
    @classmethod
    def AutoSaveInterval(cls) -> TimeSpan: ...
    @property
    @classmethod
    def AutoSaveMeshes(cls) -> bool: ...
    @property
    @classmethod
    def ClipboardCopyToPreviousRhinoVersion(cls) -> bool: ...
    @property
    @classmethod
    def ClipboardOnExit(cls) -> ClipboardState: ...
    @property
    @classmethod
    def CreateBackupFiles(cls) -> bool: ...
    @property
    @classmethod
    def DefaultRuiFile(cls) -> str: ...
    @property
    @classmethod
    def ExecutableFolder(cls) -> str: ...
    @property
    @classmethod
    def FileLockingEnabled(cls) -> bool: ...
    @property
    @classmethod
    def FileLockingOpenWarning(cls) -> bool: ...
    @property
    @classmethod
    def HelpFilePath(cls) -> str: ...
    @property
    @classmethod
    def InstallFolder(cls) -> DirectoryInfo: ...
    @property
    @classmethod
    def LocalProfileDataFolder(cls) -> str: ...
    @property
    @classmethod
    def SaveViewChanges(cls) -> bool: ...
    @property
    @classmethod
    def SearchPathCount(cls) -> int: ...
    @property
    @classmethod
    def TemplateFile(cls) -> str: ...
    @property
    @classmethod
    def TemplateFolder(cls) -> str: ...
    @property
    @classmethod
    def WorkingFolder(cls) -> str: ...
    @overload
    @staticmethod
    def GetCurrentState() -> FileSettingsState: ...
    @overload
    @staticmethod
    def GetDataFolder(currentUser: bool) -> str: ...
    @overload
    @staticmethod
    def GetDefaultState() -> FileSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetSearchPaths() -> Iterable[str]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RecentlyOpenedFiles() -> Iterable[str]: ...
    @AutoSaveEnabled.setter
    @classmethod
    def AutoSaveEnabled(clsvalue: bool) -> None: ...
    @AutoSaveFile.setter
    @classmethod
    def AutoSaveFile(clsvalue: str) -> None: ...
    @AutoSaveInterval.setter
    @classmethod
    def AutoSaveInterval(clsvalue: TimeSpan) -> None: ...
    @AutoSaveMeshes.setter
    @classmethod
    def AutoSaveMeshes(clsvalue: bool) -> None: ...
    @ClipboardCopyToPreviousRhinoVersion.setter
    @classmethod
    def ClipboardCopyToPreviousRhinoVersion(clsvalue: bool) -> None: ...
    @ClipboardOnExit.setter
    @classmethod
    def ClipboardOnExit(clsvalue: ClipboardState) -> None: ...
    @CreateBackupFiles.setter
    @classmethod
    def CreateBackupFiles(clsvalue: bool) -> None: ...
    @FileLockingEnabled.setter
    @classmethod
    def FileLockingEnabled(clsvalue: bool) -> None: ...
    @FileLockingOpenWarning.setter
    @classmethod
    def FileLockingOpenWarning(clsvalue: bool) -> None: ...
    @SaveViewChanges.setter
    @classmethod
    def SaveViewChanges(clsvalue: bool) -> None: ...
    @TemplateFile.setter
    @classmethod
    def TemplateFile(clsvalue: str) -> None: ...
    @TemplateFolder.setter
    @classmethod
    def TemplateFolder(clsvalue: str) -> None: ...
    @WorkingFolder.setter
    @classmethod
    def WorkingFolder(clsvalue: str) -> None: ...
    @overload
    @staticmethod
    def SetAutoSaveBeforeCommands(commands: Iterable[str]) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: FileSettingsState) -> None: ...


from System import TimeSpan
class FileSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AutoSaveEnabled(self) -> bool: ...
    @property
    def AutoSaveInterval(self) -> TimeSpan: ...
    @property
    def AutoSaveMeshes(self) -> bool: ...
    @property
    def ClipboardCopyToPreviousRhinoVersion(self) -> bool: ...
    @property
    def ClipboardOnExit(self) -> ClipboardState: ...
    @property
    def CreateBackupFiles(self) -> bool: ...
    @property
    def FileLockingEnabled(self) -> bool: ...
    @property
    def FileLockingOpenWarning(self) -> bool: ...
    @property
    def SaveViewChanges(self) -> bool: ...
    @property
    def TemplateFileDir(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AutoSaveEnabled.setter
    def AutoSaveEnabled(self, value: bool) -> None: ...
    @AutoSaveInterval.setter
    def AutoSaveInterval(self, value: TimeSpan) -> None: ...
    @AutoSaveMeshes.setter
    def AutoSaveMeshes(self, value: bool) -> None: ...
    @ClipboardCopyToPreviousRhinoVersion.setter
    def ClipboardCopyToPreviousRhinoVersion(self, value: bool) -> None: ...
    @ClipboardOnExit.setter
    def ClipboardOnExit(self, value: ClipboardState) -> None: ...
    @CreateBackupFiles.setter
    def CreateBackupFiles(self, value: bool) -> None: ...
    @FileLockingEnabled.setter
    def FileLockingEnabled(self, value: bool) -> None: ...
    @FileLockingOpenWarning.setter
    def FileLockingOpenWarning(self, value: bool) -> None: ...
    @SaveViewChanges.setter
    def SaveViewChanges(self, value: bool) -> None: ...
    @TemplateFileDir.setter
    def TemplateFileDir(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


from System import TimeSpan
class GeneralSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def AutoUpdateCommandHelp(cls) -> bool: ...
    @property
    @classmethod
    def ContextMenuDelay(cls) -> TimeSpan: ...
    @property
    @classmethod
    def EnableContextMenu(cls) -> bool: ...
    @property
    @classmethod
    def MaximumPopupMenuLines(cls) -> int: ...
    @property
    @classmethod
    def MaximumUndoMemoryMb(cls) -> int: ...
    @property
    @classmethod
    def MiddleMouseMacro(cls) -> str: ...
    @property
    @classmethod
    def MiddleMouseMode(cls) -> MiddleMouseMode: ...
    @property
    @classmethod
    def MiddleMousePopupToolbar(cls) -> str: ...
    @property
    @classmethod
    def MinimumUndoSteps(cls) -> int: ...
    @property
    @classmethod
    def MouseSelectMode(cls) -> MouseSelectMode: ...
    @property
    @classmethod
    def NewObjectIsoparmCount(cls) -> int: ...
    @property
    @classmethod
    def UseExtrusions(cls) -> bool: ...
    @overload
    @staticmethod
    def GetCurrentState() -> GeneralSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> GeneralSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AutoUpdateCommandHelp.setter
    @classmethod
    def AutoUpdateCommandHelp(clsvalue: bool) -> None: ...
    @ContextMenuDelay.setter
    @classmethod
    def ContextMenuDelay(clsvalue: TimeSpan) -> None: ...
    @EnableContextMenu.setter
    @classmethod
    def EnableContextMenu(clsvalue: bool) -> None: ...
    @MaximumPopupMenuLines.setter
    @classmethod
    def MaximumPopupMenuLines(clsvalue: int) -> None: ...
    @MaximumUndoMemoryMb.setter
    @classmethod
    def MaximumUndoMemoryMb(clsvalue: int) -> None: ...
    @MiddleMouseMacro.setter
    @classmethod
    def MiddleMouseMacro(clsvalue: str) -> None: ...
    @MiddleMouseMode.setter
    @classmethod
    def MiddleMouseMode(clsvalue: MiddleMouseMode) -> None: ...
    @MiddleMousePopupToolbar.setter
    @classmethod
    def MiddleMousePopupToolbar(clsvalue: str) -> None: ...
    @MinimumUndoSteps.setter
    @classmethod
    def MinimumUndoSteps(clsvalue: int) -> None: ...
    @MouseSelectMode.setter
    @classmethod
    def MouseSelectMode(clsvalue: MouseSelectMode) -> None: ...
    @NewObjectIsoparmCount.setter
    @classmethod
    def NewObjectIsoparmCount(clsvalue: int) -> None: ...
    @overload
    def ToString(self) -> str: ...


from System import TimeSpan
class GeneralSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AutoUpdateCommandHelp(self) -> bool: ...
    @property
    def ContextMenuDelay(self) -> TimeSpan: ...
    @property
    def EnableContextMenu(self) -> bool: ...
    @property
    def MaximumPopupMenuLines(self) -> int: ...
    @property
    def MaximumUndoMemoryMb(self) -> int: ...
    @property
    def MiddleMouseMacro(self) -> str: ...
    @property
    def MiddleMouseMode(self) -> MiddleMouseMode: ...
    @property
    def MiddleMousePopupToolbar(self) -> str: ...
    @property
    def MinimumUndoSteps(self) -> int: ...
    @property
    def MouseSelectMode(self) -> MouseSelectMode: ...
    @property
    def NewObjectIsoparmCount(self) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AutoUpdateCommandHelp.setter
    def AutoUpdateCommandHelp(self, value: bool) -> None: ...
    @ContextMenuDelay.setter
    def ContextMenuDelay(self, value: TimeSpan) -> None: ...
    @EnableContextMenu.setter
    def EnableContextMenu(self, value: bool) -> None: ...
    @MaximumPopupMenuLines.setter
    def MaximumPopupMenuLines(self, value: int) -> None: ...
    @MaximumUndoMemoryMb.setter
    def MaximumUndoMemoryMb(self, value: int) -> None: ...
    @MiddleMouseMacro.setter
    def MiddleMouseMacro(self, value: str) -> None: ...
    @MiddleMouseMode.setter
    def MiddleMouseMode(self, value: MiddleMouseMode) -> None: ...
    @MiddleMousePopupToolbar.setter
    def MiddleMousePopupToolbar(self, value: str) -> None: ...
    @MinimumUndoSteps.setter
    def MinimumUndoSteps(self, value: int) -> None: ...
    @MouseSelectMode.setter
    def MouseSelectMode(self, value: MouseSelectMode) -> None: ...
    @NewObjectIsoparmCount.setter
    def NewObjectIsoparmCount(self, value: int) -> None: ...
    @overload
    def ToString(self) -> str: ...


class HistorySettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def BrokenRecordWarningEnabled(cls) -> bool: ...
    @property
    @classmethod
    def ObjectLockingEnabled(cls) -> bool: ...
    @property
    @classmethod
    def RecordingEnabled(cls) -> bool: ...
    @property
    @classmethod
    def RecordNextCommand(cls) -> bool: ...
    @property
    @classmethod
    def UpdateEnabled(cls) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @BrokenRecordWarningEnabled.setter
    @classmethod
    def BrokenRecordWarningEnabled(clsvalue: bool) -> None: ...
    @ObjectLockingEnabled.setter
    @classmethod
    def ObjectLockingEnabled(clsvalue: bool) -> None: ...
    @RecordingEnabled.setter
    @classmethod
    def RecordingEnabled(clsvalue: bool) -> None: ...
    @RecordNextCommand.setter
    @classmethod
    def RecordNextCommand(clsvalue: bool) -> None: ...
    @UpdateEnabled.setter
    @classmethod
    def UpdateEnabled(clsvalue: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...


class Installation(Enum):
    Undefined = 0
    Commercial = 1
    Educational = 2
    EducationalLab = 3
    NotForResale = 4
    NotForResaleLab = 5
    Beta = 6
    BetaLab = 7
    Evaluation = 8
    Corporate = 9
    EvaluationTimed = 10


class KeyboardShortcut:
    @overload
    def __init__(self): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def Key(self) -> KeyboardKey: ...
    @property
    def Macro(self) -> str: ...
    @property
    def Modifier(self) -> ModifierKey: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @Key.setter
    def Key(self, value: KeyboardKey) -> None: ...
    @Macro.setter
    def Macro(self, value: str) -> None: ...
    @Modifier.setter
    def Modifier(self, value: ModifierKey) -> None: ...
    @overload
    def ToString(self) -> str: ...


class LicenseNode(Enum):
    Standalone = 0
    Network = 1
    NetworkCheckedOut = 2


class MiddleMouseMode(Enum):
    PopupMenu = 0
    PopupToolbar = 1
    RunMacro = 2


class ModelAidSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def AltPlusArrow(cls) -> bool: ...
    @property
    @classmethod
    def AutoAlignCPlane(cls) -> bool: ...
    @property
    @classmethod
    def AutoCPlaneAlignment(cls) -> int: ...
    @property
    @classmethod
    def AutoGumballEnabled(cls) -> bool: ...
    @property
    @classmethod
    def ControlPolygonDisplayDensity(cls) -> int: ...
    @property
    @classmethod
    def CtrlNudgeKeyStep(cls) -> float: ...
    @property
    @classmethod
    def DisplayControlPolygon(cls) -> bool: ...
    @property
    @classmethod
    def ExtendToApparentIntersection(cls) -> bool: ...
    @property
    @classmethod
    def ExtendTrimLines(cls) -> bool: ...
    @property
    @classmethod
    def GridSnap(cls) -> bool: ...
    @property
    @classmethod
    def GumballAutoReset(cls) -> bool: ...
    @property
    @classmethod
    def GumballExtrudeMergeFaces(cls) -> bool: ...
    @property
    @classmethod
    def HighlightControlPolygon(cls) -> bool: ...
    @property
    @classmethod
    def MousePickboxRadius(cls) -> int: ...
    @property
    @classmethod
    def NudgeKeyStep(cls) -> float: ...
    @property
    @classmethod
    def NudgeMode(cls) -> int: ...
    @property
    @classmethod
    def OnlySnapToSelected(cls) -> bool: ...
    @property
    @classmethod
    def OrientAutoCPlaneToView(cls) -> bool: ...
    @property
    @classmethod
    def Ortho(cls) -> bool: ...
    @property
    @classmethod
    def OrthoAngle(cls) -> float: ...
    @property
    @classmethod
    def OrthoUseZ(cls) -> bool: ...
    @property
    @classmethod
    def Osnap(cls) -> bool: ...
    @property
    @classmethod
    def OsnapCursorMode(cls) -> CursorMode: ...
    @property
    @classmethod
    def OsnapModes(cls) -> OsnapModes: ...
    @property
    @classmethod
    def OsnapPickboxRadius(cls) -> int: ...
    @property
    @classmethod
    def Planar(cls) -> bool: ...
    @property
    @classmethod
    def PointDisplay(cls) -> PointDisplayMode: ...
    @property
    @classmethod
    def ProjectSnapToCPlane(cls) -> bool: ...
    @property
    @classmethod
    def ShiftNudgeKeyStep(cls) -> float: ...
    @property
    @classmethod
    def SnappyGumballEnabled(cls) -> bool: ...
    @property
    @classmethod
    def SnapToFiltered(cls) -> bool: ...
    @property
    @classmethod
    def SnapToLocked(cls) -> bool: ...
    @property
    @classmethod
    def SnapToOccluded(cls) -> bool: ...
    @property
    @classmethod
    def StickyAutoCPlane(cls) -> bool: ...
    @property
    @classmethod
    def UniversalConstructionPlaneMode(cls) -> bool: ...
    @property
    @classmethod
    def UseHorizontalDialog(cls) -> bool: ...
    @overload
    @staticmethod
    def GetCurrentState() -> ModelAidSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> ModelAidSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AltPlusArrow.setter
    @classmethod
    def AltPlusArrow(clsvalue: bool) -> None: ...
    @AutoAlignCPlane.setter
    @classmethod
    def AutoAlignCPlane(clsvalue: bool) -> None: ...
    @AutoCPlaneAlignment.setter
    @classmethod
    def AutoCPlaneAlignment(clsvalue: int) -> None: ...
    @AutoGumballEnabled.setter
    @classmethod
    def AutoGumballEnabled(clsvalue: bool) -> None: ...
    @ControlPolygonDisplayDensity.setter
    @classmethod
    def ControlPolygonDisplayDensity(clsvalue: int) -> None: ...
    @CtrlNudgeKeyStep.setter
    @classmethod
    def CtrlNudgeKeyStep(clsvalue: float) -> None: ...
    @DisplayControlPolygon.setter
    @classmethod
    def DisplayControlPolygon(clsvalue: bool) -> None: ...
    @ExtendToApparentIntersection.setter
    @classmethod
    def ExtendToApparentIntersection(clsvalue: bool) -> None: ...
    @ExtendTrimLines.setter
    @classmethod
    def ExtendTrimLines(clsvalue: bool) -> None: ...
    @GridSnap.setter
    @classmethod
    def GridSnap(clsvalue: bool) -> None: ...
    @GumballAutoReset.setter
    @classmethod
    def GumballAutoReset(clsvalue: bool) -> None: ...
    @GumballExtrudeMergeFaces.setter
    @classmethod
    def GumballExtrudeMergeFaces(clsvalue: bool) -> None: ...
    @HighlightControlPolygon.setter
    @classmethod
    def HighlightControlPolygon(clsvalue: bool) -> None: ...
    @MousePickboxRadius.setter
    @classmethod
    def MousePickboxRadius(clsvalue: int) -> None: ...
    @NudgeKeyStep.setter
    @classmethod
    def NudgeKeyStep(clsvalue: float) -> None: ...
    @NudgeMode.setter
    @classmethod
    def NudgeMode(clsvalue: int) -> None: ...
    @OnlySnapToSelected.setter
    @classmethod
    def OnlySnapToSelected(clsvalue: bool) -> None: ...
    @OrientAutoCPlaneToView.setter
    @classmethod
    def OrientAutoCPlaneToView(clsvalue: bool) -> None: ...
    @Ortho.setter
    @classmethod
    def Ortho(clsvalue: bool) -> None: ...
    @OrthoAngle.setter
    @classmethod
    def OrthoAngle(clsvalue: float) -> None: ...
    @OrthoUseZ.setter
    @classmethod
    def OrthoUseZ(clsvalue: bool) -> None: ...
    @Osnap.setter
    @classmethod
    def Osnap(clsvalue: bool) -> None: ...
    @OsnapCursorMode.setter
    @classmethod
    def OsnapCursorMode(clsvalue: CursorMode) -> None: ...
    @OsnapModes.setter
    @classmethod
    def OsnapModes(clsvalue: OsnapModes) -> None: ...
    @OsnapPickboxRadius.setter
    @classmethod
    def OsnapPickboxRadius(clsvalue: int) -> None: ...
    @Planar.setter
    @classmethod
    def Planar(clsvalue: bool) -> None: ...
    @PointDisplay.setter
    @classmethod
    def PointDisplay(clsvalue: PointDisplayMode) -> None: ...
    @ProjectSnapToCPlane.setter
    @classmethod
    def ProjectSnapToCPlane(clsvalue: bool) -> None: ...
    @ShiftNudgeKeyStep.setter
    @classmethod
    def ShiftNudgeKeyStep(clsvalue: float) -> None: ...
    @SnappyGumballEnabled.setter
    @classmethod
    def SnappyGumballEnabled(clsvalue: bool) -> None: ...
    @SnapToFiltered.setter
    @classmethod
    def SnapToFiltered(clsvalue: bool) -> None: ...
    @SnapToLocked.setter
    @classmethod
    def SnapToLocked(clsvalue: bool) -> None: ...
    @SnapToOccluded.setter
    @classmethod
    def SnapToOccluded(clsvalue: bool) -> None: ...
    @StickyAutoCPlane.setter
    @classmethod
    def StickyAutoCPlane(clsvalue: bool) -> None: ...
    @UniversalConstructionPlaneMode.setter
    @classmethod
    def UniversalConstructionPlaneMode(clsvalue: bool) -> None: ...
    @UseHorizontalDialog.setter
    @classmethod
    def UseHorizontalDialog(clsvalue: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: ModelAidSettingsState) -> None: ...


class ModelAidSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AltPlusArrow(self) -> bool: ...
    @property
    def AutoAlignCPlane(self) -> bool: ...
    @property
    def AutoCPlaneAlignment(self) -> int: ...
    @property
    def ControlPolygonDisplayDensity(self) -> int: ...
    @property
    def CtrlNudgeKeyStep(self) -> float: ...
    @property
    def DisplayControlPolygon(self) -> bool: ...
    @property
    def ExtendToApparentIntersection(self) -> bool: ...
    @property
    def ExtendTrimLines(self) -> bool: ...
    @property
    def GridSnap(self) -> bool: ...
    @property
    def HighlightControlPolygon(self) -> bool: ...
    @property
    def MousePickboxRadius(self) -> int: ...
    @property
    def NudgeKeyStep(self) -> float: ...
    @property
    def NudgeMode(self) -> int: ...
    @property
    def OrientAutoCPlaneToView(self) -> bool: ...
    @property
    def Ortho(self) -> bool: ...
    @property
    def OrthoAngle(self) -> float: ...
    @property
    def OrthoUseZ(self) -> bool: ...
    @property
    def Osnap(self) -> bool: ...
    @property
    def OsnapCursorMode(self) -> CursorMode: ...
    @property
    def OsnapModes(self) -> OsnapModes: ...
    @property
    def OsnapPickboxRadius(self) -> int: ...
    @property
    def Planar(self) -> bool: ...
    @property
    def PointDisplay(self) -> PointDisplayMode: ...
    @property
    def ProjectSnapToCPlane(self) -> bool: ...
    @property
    def ShiftNudgeKeyStep(self) -> float: ...
    @property
    def SnapToLocked(self) -> bool: ...
    @property
    def StickyAutoCPlane(self) -> bool: ...
    @property
    def UniversalConstructionPlaneMode(self) -> bool: ...
    @property
    def UseHorizontalDialog(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AltPlusArrow.setter
    def AltPlusArrow(self, value: bool) -> None: ...
    @AutoAlignCPlane.setter
    def AutoAlignCPlane(self, value: bool) -> None: ...
    @AutoCPlaneAlignment.setter
    def AutoCPlaneAlignment(self, value: int) -> None: ...
    @ControlPolygonDisplayDensity.setter
    def ControlPolygonDisplayDensity(self, value: int) -> None: ...
    @CtrlNudgeKeyStep.setter
    def CtrlNudgeKeyStep(self, value: float) -> None: ...
    @DisplayControlPolygon.setter
    def DisplayControlPolygon(self, value: bool) -> None: ...
    @ExtendToApparentIntersection.setter
    def ExtendToApparentIntersection(self, value: bool) -> None: ...
    @ExtendTrimLines.setter
    def ExtendTrimLines(self, value: bool) -> None: ...
    @GridSnap.setter
    def GridSnap(self, value: bool) -> None: ...
    @HighlightControlPolygon.setter
    def HighlightControlPolygon(self, value: bool) -> None: ...
    @MousePickboxRadius.setter
    def MousePickboxRadius(self, value: int) -> None: ...
    @NudgeKeyStep.setter
    def NudgeKeyStep(self, value: float) -> None: ...
    @NudgeMode.setter
    def NudgeMode(self, value: int) -> None: ...
    @OrientAutoCPlaneToView.setter
    def OrientAutoCPlaneToView(self, value: bool) -> None: ...
    @Ortho.setter
    def Ortho(self, value: bool) -> None: ...
    @OrthoAngle.setter
    def OrthoAngle(self, value: float) -> None: ...
    @OrthoUseZ.setter
    def OrthoUseZ(self, value: bool) -> None: ...
    @Osnap.setter
    def Osnap(self, value: bool) -> None: ...
    @OsnapCursorMode.setter
    def OsnapCursorMode(self, value: CursorMode) -> None: ...
    @OsnapModes.setter
    def OsnapModes(self, value: OsnapModes) -> None: ...
    @OsnapPickboxRadius.setter
    def OsnapPickboxRadius(self, value: int) -> None: ...
    @Planar.setter
    def Planar(self, value: bool) -> None: ...
    @PointDisplay.setter
    def PointDisplay(self, value: PointDisplayMode) -> None: ...
    @ProjectSnapToCPlane.setter
    def ProjectSnapToCPlane(self, value: bool) -> None: ...
    @ShiftNudgeKeyStep.setter
    def ShiftNudgeKeyStep(self, value: float) -> None: ...
    @SnapToLocked.setter
    def SnapToLocked(self, value: bool) -> None: ...
    @StickyAutoCPlane.setter
    def StickyAutoCPlane(self, value: bool) -> None: ...
    @UniversalConstructionPlaneMode.setter
    def UniversalConstructionPlaneMode(self, value: bool) -> None: ...
    @UseHorizontalDialog.setter
    def UseHorizontalDialog(self, value: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...


class MouseSelectMode(Enum):
    Crossing = 0
    Window = 1
    Combo = 2


class NeverRepeatList:
    @overload
    @staticmethod
    def CommandNames() -> Iterable[str]: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def UseNeverRepeatList(cls) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def SetList(commandNames: Iterable[str]) -> int: ...
    @overload
    def ToString(self) -> str: ...


from Rhino import AntialiasLevel
class OpenGLSettings:
    @overload
    def __init__(self): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def AntialiasLevel(cls) -> AntialiasLevel: ...
    @overload
    @staticmethod
    def GetCurrentState() -> OpenGLSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> OpenGLSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @AntialiasLevel.setter
    @classmethod
    def AntialiasLevel(clsvalue: AntialiasLevel) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: OpenGLSettingsState) -> None: ...


from Rhino import AntialiasLevel
class OpenGLSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AntialiasLevel(self) -> AntialiasLevel: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AntialiasLevel.setter
    def AntialiasLevel(self, value: AntialiasLevel) -> None: ...
    @overload
    def ToString(self) -> str: ...


class OsnapModes(Enum):
    # None = 0
    Near = 2
    Focus = 8
    Center = 32
    Vertex = 64
    Knot = 128
    Quadrant = 512
    Midpoint = 2048
    Intersection = 8192
    End = 131072
    Perpendicular = 524288
    Tangent = 2097152
    Point = 134217728


class PackageManagerSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def Sources(cls) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @Sources.setter
    @classmethod
    def Sources(clsvalue: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class PaintColor(Enum):
    NormalStart = 0
    NormalEnd = 1
    NormalBorder = 2
    HotStart = 3
    HotEnd = 4
    HotBorder = 5
    PressedStart = 6
    PressedEnd = 7
    PressedBorder = 8
    TextEnabled = 9
    TextDisabled = 10
    MouseOverControlStart = 11
    MouseOverControlEnd = 12
    MouseOverControlBorder = 13
    ActiveCaption = 14
    InactiveCaption = 15
    PanelBackground = 16
    ActiveViewportTitle = 17
    InactiveViewportTitle = 18
    ModifiedValueControlColor = 19
    EditBoxBackground = 20
    GridLinesOnPanelBackground = 21
    GridLinesOnEditBoxBackground = 22
    InactiveTabBackground = 23


class PointDisplayMode(Enum):
    WorldPoint = 0
    CplanePoint = 1


class SelectionFilterSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def Enabled(cls) -> bool: ...
    @property
    @classmethod
    def GlobalGeometryFilter(cls) -> ObjectType: ...
    @property
    @classmethod
    def OneShotGeometryFilter(cls) -> ObjectType: ...
    @property
    @classmethod
    def SubObjectSelect(cls) -> bool: ...
    @overload
    @staticmethod
    def GetCurrentState() -> SelectionFilterSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> SelectionFilterSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @Enabled.setter
    @classmethod
    def Enabled(clsvalue: bool) -> None: ...
    @GlobalGeometryFilter.setter
    @classmethod
    def GlobalGeometryFilter(clsvalue: ObjectType) -> None: ...
    @OneShotGeometryFilter.setter
    @classmethod
    def OneShotGeometryFilter(clsvalue: ObjectType) -> None: ...
    @SubObjectSelect.setter
    @classmethod
    def SubObjectSelect(clsvalue: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: SelectionFilterSettingsState) -> None: ...


class SelectionFilterSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def Enabled(self) -> bool: ...
    @property
    def GlobalGeometryFilter(self) -> ObjectType: ...
    @property
    def OneShotGeometryFilter(self) -> ObjectType: ...
    @property
    def SubObjectSelect(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...
    @GlobalGeometryFilter.setter
    def GlobalGeometryFilter(self, value: ObjectType) -> None: ...
    @OneShotGeometryFilter.setter
    def OneShotGeometryFilter(self, value: ObjectType) -> None: ...
    @SubObjectSelect.setter
    def SubObjectSelect(self, value: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...


class ShortcutKey(Enum):
    F1 = 0
    F2 = 1
    F3 = 2
    F4 = 3
    F5 = 4
    F6 = 5
    F7 = 6
    F8 = 7
    F9 = 8
    F10 = 9
    F11 = 10
    F12 = 11
    CtrlF1 = 12
    CtrlF2 = 13
    CtrlF3 = 14
    CtrlF4 = 15
    CtrlF5 = 16
    CtrlF6 = 17
    CtrlF7 = 18
    CtrlF8 = 19
    CtrlF9 = 20
    CtrlF10 = 21
    CtrlF11 = 22
    CtrlF12 = 23
    ShiftCtrlF1 = 24
    ShiftCtrlF2 = 25
    ShiftCtrlF3 = 26
    ShiftCtrlF4 = 27
    ShiftCtrlF5 = 28
    ShiftCtrlF6 = 29
    ShiftCtrlF7 = 30
    ShiftCtrlF8 = 31
    ShiftCtrlF9 = 32
    ShiftCtrlF10 = 33
    ShiftCtrlF11 = 34
    ShiftCtrlF12 = 35
    AltCtrlF1 = 36
    AltCtrlF2 = 37
    AltCtrlF3 = 38
    AltCtrlF4 = 39
    AltCtrlF5 = 40
    AltCtrlF6 = 41
    AltCtrlF7 = 42
    AltCtrlF8 = 43
    AltCtrlF9 = 44
    AltCtrlF10 = 45
    AltCtrlF11 = 46
    AltCtrlF12 = 47
    CtrlA = 48
    CtrlB = 49
    CtrlC = 50
    CtrlD = 51
    CtrlE = 52
    CtrlF = 53
    CtrlG = 54
    CtrlH = 55
    CtrlI = 56
    CtrlJ = 57
    CtrlK = 58
    CtrlL = 59
    CtrlM = 60
    CtrlN = 61
    CtrlO = 62
    CtrlP = 63
    CtrlQ = 64
    CtrlR = 65
    CtrlS = 66
    CtrlT = 67
    CtrlU = 68
    CtrlV = 69
    CtrlW = 70
    CtrlX = 71
    CtrlY = 72
    CtrlZ = 73
    ShiftCtrlA = 74
    ShiftCtrlB = 75
    ShiftCtrlC = 76
    ShiftCtrlD = 77
    ShiftCtrlE = 78
    ShiftCtrlF = 79
    ShiftCtrlG = 80
    ShiftCtrlH = 81
    ShiftCtrlI = 82
    ShiftCtrlJ = 83
    ShiftCtrlK = 84
    ShiftCtrlL = 85
    ShiftCtrlM = 86
    ShiftCtrlN = 87
    ShiftCtrlO = 88
    ShiftCtrlP = 89
    ShiftCtrlQ = 90
    ShiftCtrlR = 91
    ShiftCtrlS = 92
    ShiftCtrlT = 93
    ShiftCtrlU = 94
    ShiftCtrlV = 95
    ShiftCtrlW = 96
    ShiftCtrlX = 97
    ShiftCtrlY = 98
    ShiftCtrlZ = 99
    AltCtrlA = 100
    AltCtrlB = 101
    AltCtrlC = 102
    AltCtrlD = 103
    AltCtrlE = 104
    AltCtrlF = 105
    AltCtrlG = 106
    AltCtrlH = 107
    AltCtrlI = 108
    AltCtrlJ = 109
    AltCtrlK = 110
    AltCtrlL = 111
    AltCtrlM = 112
    AltCtrlN = 113
    AltCtrlO = 114
    AltCtrlP = 115
    AltCtrlQ = 116
    AltCtrlR = 117
    AltCtrlS = 118
    AltCtrlT = 119
    AltCtrlU = 120
    AltCtrlV = 121
    AltCtrlW = 122
    AltCtrlX = 123
    AltCtrlY = 124
    AltCtrlZ = 125
    Ctrl0 = 126
    Ctrl1 = 127
    Ctrl2 = 128
    Ctrl3 = 129
    Ctrl4 = 130
    Ctrl5 = 131
    Ctrl6 = 132
    Ctrl7 = 133
    Ctrl8 = 134
    Ctrl9 = 135
    ShiftCtrl0 = 136
    ShiftCtrl1 = 137
    ShiftCtrl2 = 138
    ShiftCtrl3 = 139
    ShiftCtrl4 = 140
    ShiftCtrl5 = 141
    ShiftCtrl6 = 142
    ShiftCtrl7 = 143
    ShiftCtrl8 = 144
    ShiftCtrl9 = 145
    AltCtrl0 = 146
    AltCtrl1 = 147
    AltCtrl2 = 148
    AltCtrl3 = 149
    AltCtrl4 = 150
    AltCtrl5 = 151
    AltCtrl6 = 152
    AltCtrl7 = 153
    AltCtrl8 = 154
    AltCtrl9 = 155
    Home = 156
    End = 157
    CtrlHome = 158
    CtrlEnd = 159
    ShiftHome = 160
    ShiftEnd = 161
    ShiftCtrlHome = 162
    ShiftCtrlEnd = 163
    AltCtrlHome = 164
    AltCtrlEnd = 165
    Tab = 166
    PageUp = 167
    PageDown = 168
    ShiftPageUp = 169
    ShiftPageDown = 170
    CtrlPageUp = 171
    CtrlPageDown = 172
    ShiftCtrlPageUp = 173
    ShiftCtrlPageDown = 174
    AltCtrlPageUp = 175
    AltCtrlPageDown = 176
    # None = 177
    AltHome = 178
    AltEnd = 179
    AltA = 180
    AltB = 181
    AltC = 182
    AltD = 183
    AltE = 184
    AltF = 185
    AltG = 186
    AltH = 187
    AltI = 188
    AltJ = 189
    AltK = 190
    AltL = 191
    AltM = 192
    AltN = 193
    AltO = 194
    AltP = 195
    AltQ = 196
    AltR = 197
    AltS = 198
    AltT = 199
    AltU = 200
    AltV = 201
    AltW = 202
    AltX = 203
    AltY = 204
    AltZ = 205
    Alt0 = 206
    Alt1 = 207
    Alt2 = 208
    Alt3 = 209
    Alt4 = 210
    Alt5 = 211
    Alt6 = 212
    Alt7 = 213
    Alt8 = 214
    Alt9 = 215
    AltF1 = 216
    AltF2 = 217
    AltF3 = 218
    AltF4 = 219
    AltF5 = 220
    AltF6 = 221
    AltF7 = 222
    AltF8 = 223
    AltF9 = 224
    AltF10 = 225
    AltF11 = 226
    AltF12 = 227
    AltShiftHome = 228
    AltShiftEnd = 229
    AltShiftA = 230
    AltShiftB = 231
    AltShiftC = 232
    AltShiftD = 233
    AltShiftE = 234
    AltShiftF = 235
    AltShiftG = 236
    AltShiftH = 237
    AltShiftI = 238
    AltShiftJ = 239
    AltShiftK = 240
    AltShiftL = 241
    AltShiftM = 242
    AltShiftN = 243
    AltShiftO = 244
    AltShiftP = 245
    AltShiftQ = 246
    AltShiftR = 247
    AltShiftS = 248
    AltShiftT = 249
    AltShiftU = 250
    AltShiftV = 251
    AltShiftW = 252
    AltShiftX = 253
    AltShiftY = 254
    AltShiftZ = 255
    AltShift0 = 256
    AltShift1 = 257
    AltShift2 = 258
    AltShift3 = 259
    AltShift4 = 260
    AltShift5 = 261
    AltShift6 = 262
    AltShift7 = 263
    AltShift8 = 264
    AltShift9 = 265
    AltShiftF1 = 266
    AltShiftF2 = 267
    AltShiftF3 = 268
    AltShiftF4 = 269
    AltShiftF5 = 270
    AltShiftF6 = 271
    AltShiftF7 = 272
    AltShiftF8 = 273
    AltShiftF9 = 274
    AltShiftF10 = 275
    AltShiftF11 = 276
    AltShiftF12 = 277
    MacControlHome = 278
    MacControlEnd = 279
    MacControlA = 280
    MacControlB = 281
    MacControlC = 282
    MacControlD = 283
    MacControlE = 284
    MacControlF = 285
    MacControlG = 286
    MacControlH = 287
    MacControlI = 288
    MacControlJ = 289
    MacControlK = 290
    MacControlL = 291
    MacControlM = 292
    MacControlN = 293
    MacControlO = 294
    MacControlP = 295
    MacControlQ = 296
    MacControlR = 297
    MacControlS = 298
    MacControlT = 299
    MacControlU = 300
    MacControlV = 301
    MacControlW = 302
    MacControlX = 303
    MacControlY = 304
    MacControlZ = 305
    MacControl0 = 306
    MacControl1 = 307
    MacControl2 = 308
    MacControl3 = 309
    MacControl4 = 310
    MacControl5 = 311
    MacControl6 = 312
    MacControl7 = 313
    MacControl8 = 314
    MacControl9 = 315
    MacControlF1 = 316
    MacControlF2 = 317
    MacControlF3 = 318
    MacControlF4 = 319
    MacControlF5 = 320
    MacControlF6 = 321
    MacControlF7 = 322
    MacControlF8 = 323
    MacControlF9 = 324
    MacControlF10 = 325
    MacControlF11 = 326
    MacControlF12 = 327
    MacControlAltHome = 328
    MacControlAltEnd = 329
    MacControlAltA = 330
    MacControlAltB = 331
    MacControlAltC = 332
    MacControlAltD = 333
    MacControlAltE = 334
    MacControlAltF = 335
    MacControlAltG = 336
    MacControlAltH = 337
    MacControlAltI = 338
    MacControlAltJ = 339
    MacControlAltK = 340
    MacControlAltL = 341
    MacControlAltM = 342
    MacControlAltN = 343
    MacControlAltO = 344
    MacControlAltP = 345
    MacControlAltQ = 346
    MacControlAltR = 347
    MacControlAltS = 348
    MacControlAltT = 349
    MacControlAltU = 350
    MacControlAltV = 351
    MacControlAltW = 352
    MacControlAltX = 353
    MacControlAltY = 354
    MacControlAltZ = 355
    MacControlAlt0 = 356
    MacControlAlt1 = 357
    MacControlAlt2 = 358
    MacControlAlt3 = 359
    MacControlAlt4 = 360
    MacControlAlt5 = 361
    MacControlAlt6 = 362
    MacControlAlt7 = 363
    MacControlAlt8 = 364
    MacControlAlt9 = 365
    MacControlAltF1 = 366
    MacControlAltF2 = 367
    MacControlAltF3 = 368
    MacControlAltF4 = 369
    MacControlAltF5 = 370
    MacControlAltF6 = 371
    MacControlAltF7 = 372
    MacControlAltF8 = 373
    MacControlAltF9 = 374
    MacControlAltF10 = 375
    MacControlAltF11 = 376
    MacControlAltF12 = 377
    MacControlOptionHome = 378
    MacControlOptionEnd = 379
    MacControlOptionA = 380
    MacControlOptionB = 381
    MacControlOptionC = 382
    MacControlOptionD = 383
    MacControlOptionE = 384
    MacControlOptionF = 385
    MacControlOptionG = 386
    MacControlOptionH = 387
    MacControlOptionI = 388
    MacControlOptionJ = 389
    MacControlOptionK = 390
    MacControlOptionL = 391
    MacControlOptionM = 392
    MacControlOptionN = 393
    MacControlOptionO = 394
    MacControlOptionP = 395
    MacControlOptionQ = 396
    MacControlOptionR = 397
    MacControlOptionS = 398
    MacControlOptionT = 399
    MacControlOptionU = 400
    MacControlOptionV = 401
    MacControlOptionW = 402
    MacControlOptionX = 403
    MacControlOptionY = 404
    MacControlOptionZ = 405
    MacControlOption0 = 406
    MacControlOption1 = 407
    MacControlOption2 = 408
    MacControlOption3 = 409
    MacControlOption4 = 410
    MacControlOption5 = 411
    MacControlOption6 = 412
    MacControlOption7 = 413
    MacControlOption8 = 414
    MacControlOption9 = 415
    MacControlOptionF1 = 416
    MacControlOptionF2 = 417
    MacControlOptionF3 = 418
    MacControlOptionF4 = 419
    MacControlOptionF5 = 420
    MacControlOptionF6 = 421
    MacControlOptionF7 = 422
    MacControlOptionF8 = 423
    MacControlOptionF9 = 424
    MacControlOptionF10 = 425
    MacControlOptionF11 = 426
    MacControlOptionF12 = 427
    MacControlShiftHome = 428
    MacControlShiftEnd = 429
    MacControlShiftA = 430
    MacControlShiftB = 431
    MacControlShiftC = 432
    MacControlShiftD = 433
    MacControlShiftE = 434
    MacControlShiftF = 435
    MacControlShiftG = 436
    MacControlShiftH = 437
    MacControlShiftI = 438
    MacControlShiftJ = 439
    MacControlShiftK = 440
    MacControlShiftL = 441
    MacControlShiftM = 442
    MacControlShiftN = 443
    MacControlShiftO = 444
    MacControlShiftP = 445
    MacControlShiftQ = 446
    MacControlShiftR = 447
    MacControlShiftS = 448
    MacControlShiftT = 449
    MacControlShiftU = 450
    MacControlShiftV = 451
    MacControlShiftW = 452
    MacControlShiftX = 453
    MacControlShiftY = 454
    MacControlShiftZ = 455
    MacControlShift0 = 456
    MacControlShift1 = 457
    MacControlShift2 = 458
    MacControlShift3 = 459
    MacControlShift4 = 460
    MacControlShift5 = 461
    MacControlShift6 = 462
    MacControlShift7 = 463
    MacControlShift8 = 464
    MacControlShift9 = 465
    MacControlShiftF1 = 466
    MacControlShiftF2 = 467
    MacControlShiftF3 = 468
    MacControlShiftF4 = 469
    MacControlShiftF5 = 470
    MacControlShiftF6 = 471
    MacControlShiftF7 = 472
    MacControlShiftF8 = 473
    MacControlShiftF9 = 474
    MacControlShiftF10 = 475
    MacControlShiftF11 = 476
    MacControlShiftF12 = 477


class ShortcutKeySettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetDefaults() -> Iterable[KeyboardShortcut]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLabel(key: ShortcutKey) -> str: ...
    @overload
    @staticmethod
    def GetMacro(key: ShortcutKey) -> str: ...
    @overload
    @staticmethod
    def GetShortcuts() -> Iterable[KeyboardShortcut]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def IsAcceptableKeyCombo(key: KeyboardKey, modifier: ModifierKey) -> bool: ...
    @overload
    @staticmethod
    def SetMacro(key: ShortcutKey, macro: str) -> None: ...
    @overload
    @staticmethod
    def SetMacro(key: KeyboardKey, modifier: ModifierKey, macro: str) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def Update(shortcuts: Iterable[KeyboardShortcut], replaceAll: bool) -> None: ...


class SmartTrackSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def ActivationDelayMilliseconds(cls) -> int: ...
    @property
    @classmethod
    def ActivePointColor(cls) -> Color: ...
    @property
    @classmethod
    def GuideColor(cls) -> Color: ...
    @property
    @classmethod
    def LineColor(cls) -> Color: ...
    @property
    @classmethod
    def MaxSmartPoints(cls) -> int: ...
    @property
    @classmethod
    def PointColor(cls) -> Color: ...
    @property
    @classmethod
    def SmartOrtho(cls) -> bool: ...
    @property
    @classmethod
    def SmartTangents(cls) -> bool: ...
    @property
    @classmethod
    def TanPerpLineColor(cls) -> Color: ...
    @property
    @classmethod
    def UseDottedLines(cls) -> bool: ...
    @property
    @classmethod
    def UseSmartTrack(cls) -> bool: ...
    @overload
    @staticmethod
    def GetCurrentState() -> SmartTrackSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> SmartTrackSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @ActivationDelayMilliseconds.setter
    @classmethod
    def ActivationDelayMilliseconds(clsvalue: int) -> None: ...
    @ActivePointColor.setter
    @classmethod
    def ActivePointColor(clsvalue: Color) -> None: ...
    @GuideColor.setter
    @classmethod
    def GuideColor(clsvalue: Color) -> None: ...
    @LineColor.setter
    @classmethod
    def LineColor(clsvalue: Color) -> None: ...
    @MaxSmartPoints.setter
    @classmethod
    def MaxSmartPoints(clsvalue: int) -> None: ...
    @PointColor.setter
    @classmethod
    def PointColor(clsvalue: Color) -> None: ...
    @SmartOrtho.setter
    @classmethod
    def SmartOrtho(clsvalue: bool) -> None: ...
    @SmartTangents.setter
    @classmethod
    def SmartTangents(clsvalue: bool) -> None: ...
    @TanPerpLineColor.setter
    @classmethod
    def TanPerpLineColor(clsvalue: Color) -> None: ...
    @UseDottedLines.setter
    @classmethod
    def UseDottedLines(clsvalue: bool) -> None: ...
    @UseSmartTrack.setter
    @classmethod
    def UseSmartTrack(clsvalue: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: SmartTrackSettingsState) -> None: ...


class SmartTrackSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ActivationDelayMilliseconds(self) -> int: ...
    @property
    def ActivePointColor(self) -> Color: ...
    @property
    def GuideColor(self) -> Color: ...
    @property
    def LineColor(self) -> Color: ...
    @property
    @classmethod
    def MaxSmartPoints(cls) -> int: ...
    @property
    def PointColor(self) -> Color: ...
    @property
    def SmartOrtho(self) -> bool: ...
    @property
    def SmartTangents(self) -> bool: ...
    @property
    def TanPerpLineColor(self) -> Color: ...
    @property
    def UseDottedLines(self) -> bool: ...
    @property
    def UseSmartTrack(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @ActivationDelayMilliseconds.setter
    def ActivationDelayMilliseconds(self, value: int) -> None: ...
    @ActivePointColor.setter
    def ActivePointColor(self, value: Color) -> None: ...
    @GuideColor.setter
    def GuideColor(self, value: Color) -> None: ...
    @LineColor.setter
    def LineColor(self, value: Color) -> None: ...
    @MaxSmartPoints.setter
    @classmethod
    def MaxSmartPoints(clsvalue: int) -> None: ...
    @PointColor.setter
    def PointColor(self, value: Color) -> None: ...
    @SmartOrtho.setter
    def SmartOrtho(self, value: bool) -> None: ...
    @SmartTangents.setter
    def SmartTangents(self, value: bool) -> None: ...
    @TanPerpLineColor.setter
    def TanPerpLineColor(self, value: Color) -> None: ...
    @UseDottedLines.setter
    def UseDottedLines(self, value: bool) -> None: ...
    @UseSmartTrack.setter
    def UseSmartTrack(self, value: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...


class ViewRotationStyle(Enum):
    RotateAroundWorldAxes = 0
    RotateRelativeToView = 1
    RotateRelativeToViewV2Style = 2
    RotateAroundCplaneZaxis = 3


class ViewSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def AlwaysPanParallelViews(cls) -> bool: ...
    @property
    @classmethod
    def AutoAdjustTargetDepth(cls) -> bool: ...
    @property
    @classmethod
    def DefinedViewSetClippingPlanes(cls) -> bool: ...
    @property
    @classmethod
    def DefinedViewSetCPlane(cls) -> bool: ...
    @property
    @classmethod
    def DefinedViewSetDisplayMode(cls) -> bool: ...
    @property
    @classmethod
    def DefinedViewSetProjection(cls) -> bool: ...
    @property
    @classmethod
    def LinkedViewports(cls) -> bool: ...
    @property
    @classmethod
    def PanPlanParallelViewsWithControlShiftRMB(cls) -> bool: ...
    @property
    @classmethod
    def PanReverseKeyboardAction(cls) -> bool: ...
    @property
    @classmethod
    def PanScreenFraction(cls) -> float: ...
    @property
    @classmethod
    def RotateCircleIncrement(cls) -> int: ...
    @property
    @classmethod
    def RotateReverseKeyboard(cls) -> bool: ...
    @property
    @classmethod
    def RotateToView(cls) -> bool: ...
    @property
    @classmethod
    def RotateViewAroundAutogumball(cls) -> bool: ...
    @property
    @classmethod
    def RotateViewAroundObjectAtMouseCursor(cls) -> bool: ...
    @property
    @classmethod
    def SingleClickMaximize(cls) -> bool: ...
    @property
    @classmethod
    def ThreePointPerspectiveLensLength(cls) -> float: ...
    @property
    @classmethod
    def TwoPointPerspectiveLensLength(cls) -> float: ...
    @property
    @classmethod
    def ViewRotation(cls) -> ViewRotationStyle: ...
    @property
    @classmethod
    def ZoomExtentsParallelViewBorder(cls) -> float: ...
    @property
    @classmethod
    def ZoomExtentsPerspectiveViewBorder(cls) -> float: ...
    @property
    @classmethod
    def ZoomScale(cls) -> float: ...
    @overload
    @staticmethod
    def GetCurrentState() -> ViewSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> ViewSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @AlwaysPanParallelViews.setter
    @classmethod
    def AlwaysPanParallelViews(clsvalue: bool) -> None: ...
    @AutoAdjustTargetDepth.setter
    @classmethod
    def AutoAdjustTargetDepth(clsvalue: bool) -> None: ...
    @DefinedViewSetClippingPlanes.setter
    @classmethod
    def DefinedViewSetClippingPlanes(clsvalue: bool) -> None: ...
    @DefinedViewSetCPlane.setter
    @classmethod
    def DefinedViewSetCPlane(clsvalue: bool) -> None: ...
    @DefinedViewSetDisplayMode.setter
    @classmethod
    def DefinedViewSetDisplayMode(clsvalue: bool) -> None: ...
    @DefinedViewSetProjection.setter
    @classmethod
    def DefinedViewSetProjection(clsvalue: bool) -> None: ...
    @LinkedViewports.setter
    @classmethod
    def LinkedViewports(clsvalue: bool) -> None: ...
    @PanPlanParallelViewsWithControlShiftRMB.setter
    @classmethod
    def PanPlanParallelViewsWithControlShiftRMB(clsvalue: bool) -> None: ...
    @PanReverseKeyboardAction.setter
    @classmethod
    def PanReverseKeyboardAction(clsvalue: bool) -> None: ...
    @PanScreenFraction.setter
    @classmethod
    def PanScreenFraction(clsvalue: float) -> None: ...
    @RotateCircleIncrement.setter
    @classmethod
    def RotateCircleIncrement(clsvalue: int) -> None: ...
    @RotateReverseKeyboard.setter
    @classmethod
    def RotateReverseKeyboard(clsvalue: bool) -> None: ...
    @RotateToView.setter
    @classmethod
    def RotateToView(clsvalue: bool) -> None: ...
    @RotateViewAroundAutogumball.setter
    @classmethod
    def RotateViewAroundAutogumball(clsvalue: bool) -> None: ...
    @RotateViewAroundObjectAtMouseCursor.setter
    @classmethod
    def RotateViewAroundObjectAtMouseCursor(clsvalue: bool) -> None: ...
    @SingleClickMaximize.setter
    @classmethod
    def SingleClickMaximize(clsvalue: bool) -> None: ...
    @ViewRotation.setter
    @classmethod
    def ViewRotation(clsvalue: ViewRotationStyle) -> None: ...
    @ZoomExtentsParallelViewBorder.setter
    @classmethod
    def ZoomExtentsParallelViewBorder(clsvalue: float) -> None: ...
    @ZoomExtentsPerspectiveViewBorder.setter
    @classmethod
    def ZoomExtentsPerspectiveViewBorder(clsvalue: float) -> None: ...
    @ZoomScale.setter
    @classmethod
    def ZoomScale(clsvalue: float) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: ViewSettingsState) -> None: ...


class ViewSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AlwaysPanParallelViews(self) -> bool: ...
    @property
    def DefinedViewSetCPlane(self) -> bool: ...
    @property
    def DefinedViewSetProjection(self) -> bool: ...
    @property
    def LinkedViewports(self) -> bool: ...
    @property
    def PanReverseKeyboardAction(self) -> bool: ...
    @property
    def PanScreenFraction(self) -> float: ...
    @property
    def RotateCircleIncrement(self) -> int: ...
    @property
    def RotateReverseKeyboard(self) -> bool: ...
    @property
    def RotateToView(self) -> bool: ...
    @property
    def SingleClickMaximize(self) -> bool: ...
    @property
    def ThreePointPerspectiveLensLength(self) -> float: ...
    @property
    def TwoPointPerspectiveLensLength(self) -> float: ...
    @property
    def ViewRotation(self) -> ViewRotationStyle: ...
    @property
    def ZoomExtentsParallelViewBorder(self) -> float: ...
    @property
    def ZoomExtentsPerspectiveViewBorder(self) -> float: ...
    @property
    def ZoomScale(self) -> float: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @AlwaysPanParallelViews.setter
    def AlwaysPanParallelViews(self, value: bool) -> None: ...
    @DefinedViewSetCPlane.setter
    def DefinedViewSetCPlane(self, value: bool) -> None: ...
    @DefinedViewSetProjection.setter
    def DefinedViewSetProjection(self, value: bool) -> None: ...
    @LinkedViewports.setter
    def LinkedViewports(self, value: bool) -> None: ...
    @PanReverseKeyboardAction.setter
    def PanReverseKeyboardAction(self, value: bool) -> None: ...
    @PanScreenFraction.setter
    def PanScreenFraction(self, value: float) -> None: ...
    @RotateCircleIncrement.setter
    def RotateCircleIncrement(self, value: int) -> None: ...
    @RotateReverseKeyboard.setter
    def RotateReverseKeyboard(self, value: bool) -> None: ...
    @RotateToView.setter
    def RotateToView(self, value: bool) -> None: ...
    @SingleClickMaximize.setter
    def SingleClickMaximize(self, value: bool) -> None: ...
    @ViewRotation.setter
    def ViewRotation(self, value: ViewRotationStyle) -> None: ...
    @ZoomExtentsParallelViewBorder.setter
    def ZoomExtentsParallelViewBorder(self, value: float) -> None: ...
    @ZoomExtentsPerspectiveViewBorder.setter
    def ZoomExtentsPerspectiveViewBorder(self, value: float) -> None: ...
    @ZoomScale.setter
    def ZoomScale(self, value: float) -> None: ...
    @overload
    def ToString(self) -> str: ...


class WidgetColor(Enum):
    UAxisColor = 0
    VAxisColor = 1
    WAxisColor = 2


class ZebraAnalysisSettings:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def ShowIsoCurves(cls) -> bool: ...
    @property
    @classmethod
    def StripeColor(cls) -> Color: ...
    @property
    @classmethod
    def StripeThickness(cls) -> int: ...
    @property
    @classmethod
    def VerticalStripes(cls) -> bool: ...
    @overload
    @staticmethod
    def GetCurrentState() -> ZebraAnalysisSettingsState: ...
    @overload
    @staticmethod
    def GetDefaultState() -> ZebraAnalysisSettingsState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RestoreDefaults() -> None: ...
    @ShowIsoCurves.setter
    @classmethod
    def ShowIsoCurves(clsvalue: bool) -> None: ...
    @StripeColor.setter
    @classmethod
    def StripeColor(clsvalue: Color) -> None: ...
    @StripeThickness.setter
    @classmethod
    def StripeThickness(clsvalue: int) -> None: ...
    @VerticalStripes.setter
    @classmethod
    def VerticalStripes(clsvalue: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UpdateFromState(state: ZebraAnalysisSettingsState) -> None: ...


class ZebraAnalysisSettingsState:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ShowIsoCurves(self) -> bool: ...
    @property
    def StripeColor(self) -> Color: ...
    @property
    def StripeThickness(self) -> int: ...
    @property
    def VerticalStripes(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @ShowIsoCurves.setter
    def ShowIsoCurves(self, value: bool) -> None: ...
    @StripeColor.setter
    def StripeColor(self, value: Color) -> None: ...
    @StripeThickness.setter
    def StripeThickness(self, value: int) -> None: ...
    @VerticalStripes.setter
    def VerticalStripes(self, value: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
