from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class GumballAppearanceSettings:
    @overload
    def __init__(self): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def ArcThickness(self) -> int: ...
    @overload
    @property
    def ArrowHeadLength(self) -> int: ...
    @overload
    @property
    def ArrowHeadWidth(self) -> int: ...
    @overload
    @property
    def AxisThickness(self) -> int: ...
    @overload
    @property
    def ColorMenuButton(self) -> Color: ...
    @overload
    @property
    def ColorX(self) -> Color: ...
    @overload
    @property
    def ColorY(self) -> Color: ...
    @overload
    @property
    def ColorZ(self) -> Color: ...
    @overload
    @property
    def FreeTranslate(self) -> int: ...
    @overload
    @property
    def MenuDistance(self) -> int: ...
    @overload
    @property
    def MenuEnabled(self) -> bool: ...
    @overload
    @property
    def MenuSize(self) -> int: ...
    @overload
    @property
    def PlanarTranslationGripCorner(self) -> int: ...
    @overload
    @property
    def PlanarTranslationGripSize(self) -> int: ...
    @overload
    @property
    def Radius(self) -> int: ...
    @overload
    @property
    def RelocateEnabled(self) -> bool: ...
    @overload
    @property
    def RotateXEnabled(self) -> bool: ...
    @overload
    @property
    def RotateYEnabled(self) -> bool: ...
    @overload
    @property
    def RotateZEnabled(self) -> bool: ...
    @overload
    @property
    def ScaleGripSize(self) -> int: ...
    @overload
    @property
    def ScaleXEnabled(self) -> bool: ...
    @overload
    @property
    def ScaleYEnabled(self) -> bool: ...
    @overload
    @property
    def ScaleZEnabled(self) -> bool: ...
    @overload
    @property
    def TranslateXEnabled(self) -> bool: ...
    @overload
    @property
    def TranslateXYEnabled(self) -> bool: ...
    @overload
    @property
    def TranslateYEnabled(self) -> bool: ...
    @overload
    @property
    def TranslateYZEnabled(self) -> bool: ...
    @overload
    @property
    def TranslateZEnabled(self) -> bool: ...
    @overload
    @property
    def TranslateZXEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @ArcThickness.setter
    def ArcThickness(self, value: int) -> None: ...
    @overload
    @ArrowHeadLength.setter
    def ArrowHeadLength(self, value: int) -> None: ...
    @overload
    @ArrowHeadWidth.setter
    def ArrowHeadWidth(self, value: int) -> None: ...
    @overload
    @AxisThickness.setter
    def AxisThickness(self, value: int) -> None: ...
    @overload
    @ColorMenuButton.setter
    def ColorMenuButton(self, value: Color) -> None: ...
    @overload
    @ColorX.setter
    def ColorX(self, value: Color) -> None: ...
    @overload
    @ColorY.setter
    def ColorY(self, value: Color) -> None: ...
    @overload
    @ColorZ.setter
    def ColorZ(self, value: Color) -> None: ...
    @overload
    @FreeTranslate.setter
    def FreeTranslate(self, value: int) -> None: ...
    @overload
    @MenuDistance.setter
    def MenuDistance(self, value: int) -> None: ...
    @overload
    @MenuEnabled.setter
    def MenuEnabled(self, value: bool) -> None: ...
    @overload
    @MenuSize.setter
    def MenuSize(self, value: int) -> None: ...
    @overload
    @PlanarTranslationGripCorner.setter
    def PlanarTranslationGripCorner(self, value: int) -> None: ...
    @overload
    @PlanarTranslationGripSize.setter
    def PlanarTranslationGripSize(self, value: int) -> None: ...
    @overload
    @Radius.setter
    def Radius(self, value: int) -> None: ...
    @overload
    @RelocateEnabled.setter
    def RelocateEnabled(self, value: bool) -> None: ...
    @overload
    @RotateXEnabled.setter
    def RotateXEnabled(self, value: bool) -> None: ...
    @overload
    @RotateYEnabled.setter
    def RotateYEnabled(self, value: bool) -> None: ...
    @overload
    @RotateZEnabled.setter
    def RotateZEnabled(self, value: bool) -> None: ...
    @overload
    @ScaleGripSize.setter
    def ScaleGripSize(self, value: int) -> None: ...
    @overload
    @ScaleXEnabled.setter
    def ScaleXEnabled(self, value: bool) -> None: ...
    @overload
    @ScaleYEnabled.setter
    def ScaleYEnabled(self, value: bool) -> None: ...
    @overload
    @ScaleZEnabled.setter
    def ScaleZEnabled(self, value: bool) -> None: ...
    @overload
    @TranslateXEnabled.setter
    def TranslateXEnabled(self, value: bool) -> None: ...
    @overload
    @TranslateXYEnabled.setter
    def TranslateXYEnabled(self, value: bool) -> None: ...
    @overload
    @TranslateYEnabled.setter
    def TranslateYEnabled(self, value: bool) -> None: ...
    @overload
    @TranslateYZEnabled.setter
    def TranslateYZEnabled(self, value: bool) -> None: ...
    @overload
    @TranslateZEnabled.setter
    def TranslateZEnabled(self, value: bool) -> None: ...
    @overload
    @TranslateZXEnabled.setter
    def TranslateZXEnabled(self, value: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ...DocObjects import ActiveSpace
from ...Geometry import Transform
from ...Geometry import Point3d
from ...Geometry import Line
from ...Geometry import Plane
from ...Input.Custom import PickContext
from ...Input.Custom import GetPoint
class GumballDisplayConduit:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, space: ActiveSpace): ...
    @overload
    def CheckShiftAndControlKeys(self) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def BaseGumball(self) -> GumballObject: ...
    @overload
    @property
    def Enabled(self) -> bool: ...
    @overload
    @property
    def Gumball(self) -> GumballObject: ...
    @overload
    @property
    def GumballTransform(self) -> Transform: ...
    @overload
    @property
    def InRelocate(self) -> bool: ...
    @overload
    @property
    def PickResult(self) -> GumballPickResult: ...
    @overload
    @property
    def PreTransform(self) -> Transform: ...
    @overload
    @property
    def TotalTransform(self) -> Transform: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def PickGumball(self, pickContext: PickContext, getPoint: GetPoint) -> bool: ...
    @overload
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...
    @overload
    @PreTransform.setter
    def PreTransform(self, value: Transform) -> None: ...
    @overload
    def SetBaseGumball(self, gumball: GumballObject) -> None: ...
    @overload
    def SetBaseGumball(self, gumball: GumballObject, appearanceSettings: GumballAppearanceSettings) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def UpdateGumball(self, frame: Plane) -> bool: ...
    @overload
    def UpdateGumball(self, point: Point3d, worldLine: Line) -> bool: ...


from ...Geometry import Plane
from ...Geometry import Vector3d
class GumballFrame:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Plane(self) -> Plane: ...
    @overload
    @property
    def ScaleGripDistance(self) -> Vector3d: ...
    @overload
    @property
    def ScaleMode(self) -> GumballScaleMode: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...
    @overload
    @ScaleGripDistance.setter
    def ScaleGripDistance(self, value: Vector3d) -> None: ...
    @overload
    @ScaleMode.setter
    def ScaleMode(self, value: GumballScaleMode) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GumballMode(Enum):
    # None = 0
    Menu = 1
    TranslateFree = 2
    TranslateX = 3
    TranslateY = 4
    TranslateZ = 5
    TranslateXY = 6
    TranslateYZ = 7
    TranslateZX = 8
    ScaleX = 9
    ScaleY = 10
    ScaleZ = 11
    ScaleXY = 12
    ScaleYZ = 13
    ScaleZX = 14
    RotateX = 15
    RotateY = 16
    RotateZ = 17
    ExtrudeX = 18
    ExtrudeY = 19
    ExtrudeZ = 20
    CutX = 21
    CutY = 22
    CutZ = 23


from ...Geometry import BoundingBox
from ...Geometry import Plane
from ...Geometry import Line
from ...Geometry import Arc
from ...Geometry import Circle
from ...Geometry import Ellipse
from ...Geometry import Light
from ...Geometry import Hatch
from ...Geometry import Curve
from ...Geometry import Extrusion
class GumballObject:
    @overload
    def __init__(self): ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Frame(self) -> GumballFrame: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @Frame.setter
    def Frame(self, value: GumballFrame) -> None: ...
    @overload
    def SetFromArc(self, arc: Arc) -> bool: ...
    @overload
    def SetFromBoundingBox(self, boundingBox: BoundingBox) -> bool: ...
    @overload
    def SetFromBoundingBox(self, frame: Plane, frameBoundingBox: BoundingBox) -> bool: ...
    @overload
    def SetFromCircle(self, circle: Circle) -> bool: ...
    @overload
    def SetFromCurve(self, curve: Curve) -> bool: ...
    @overload
    def SetFromEllipse(self, ellipse: Ellipse) -> bool: ...
    @overload
    def SetFromExtrusion(self, extrusion: Extrusion) -> bool: ...
    @overload
    def SetFromHatch(self, hatch: Hatch) -> bool: ...
    @overload
    def SetFromLight(self, light: Light) -> bool: ...
    @overload
    def SetFromLine(self, line: Line) -> bool: ...
    @overload
    def SetFromPlane(self, plane: Plane) -> bool: ...
    @overload
    def ToString(self) -> str: ...


class GumballPickResult:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Mode(self) -> GumballMode: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def SetToDefault(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GumballScaleMode(Enum):
    Independent = 0
    XY = 1
    YZ = 2
    ZX = 3
    XYZ = 4
