from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



from ...Geometry import Point2d
class WorldMapDayNight:
    @overload
    def __init__(self): ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def HasMapForCurrentSettings(self) -> bool: ...
    @overload
    def LocationToMap(self, latlong: Point2d) -> Point: ...
    @overload
    def MakeMapBitmap(self) -> None: ...
    @overload
    def Map(self) -> Image: ...
    @overload
    def MapToLocation(self, mapPoint: Point) -> Point2d: ...
    @overload
    def SetDayNightDisplay(self, bOn: bool) -> None: ...
    @overload
    def SetEnabled(self, bEnabled: bool) -> None: ...
    @overload
    def SetTimeInfo(self, dt: DateTime, timezone: float, daylightSavingMinutes: int, bDaylightSavingsOn: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
