# To create the Python virtual environment, run `uv sync`.
# Use Pyright for type checking.
# `uv` can be installed from the link below:
# https://docs.astral.sh/uv/getting-started/installation/

[tool.uv.workspace]
members = [
    "stubs/Eto",
    "stubs/GH_IO",
    "stubs/GH_Util",
    "stubs/Grasshopper",
    "stubs/Rhino",
]

[dependency-groups]
dev = ["pyright>=1.1.402"]

[tool.pyright]
typeCheckingMode = "basic"
reportInconsistentOverload = false
reportSelfClsParameterName = false
reportRedeclaration = false
extraPaths = [
    "stubs/Eto",
    "stubs/GH_IO",
    "stubs/GH_Util",
    "stubs/Grasshopper",
    "stubs/Rhino",
]

[tool.ruff]
select = []

[tool.pylint]
disable = "all"
