# To create the Python virtual environment, run `uv sync`.
# Use Pyright for type checking.
# `uv` can be installed from the link below:
# https://docs.astral.sh/uv/getting-started/installation/

[tool.uv.workspace]
members = [
    "stubs/Eto",
    "stubs/GH_IO",
    "stubs/GH_Util",
    "stubs/Grasshopper",
    "stubs/Rhino",
]

[tool.uv.sources]
"eto-stubs-typed" = { workspace = true }
"gh-io-stubs-typed" = { workspace = true }
"gh-util-stubs-typed" = { workspace = true }
"grasshopper-stubs-typed" = { workspace = true }
"rhino-stubs-typed" = { workspace = true }

[tool.ruff.lint]
extend-select = ["N", "I", "RUF", "SLF", "INP"]
exclude = ["stubs/"]

[tool.pyright]
typeCheckingMode = "basic"
reportInconsistentOverload = false
reportSelfClsParameterName = false
reportRedeclaration = false
extraPaths = [
    "stubs/Eto",
    "stubs/GH_IO",
    "stubs/GH_Util",
    "stubs/Grasshopper",
    "stubs/Rhino",
]
