from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class Res_CanvasToolbar:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Add_Group_24x24() -> Bitmap: ...
    @overload
    @property
    def Add_Label_24x24() -> Bitmap: ...
    @overload
    @property
    def Add_Separator_24x24() -> Bitmap: ...
    @overload
    @property
    def AddDataItem_24x24() -> Bitmap: ...
    @overload
    @property
    def AddPathItem_24x24() -> Bitmap: ...
    @overload
    @property
    def AutoUpdate_24x24() -> Bitmap: ...
    @overload
    @property
    def BeforeAfterSolveInstance_24x24() -> Bitmap: ...
    @overload
    @property
    def BlackYellowBands_16x16() -> Bitmap: ...
    @overload
    @property
    def BracketClose_24x10() -> Bitmap: ...
    @overload
    @property
    def BracketOpen_24x10() -> Bitmap: ...
    @overload
    @property
    def Culture() -> CultureInfo: ...
    @overload
    @property
    def DeleteDataItem_24x24() -> Bitmap: ...
    @overload
    @property
    def Edit_Mode_24x24() -> Bitmap: ...
    @overload
    @property
    def EditDataAsText_24x24() -> Bitmap: ...
    @overload
    @property
    def Focus_LowerLeft_20x20() -> Bitmap: ...
    @overload
    @property
    def Focus_LowerRight_20x20() -> Bitmap: ...
    @overload
    @property
    def Focus_UpperLeft_20x20() -> Bitmap: ...
    @overload
    @property
    def Focus_UpperRight_20x20() -> Bitmap: ...
    @overload
    @property
    def NamedView_24x24() -> Bitmap: ...
    @overload
    @property
    def OpenFile_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_Boundary_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_BumpZBuffer_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_Gumballs_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_MeshEdges_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_Off_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_PreviewMeshCoarse_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_PreviewMeshCustom_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_PreviewMeshDocument_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_PreviewMeshNone_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_PreviewMeshSmooth_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_Selected_Filter_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_Settings_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_Shaded_24x24() -> Bitmap: ...
    @overload
    @property
    def Preview_Wireframe_24x24() -> Bitmap: ...
    @overload
    @property
    def ResourceManager() -> ResourceManager: ...
    @overload
    @property
    def SaveFile_24x24() -> Bitmap: ...
    @overload
    @property
    def ShrinkWindow_24x24() -> Bitmap: ...
    @overload
    @property
    def Sketch_24x24() -> Bitmap: ...
    @overload
    @property
    def Target_24x24() -> Bitmap: ...
    @overload
    @property
    def TargetInactive_24x24() -> Bitmap: ...
    @overload
    @property
    def ZoomAllObjects_20x20() -> Bitmap: ...
    @overload
    @property
    def ZoomSelectedObjects_20x20() -> Bitmap: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @Culture.setter
    def Culture(Value: CultureInfo) -> None: ...
    @overload
    def ToString(self) -> str: ...


class Res_ContextMenu:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Access_Item_16x16() -> Bitmap: ...
    @overload
    @property
    def Access_List_16x16() -> Bitmap: ...
    @overload
    @property
    def Access_Tree_16x16() -> Bitmap: ...
    @overload
    @property
    def Align_Bottom_11x11() -> Bitmap: ...
    @overload
    @property
    def Align_Horizontal_11x11() -> Bitmap: ...
    @overload
    @property
    def Align_Left_11x11() -> Bitmap: ...
    @overload
    @property
    def Align_Right_11x11() -> Bitmap: ...
    @overload
    @property
    def Align_Top_11x11() -> Bitmap: ...
    @overload
    @property
    def Align_Vertical_11x11() -> Bitmap: ...
    @overload
    @property
    def ClusterInfo_16x16() -> Bitmap: ...
    @overload
    @property
    def ColourWheelBichromatic() -> Bitmap: ...
    @overload
    @property
    def ColourWheelComplementary() -> Bitmap: ...
    @overload
    @property
    def ColourWheelMonochromatic() -> Bitmap: ...
    @overload
    @property
    def ColourWheelTetrachromatic() -> Bitmap: ...
    @overload
    @property
    def ColourWheelTetrad() -> Bitmap: ...
    @overload
    @property
    def ColourWheelTriad() -> Bitmap: ...
    @overload
    @property
    def ColourWheelTrichromatic() -> Bitmap: ...
    @overload
    @property
    def Component_Display_Default() -> Bitmap: ...
    @overload
    @property
    def Component_Display_Icon() -> Bitmap: ...
    @overload
    @property
    def Component_Display_Name() -> Bitmap: ...
    @overload
    @property
    def Culture() -> CultureInfo: ...
    @overload
    @property
    def Distribute_Horizontal_11x11() -> Bitmap: ...
    @overload
    @property
    def Distribute_Vertical_11x11() -> Bitmap: ...
    @overload
    @property
    def Edit_PanelText_16x16() -> Bitmap: ...
    @overload
    @property
    def ErrorSymbol_20x20() -> Bitmap: ...
    @overload
    @property
    def Font_Comic_16x16() -> Bitmap: ...
    @overload
    @property
    def Font_Courier_16x16() -> Bitmap: ...
    @overload
    @property
    def Font_SansSerif_16x16() -> Bitmap: ...
    @overload
    @property
    def Font_TimesNewRoman_16x16() -> Bitmap: ...
    @overload
    @property
    def Font_Trebuchet_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Bezier_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Blank_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Conic_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_DoubleSine_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Gaussian_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Linear_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Parabola_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Perlin_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Power_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Sinc_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_Sine_16x16() -> Bitmap: ...
    @overload
    @property
    def Graph_SquareRoot_16x16() -> Bitmap: ...
    @overload
    @property
    def Group_Boxes_Outline_16x16() -> Bitmap: ...
    @overload
    @property
    def Group_MetaBall_Outline_16x16() -> Bitmap: ...
    @overload
    @property
    def Group_Rectangle_Outline_16x16() -> Bitmap: ...
    @overload
    @property
    def GroupTag_16x16() -> Bitmap: ...
    @overload
    @property
    def Help_16x16() -> Bitmap: ...
    @overload
    @property
    def LegendDiscreteHorizontal_16x16() -> Bitmap: ...
    @overload
    @property
    def LegendDiscreteVertical_16x16() -> Bitmap: ...
    @overload
    @property
    def LegendSmoothHorizontal_16x16() -> Bitmap: ...
    @overload
    @property
    def LegendSmoothVertical_16x16() -> Bitmap: ...
    @overload
    @property
    def Markov_BottomLeft_16x16() -> Bitmap: ...
    @overload
    @property
    def Markov_BottomRight_16x16() -> Bitmap: ...
    @overload
    @property
    def Markov_TopLeft_16x16() -> Bitmap: ...
    @overload
    @property
    def Markov_TopRight_16x16() -> Bitmap: ...
    @overload
    @property
    def Match_CrossReference_16x16() -> Bitmap: ...
    @overload
    @property
    def Match_LongestList_16x16() -> Bitmap: ...
    @overload
    @property
    def Match_ShortestList_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Contains_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Degrees_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_EndsWith_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Equals_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Expression_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Flatten_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Graft_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Invert_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Normalise_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_NotEquals_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Principal_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Regex_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Reverse_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Simplify_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_StartsWith_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Synchronize_16x16() -> Bitmap: ...
    @overload
    @property
    def Modifier_Wildcards_16x16() -> Bitmap: ...
    @overload
    @property
    def Panel_AlignCenter_16x16() -> Bitmap: ...
    @overload
    @property
    def Panel_AlignLeft_16x16() -> Bitmap: ...
    @overload
    @property
    def Panel_AlignRight_16x16() -> Bitmap: ...
    @overload
    @property
    def Panel_DrawIndices_16x16() -> Bitmap: ...
    @overload
    @property
    def Panel_DrawPaths_16x16() -> Bitmap: ...
    @overload
    @property
    def Panel_MultilineData_16x16() -> Bitmap: ...
    @overload
    @property
    def Panel_StreamContents_16x16() -> Bitmap: ...
    @overload
    @property
    def Panel_StreamDestination_16x16() -> Bitmap: ...
    @overload
    @property
    def ParamViewer_DrawTree_16X16() -> Bitmap: ...
    @overload
    @property
    def RemarkSymbol_20x20() -> Bitmap: ...
    @overload
    @property
    def ResourceManager() -> ResourceManager: ...
    @overload
    @property
    def Sample_Channel_Alpha_16x16() -> Bitmap: ...
    @overload
    @property
    def Sample_Channel_Blue_16x16() -> Bitmap: ...
    @overload
    @property
    def Sample_Channel_Colour_16x16() -> Bitmap: ...
    @overload
    @property
    def Sample_Channel_Green_16x16() -> Bitmap: ...
    @overload
    @property
    def Sample_Channel_Hue_16x16() -> Bitmap: ...
    @overload
    @property
    def Sample_Channel_Luminance_16x16() -> Bitmap: ...
    @overload
    @property
    def Sample_Channel_Red_16x16() -> Bitmap: ...
    @overload
    @property
    def Sample_Channel_Saturation_16x16() -> Bitmap: ...
    @overload
    @property
    def Sampling_Clamp_16x16() -> Bitmap: ...
    @overload
    @property
    def Sampling_Flip_16x16() -> Bitmap: ...
    @overload
    @property
    def Sampling_Tile_16x16() -> Bitmap: ...
    @overload
    @property
    def ValueList_Cyclical_16x16() -> Bitmap: ...
    @overload
    @property
    def Variable_Params_Input_16x16() -> Bitmap: ...
    @overload
    @property
    def Variable_Params_Output_16x16() -> Bitmap: ...
    @overload
    @property
    def WarningSymbol_20x20() -> Bitmap: ...
    @overload
    @property
    def WireDisplay_Default() -> Bitmap: ...
    @overload
    @property
    def WireDisplay_Faint() -> Bitmap: ...
    @overload
    @property
    def WireDisplay_Hidden() -> Bitmap: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @Culture.setter
    def Culture(Value: CultureInfo) -> None: ...
    @overload
    def ToString(self) -> str: ...


class Res_GUI:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Alpha_Background_20x20() -> Bitmap: ...
    @overload
    @property
    def AutosaveWarning() -> Bitmap: ...
    @overload
    @property
    def Bitmap_Dimensions_24x24() -> Bitmap: ...
    @overload
    @property
    def BloodDrip_48x24() -> Bitmap: ...
    @overload
    @property
    def BoldFont_20x20() -> Bitmap: ...
    @overload
    @property
    def Close_Toolbar_20x20() -> Bitmap: ...
    @overload
    @property
    def Close_Toolbar_Active_20x20() -> Bitmap: ...
    @overload
    @property
    def ClusterInstances_20x20() -> Bitmap: ...
    @overload
    @property
    def Collapse_7x7() -> Bitmap: ...
    @overload
    @property
    def Collapsed_11x11() -> Bitmap: ...
    @overload
    @property
    def Colour_Mode_HSV_20x20() -> Bitmap: ...
    @overload
    @property
    def Colour_Mode_RGB_20x20() -> Bitmap: ...
    @overload
    @property
    def Colour_Mode_SRC_20x20() -> Bitmap: ...
    @overload
    @property
    def ColourWheel() -> Bitmap: ...
    @overload
    @property
    def CroppingFrame_24x24() -> Bitmap: ...
    @overload
    @property
    def Culture() -> CultureInfo: ...
    @overload
    @property
    def DataRecorder_ClearActive() -> Bitmap: ...
    @overload
    @property
    def DataRecorder_ClearInactive() -> Bitmap: ...
    @overload
    @property
    def DataRecorder_RecordActive() -> Bitmap: ...
    @overload
    @property
    def DataRecorder_RecordInactive() -> Bitmap: ...
    @overload
    @property
    def DigitScrollTextInput_16x16() -> Bitmap: ...
    @overload
    @property
    def DigitScrollTextInputInactive_16x16() -> Bitmap: ...
    @overload
    @property
    def DisplayVersion_24x24() -> Bitmap: ...
    @overload
    @property
    def Doc_Aborted_48x48() -> Bitmap: ...
    @overload
    @property
    def DragWindow_20x20() -> Bitmap: ...
    @overload
    @property
    def DropDown_11x11() -> Bitmap: ...
    @overload
    @property
    def Expand_7x7() -> Bitmap: ...
    @overload
    @property
    def Expanded_11x11() -> Bitmap: ...
    @overload
    @property
    def Filter_Brep_20x20() -> Bitmap: ...
    @overload
    @property
    def Filter_BrepInactive_20x20() -> Bitmap: ...
    @overload
    @property
    def Filter_Curve_20x20() -> Bitmap: ...
    @overload
    @property
    def Filter_CurveInactive_20x20() -> Bitmap: ...
    @overload
    @property
    def Filter_Mesh_20x20() -> Bitmap: ...
    @overload
    @property
    def Filter_MeshInactive_20x20() -> Bitmap: ...
    @overload
    @property
    def Filter_Point_20x20() -> Bitmap: ...
    @overload
    @property
    def Filter_PointInactive_20x20() -> Bitmap: ...
    @overload
    @property
    def FocusFrame_24x24() -> Bitmap: ...
    @overload
    @property
    def ForgetSettings_24x24() -> Bitmap: ...
    @overload
    @property
    def FormattingSettings_24x24() -> Bitmap: ...
    @overload
    @property
    def Generic_Library_24x24() -> Bitmap: ...
    @overload
    @property
    def Generic_OpenFile_24x24() -> Bitmap: ...
    @overload
    @property
    def Generic_Variations_24x24() -> Bitmap: ...
    @overload
    @property
    def GracehopperBug() -> Bitmap: ...
    @overload
    @property
    def Gradient_AddGrip_16x16() -> Bitmap: ...
    @overload
    @property
    def GrasshopperRemotePanel_16x16() -> Icon: ...
    @overload
    @property
    def Grip_16x16() -> Bitmap: ...
    @overload
    @property
    def Grip_7x16() -> Bitmap: ...
    @overload
    @property
    def IconMarker_72x72() -> Bitmap: ...
    @overload
    @property
    def ItalicFont_20x20() -> Bitmap: ...
    @overload
    @property
    def KurtGodelLightCone() -> Bitmap: ...
    @overload
    @property
    def LayoutDeleteActive_20x20() -> Bitmap: ...
    @overload
    @property
    def LayoutDeleteInactive_20x20() -> Bitmap: ...
    @overload
    @property
    def LayoutEditActive_20x20() -> Bitmap: ...
    @overload
    @property
    def LayoutEditInactive_20x20() -> Bitmap: ...
    @overload
    @property
    def LayoutInvisible_20x20() -> Bitmap: ...
    @overload
    @property
    def LayoutVisible_20x20() -> Bitmap: ...
    @overload
    @property
    def Locked_20x20() -> Bitmap: ...
    @overload
    @property
    def Locked_40x40() -> Bitmap: ...
    @overload
    @property
    def Mapping_Operator_14x15() -> Bitmap: ...
    @overload
    @property
    def Margin_Horizontal_24x24() -> Bitmap: ...
    @overload
    @property
    def Margin_Vertical_24x24() -> Bitmap: ...
    @overload
    @property
    def MenuShortCutConflict_16x16() -> Bitmap: ...
    @overload
    @property
    def ObjectMarker_96x96() -> Bitmap: ...
    @overload
    @property
    def Open_Toolbar_Active_20x20() -> Bitmap: ...
    @overload
    @property
    def OpenCluster_Empty_63x56() -> Bitmap: ...
    @overload
    @property
    def Panel_AlignCenter_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_AlignLeft_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_AlignRight_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_DecreaseFont_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_DrawIndices_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_DrawPaths_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_IncreaseFont_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_MultiLine_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_PickColour_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_PickFont_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_SpecialCodes_24x24() -> Bitmap: ...
    @overload
    @property
    def Panel_Wrap_24x24() -> Bitmap: ...
    @overload
    @property
    def Pause_Symbol_24x24() -> Bitmap: ...
    @overload
    @property
    def Play_Symbol_24x24() -> Bitmap: ...
    @overload
    @property
    def Prudery_High_24x24() -> Bitmap: ...
    @overload
    @property
    def Prudery_Highest_24x24() -> Bitmap: ...
    @overload
    @property
    def Prudery_Low_24x24() -> Bitmap: ...
    @overload
    @property
    def Prudery_Lowest_24x24() -> Bitmap: ...
    @overload
    @property
    def Prudery_Medium_24x24() -> Bitmap: ...
    @overload
    @property
    def ResourceManager() -> ResourceManager: ...
    @overload
    @property
    def RibbonLayout_20x20() -> Bitmap: ...
    @overload
    @property
    def RibbonLayoutExposure_24x24() -> Bitmap: ...
    @overload
    @property
    def RibbonLayoutInsert_20x20() -> Bitmap: ...
    @overload
    @property
    def RibbonLayoutItem_24x24() -> Bitmap: ...
    @overload
    @property
    def RibbonLayoutItems_24x24() -> Bitmap: ...
    @overload
    @property
    def RibbonLayoutPanel_24x24() -> Bitmap: ...
    @overload
    @property
    def RibbonLayoutTab_24x24() -> Bitmap: ...
    @overload
    @property
    def Scroll_12x12() -> Bitmap: ...
    @overload
    @property
    def ShrinkScriptEditor_24x24() -> Bitmap: ...
    @overload
    @property
    def Slider_Even_20x20() -> Bitmap: ...
    @overload
    @property
    def Slider_Float_20x20() -> Bitmap: ...
    @overload
    @property
    def Slider_Integer_20x20() -> Bitmap: ...
    @overload
    @property
    def Slider_Odd_20x20() -> Bitmap: ...
    @overload
    @property
    def StripePattern_48x48() -> Bitmap: ...
    @overload
    @property
    def TabMarker_96x96() -> Bitmap: ...
    @overload
    @property
    def TimersBlocked_16x16() -> Bitmap: ...
    @overload
    @property
    def TimersBlocked_24x24() -> Bitmap: ...
    @overload
    @property
    def TimersFree_16x16() -> Bitmap: ...
    @overload
    @property
    def trashcan_closed() -> Bitmap: ...
    @overload
    @property
    def trashcan_open() -> Bitmap: ...
    @overload
    @property
    def Unlocked_20x20() -> Bitmap: ...
    @overload
    @property
    def Viewport_Dimensions_20x20() -> Bitmap: ...
    @overload
    @property
    def ViewportFrame_24x24() -> Bitmap: ...
    @overload
    @property
    def VoronoiOverdoseWarning() -> Bitmap: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @Culture.setter
    def Culture(Value: CultureInfo) -> None: ...
    @overload
    def ToString(self) -> str: ...
