from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



from .. import GH_CanvasMouseEvent
from .. import GH_TooltipDisplayEventArgs
class GH_AbstractInteraction:
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from .. import GH_TooltipDisplayEventArgs
class GH_CycleInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, parentCanvas: GH_Canvas): ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from ....Kernel import IGH_Attributes
from .. import GH_TooltipDisplayEventArgs
class GH_DragInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, canvas: GH_Canvas, e: GH_CanvasMouseEvent): ...
    @overload
    def AddAttribute(self, attribute: IGH_Attributes) -> None: ...
    @overload
    def AddSnapAttributes(self, attribute: IGH_Attributes) -> None: ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def AttributeCount(self) -> int: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ....Kernel import IGH_ObjectProxy
from .. import GH_CanvasMouseEvent
from .. import GH_TooltipDisplayEventArgs
class GH_DumpInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, parent: GH_Canvas): ...
    @overload
    def __init__(self, parent: GH_Canvas, objectId: Guid): ...
    @overload
    def AppendProxy(self, proxy: IGH_ObjectProxy) -> None: ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def IsAggregating(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from .. import GH_TooltipDisplayEventArgs
class GH_PanInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, iParent: GH_Canvas, mEvent: GH_CanvasMouseEvent): ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from .. import GH_TooltipDisplayEventArgs
class GH_RadialMenuInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, canvas: GH_Canvas, e: GH_CanvasMouseEvent): ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, point: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from ....Kernel import IGH_Param
from .. import GH_TooltipDisplayEventArgs
class GH_RewireInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, iParent: GH_Canvas, mEvent: GH_CanvasMouseEvent, Source: IGH_Param): ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def IsValid(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from .. import GH_TooltipDisplayEventArgs
class GH_SketchInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, iParent: GH_Canvas): ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from ....Kernel import IGH_Attributes
from .. import GH_TooltipDisplayEventArgs
class GH_SplitInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, canvas: GH_Canvas, e: GH_CanvasMouseEvent): ...
    @overload
    def AddAttribute(self, Attribute: IGH_Attributes) -> None: ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from .. import GH_TooltipDisplayEventArgs
class GH_WindowSelectInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, canvas: GH_Canvas, mEvent: GH_CanvasMouseEvent): ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from ....Kernel import IGH_Param
from .. import GH_TooltipDisplayEventArgs
class GH_WireInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, iParent: GH_Canvas, mEvent: GH_CanvasMouseEvent, Source: IGH_Param): ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import GH_CanvasMouseEvent
from .. import GH_TooltipDisplayEventArgs
class GH_ZoomInteraction(GH_AbstractInteraction):
    @overload
    def __init__(self, iParent: GH_Canvas, mEvent: GH_CanvasMouseEvent): ...
    @overload
    def Destroy(self) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Canvas(self) -> GH_Canvas: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


class IGH_MouseInteraction:
    @overload
    def Destroy(self) -> None: ...
    @overload
    @property
    def CanvasPointDown(self) -> PointF: ...
    @overload
    @property
    def ControlPointDown(self) -> Point: ...
    @overload
    @property
    def DeactivateOnFocusLoss(self) -> bool: ...
    @overload
    @property
    def IsActive(self) -> bool: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
