from typing import Tuple, Iterable, overload
from enum import Enum



class CreaseEdges(Enum):
    NakedFixed = 0
    NakedSmooth = 1
    CornerFixedOtherCreased = 2
    Auto = 3


class LoopFormula(Enum):
    Loop = 0
    Warren = 1
    WarrenWeimer = 2


class RefinementSettings:
    def __init__(self): ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def ContinueRequest(self) -> CancellationToken: ...
    @property
    def HasPull(self) -> bool: ...
    @property
    def Level(self) -> int: ...
    @property
    def NakedEdgeMode(self) -> CreaseEdges: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @ContinueRequest.setter
    def ContinueRequest(self, value: CancellationToken) -> None: ...
    @Level.setter
    def Level(self, value: int) -> None: ...
    @NakedEdgeMode.setter
    def NakedEdgeMode(self, value: CreaseEdges) -> None: ...
    def ToString(self) -> str: ...
