from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



from .. import RhinoDoc
class BitmapTable:
    def __iter__(self) -> Iterator[BitmapEntry]: ...
    def __getitem__(self, index: int) -> BitmapEntry: ...
    def __setitem__(self, index: int, value: BitmapEntry): ...
    @overload
    def AddBitmap(self, bitmapFilename: str, replaceExisting: bool) -> int: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Delete(self, item: BitmapEntry) -> bool: ...
    @overload
    def DeleteBitmap(self, bitmapFilename: str) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def ExportToFile(self, index: int, path: str) -> bool: ...
    @overload
    def ExportToFiles(self, directoryPath: str, overwrite: int) -> int: ...
    @overload
    def Find(self, name: str, createFile: bool) -> Tuple[BitmapEntry, str]: ...
    @overload
    def FindId(self, id: Guid) -> BitmapEntry: ...
    @overload
    def FindIndex(self, index: int) -> BitmapEntry: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[BitmapEntry]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ...Geometry import AnnotationBase
from .. import RhinoDoc
class DimStyleTable:
    def __iter__(self) -> Iterator[DimensionStyle]: ...
    def __getitem__(self, index: int) -> DimensionStyle: ...
    def __setitem__(self, index: int, value: DimensionStyle): ...
    @overload
    def Add(self, name: str) -> int: ...
    @overload
    def Add(self, dimstyle: DimensionStyle, reference: bool) -> int: ...
    @overload
    def Add(self, name: str, reference: bool) -> int: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Delete(self, item: DimensionStyle) -> bool: ...
    @overload
    def Delete(self, index: int, quiet: bool) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, styleId: Guid, ignoreDeleted: bool) -> DimensionStyle: ...
    @overload
    def FindId(self, id: Guid) -> DimensionStyle: ...
    @overload
    def FindIndex(self, index: int) -> DimensionStyle: ...
    @overload
    def FindName(self, name: str) -> DimensionStyle: ...
    @overload
    def FindRoot(self, styleId: Guid, ignoreDeleted: bool) -> DimensionStyle: ...
    @overload
    @property
    def BuiltInStyles(self) -> Iterable[DimensionStyle]: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Current(self) -> DimensionStyle: ...
    @overload
    @property
    def CurrentDimensionStyle(self) -> DimensionStyle: ...
    @overload
    @property
    def CurrentId(self) -> Guid: ...
    @overload
    @property
    def CurrentIndex(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[DimensionStyle]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetUnusedStyleName(self) -> str: ...
    @overload
    def GetUnusedStyleName(self, rootName: str) -> str: ...
    @overload
    def Modify(self, dimstyle: DimensionStyle, annotation: AnnotationBase) -> ModifyType: ...
    @overload
    def Modify(self, newSettings: DimensionStyle, dimstyleIndex: int, quiet: bool) -> bool: ...
    @overload
    def Modify(self, newSettings: DimensionStyle, dimstyleId: Guid, quiet: bool) -> bool: ...
    @overload
    def SetCurrent(self, index: int, quiet: bool) -> bool: ...
    @overload
    def ToString(self) -> str: ...


from .. import RhinoDoc
class DimStyleTableEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def EventType(self) -> DimStyleTableEventType: ...
    @overload
    @property
    def Index(self) -> int: ...
    @overload
    @property
    def NewState(self) -> DimensionStyle: ...
    @overload
    @property
    def OldState(self) -> DimensionStyle: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class DimStyleTableEventType(Enum):
    Added = 0
    Deleted = 1
    Undeleted = 2
    Modified = 3
    Sorted = 4
    Current = 5


from .. import RhinoDoc
class FontTable:
    def __iter__(self) -> Iterator[Font]: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def FindOrCreate(self, face: str, bold: bool, italic: bool) -> int: ...
    @overload
    def FindOrCreate(self, face: str, bold: bool, italic: bool, template_style: DimensionStyle) -> int: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def CurrentIndex(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[Font]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ...FileIO import NameHash
from .. import RhinoDoc
class GroupTable:
    def __iter__(self) -> Iterator[Group]: ...
    def __getitem__(self, index: int) -> Group: ...
    def __setitem__(self, index: int, value: Group): ...
    @overload
    def Add(self) -> int: ...
    @overload
    def Add(self, objectIds: Iterable[Guid]) -> int: ...
    @overload
    def Add(self, groupName: str) -> int: ...
    @overload
    def Add(self, groupName: str, objectIds: Iterable[Guid]) -> int: ...
    @overload
    def AddToGroup(self, groupIndex: int, objectIds: Iterable[Guid]) -> bool: ...
    @overload
    def AddToGroup(self, groupIndex: int, objectId: Guid) -> bool: ...
    @overload
    def ChangeGroupName(self, groupIndex: int, newName: str) -> bool: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Delete(self, groupIndex: int) -> bool: ...
    @overload
    def Delete(self, item: Group) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, groupName: str) -> int: ...
    @overload
    def FindId(self, id: Guid) -> Group: ...
    @overload
    def FindIndex(self, index: int) -> Group: ...
    @overload
    def FindName(self, name: str) -> Group: ...
    @overload
    def FindNameHash(self, nameHash: NameHash) -> Group: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[Group]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GroupMembers(self, groupIndex: int) -> Iterable[RhinoObject]: ...
    @overload
    def GroupName(self, groupIndex: int) -> str: ...
    @overload
    def GroupNames(self, ignoreDeletedGroups: bool) -> Iterable[str]: ...
    @overload
    def GroupObjectCount(self, groupIndex: int) -> int: ...
    @overload
    def Hide(self, groupIndex: int) -> int: ...
    @overload
    def IsDeleted(self, groupIndex: int) -> bool: ...
    @overload
    def Lock(self, groupIndex: int) -> int: ...
    @overload
    def RemapObjects(self, rhinoObjects: Iterable[RhinoObject]) -> int: ...
    @overload
    def RemapObjects(self, rhinoObjects: Iterable[RhinoObject]) -> Tuple[int, Dictionary]: ...
    @overload
    def Show(self, groupIndex: int) -> int: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undelete(self, groupIndex: int) -> bool: ...
    @overload
    def Unlock(self, groupIndex: int) -> int: ...


from .. import RhinoDoc
class GroupTableEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def EventType(self) -> GroupTableEventType: ...
    @overload
    @property
    def GroupIndex(self) -> int: ...
    @overload
    @property
    def NewState(self) -> Group: ...
    @overload
    @property
    def OldState(self) -> Group: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GroupTableEventType(Enum):
    Added = 0
    Deleted = 1
    Undeleted = 2
    Modified = 3
    Sorted = 4


from ...FileIO import NameHash
from .. import RhinoDoc
class HatchPatternTable:
    def __iter__(self) -> Iterator[HatchPattern]: ...
    def __getitem__(self, index: int) -> HatchPattern: ...
    def __setitem__(self, index: int, value: HatchPattern): ...
    @overload
    def Add(self, pattern: HatchPattern) -> int: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Delete(self, hatchPatternIndex: int) -> bool: ...
    @overload
    def Delete(self, item: HatchPattern) -> bool: ...
    @overload
    def Delete(self, item: HatchPattern, quiet: bool) -> bool: ...
    @overload
    def Delete(self, hatchPatternIndex: int, quiet: bool) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def FindId(self, id: Guid) -> HatchPattern: ...
    @overload
    def FindIndex(self, index: int) -> HatchPattern: ...
    @overload
    def FindName(self, name: str) -> HatchPattern: ...
    @overload
    def FindNameHash(self, nameHash: NameHash) -> HatchPattern: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def CurrentHatchPatternIndex(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[HatchPattern]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Modify(self, hatchPattern: HatchPattern, hatchPatternIndex: int, quiet: bool) -> bool: ...
    @overload
    def Rename(self, item: HatchPattern, hatchPatternName: str) -> bool: ...
    @overload
    def Rename(self, hatchPatternIndex: int, hatchPatternName: str) -> bool: ...
    @overload
    @CurrentHatchPatternIndex.setter
    def CurrentHatchPatternIndex(self, value: int) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import RhinoDoc
class HatchPatternTableEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def EventType(self) -> HatchPatternTableEventType: ...
    @overload
    @property
    def HatchPatternIndex(self) -> int: ...
    @overload
    @property
    def NewState(self) -> HatchPattern: ...
    @overload
    @property
    def OldState(self) -> HatchPattern: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class HatchPatternTableEventType(Enum):
    Added = 0
    Deleted = 1
    Undeleted = 2
    Modified = 3
    Sorted = 4
    Current = 5


from .. import RhinoDoc
from ...Geometry import Point3d
from ...Geometry import GeometryBase
from ..Custom import UserData
from ...FileIO import FileReference
class InstanceDefinitionTable:
    def __iter__(self) -> Iterator[InstanceDefinition]: ...
    def __getitem__(self, index: int) -> InstanceDefinition: ...
    def __setitem__(self, index: int, value: InstanceDefinition): ...
    @overload
    def Add(self, name: str, description: str, basePoint: Point3d, geometry: Iterable[GeometryBase]) -> int: ...
    @overload
    def Add(self, name: str, description: str, basePoint: Point3d, geometry: GeometryBase, attributes: ObjectAttributes) -> int: ...
    @overload
    def Add(self, name: str, description: str, basePoint: Point3d, geometry: Iterable[GeometryBase], attributes: Iterable[ObjectAttributes]) -> int: ...
    @overload
    def Add(self, name: str, description: str, url: str, urlTag: str, basePoint: Point3d, geometry: Iterable[GeometryBase], attributes: Iterable[ObjectAttributes]) -> int: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Compact(self, ignoreUndoReferences: bool) -> None: ...
    @overload
    def Delete(self, item: InstanceDefinition) -> bool: ...
    @overload
    def Delete(self, idefIndex: int, deleteReferences: bool, quiet: bool) -> bool: ...
    @overload
    def DestroySourceArchive(self, definition: InstanceDefinition, quiet: bool) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, instanceDefinitionName: str) -> InstanceDefinition: ...
    @overload
    def Find(self, instanceId: Guid, ignoreDeletedInstanceDefinitions: bool) -> InstanceDefinition: ...
    @overload
    def FindId(self, id: Guid) -> InstanceDefinition: ...
    @overload
    @property
    def ActiveCount(self) -> int: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[InstanceDefinition]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetList(self, ignoreDeleted: bool) -> Iterable[InstanceDefinition]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetUnusedInstanceDefinitionName(self) -> str: ...
    @overload
    def GetUnusedInstanceDefinitionName(self, root: str) -> str: ...
    @overload
    def InstanceDefinitionIndex(self, instanceId: Guid, ignoreDeletedInstanceDefinitions: bool) -> int: ...
    @overload
    def Modify(self, idefIndex: int, userData: UserData, quiet: bool) -> bool: ...
    @overload
    def Modify(self, idef: InstanceDefinition, newName: str, newDescription: str, quiet: bool) -> bool: ...
    @overload
    def Modify(self, idefIndex: int, newName: str, newDescription: str, quiet: bool) -> bool: ...
    @overload
    def Modify(self, idef: InstanceDefinition, newName: str, newDescription: str, newUrl: str, newUrlTag: str, quiet: bool) -> bool: ...
    @overload
    def Modify(self, idefIndex: int, newName: str, newDescription: str, newUrl: str, newUrlTag: str, quiet: bool) -> bool: ...
    @overload
    def ModifyGeometry(self, idefIndex: int, newGeometry: Iterable[GeometryBase]) -> bool: ...
    @overload
    def ModifyGeometry(self, idefIndex: int, newGeometry: Iterable[GeometryBase], newAttributes: Iterable[ObjectAttributes]) -> bool: ...
    @overload
    def ModifyGeometry(self, idefIndex: int, newGeometry: GeometryBase, newAttributes: ObjectAttributes) -> bool: ...
    @overload
    def ModifySourceArchive(self, idefIndex: int, sourceArchive: FileReference, updateType: InstanceDefinitionUpdateType, quiet: bool) -> bool: ...
    @overload
    def Purge(self, idefIndex: int) -> bool: ...
    @overload
    def RefreshLinkedBlock(self, definition: InstanceDefinition) -> bool: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undelete(self, idefIndex: int) -> bool: ...
    @overload
    def UndoModify(self, idefIndex: int) -> bool: ...
    @overload
    def UpdateLinkedInstanceDefinition(self, idefIndex: int, filename: str, updateNestedLinks: bool, quiet: bool) -> bool: ...


from .. import RhinoDoc
from ...Geometry import InstanceDefinitionGeometry
class InstanceDefinitionTableEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def EventType(self) -> InstanceDefinitionTableEventType: ...
    @overload
    @property
    def InstanceDefinitionIndex(self) -> int: ...
    @overload
    @property
    def NewState(self) -> InstanceDefinition: ...
    @overload
    @property
    def OldState(self) -> InstanceDefinitionGeometry: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class InstanceDefinitionTableEventType(Enum):
    Added = 0
    Deleted = 1
    Undeleted = 2
    Modified = 3
    Sorted = 4


from .. import RhinoDoc
from ...FileIO import NameHash
class LayerTable:
    def __iter__(self) -> Iterator[Layer]: ...
    def __getitem__(self, index: int) -> Layer: ...
    def __setitem__(self, index: int, value: Layer): ...
    @overload
    def Add(self) -> int: ...
    @overload
    def Add(self, layer: Layer) -> int: ...
    @overload
    def Add(self, layerName: str, layerColor: Color) -> int: ...
    @overload
    def AddPath(self, layerPath: str) -> int: ...
    @overload
    def AddPath(self, layerPath: str, layerColor: Color) -> int: ...
    @overload
    def AddReferenceLayer(self) -> int: ...
    @overload
    def AddReferenceLayer(self, layer: Layer) -> int: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def CreateLayer(self, newLayer: Layer, layerType: LayerType, worksessionReferenceModelSerialNumber: UInt32, linkedInstanceDefinitionSerialNumber: UInt32) -> int: ...
    @overload
    def Delete(self, layer: Layer) -> bool: ...
    @overload
    def Delete(self, layerId: Guid, quiet: bool) -> bool: ...
    @overload
    def Delete(self, layer: Layer, quiet: bool) -> bool: ...
    @overload
    def Delete(self, layerIndices: Iterable[int], quiet: bool) -> int: ...
    @overload
    def Delete(self, layerIndex: int, quiet: bool) -> bool: ...
    @overload
    def Duplicate(self, layerIndex: int, duplicateObjects: bool, duplicateSublayers: bool) -> Iterable[int]: ...
    @overload
    def Duplicate(self, layerIndices: Iterable[int], duplicateObjects: bool, duplicateSublayers: bool) -> Iterable[int]: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, parentId: Guid, layerName: str, notFoundReturnValue: int) -> int: ...
    @overload
    def Find(self, layerId: Guid, ignoreDeletedLayers: bool, notFoundReturnValue: int) -> int: ...
    @overload
    def FindByFullPath(self, layerPath: str, notFoundReturnValue: int) -> int: ...
    @overload
    def FindId(self, id: Guid) -> Layer: ...
    @overload
    def FindIndex(self, index: int) -> Layer: ...
    @overload
    def FindName(self, layerName: str) -> Layer: ...
    @overload
    def FindName(self, layerName: str, startIndex: int) -> Layer: ...
    @overload
    def FindNameHash(self, nameHash: NameHash) -> Layer: ...
    @overload
    def FindNext(self, index: int, layerName: str) -> Layer: ...
    @overload
    def ForceLayerVisible(self, layerId: Guid) -> bool: ...
    @overload
    def ForceLayerVisible(self, layerIndex: int) -> bool: ...
    @overload
    @property
    def ActiveCount(self) -> int: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def CurrentLayer(self) -> Layer: ...
    @overload
    @property
    def CurrentLayerIndex(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[Layer]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetSelected(self) -> Tuple[bool, List]: ...
    @overload
    def GetSorted(self) -> Iterable[int]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetUnusedLayerName(self) -> str: ...
    @overload
    def Modify(self, newSettings: Layer, layerId: Guid, quiet: bool) -> bool: ...
    @overload
    def Modify(self, newSettings: Layer, layerIndex: int, quiet: bool) -> bool: ...
    @overload
    def Purge(self, layerIndex: int, quiet: bool) -> bool: ...
    @overload
    def Purge(self, layerId: Guid, quiet: bool) -> bool: ...
    @overload
    def Select(self, layerIndices: Iterable[int], bDeselect: bool) -> bool: ...
    @overload
    def SetCurrentLayerIndex(self, layerIndex: int, quiet: bool) -> bool: ...
    @overload
    def Sort(self, layerIndices: Iterable[int]) -> None: ...
    @overload
    def SortByLayerName(self, bAscending: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undelete(self, layerIndex: int) -> bool: ...
    @overload
    def UndoModify(self, layerIndex: int) -> bool: ...
    @overload
    def UndoModify(self, layerId: Guid) -> bool: ...
    @overload
    def UndoModify(self, layerIndex: int, undoRecordSerialNumber: UInt32) -> bool: ...
    @overload
    def UndoModify(self, layerId: Guid, undoRecordSerialNumber: UInt32) -> bool: ...


from .. import RhinoDoc
class LayerTableEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def EventType(self) -> LayerTableEventType: ...
    @overload
    @property
    def LayerIndex(self) -> int: ...
    @overload
    @property
    def NewState(self) -> Layer: ...
    @overload
    @property
    def OldState(self) -> Layer: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class LayerTableEventType(Enum):
    Added = 0
    Deleted = 1
    Undeleted = 2
    Modified = 3
    Sorted = 4
    Current = 5


class LayerType(Enum):
    NormalLayer = 0
    LinkedInstanceDefinitionParentLayer = 2
    WorkSessionParentLayer = 4


from .. import RhinoDoc
from ...Render import Sun
from ...Render import Skylight
from ...FileIO import NameHash
from ...Geometry import Light
class LightTable:
    def __iter__(self) -> Iterator[LightObject]: ...
    def __getitem__(self, index: int) -> LightObject: ...
    def __setitem__(self, index: int, value: LightObject): ...
    @overload
    def Add(self, light: Light) -> int: ...
    @overload
    def Add(self, light: Light, attributes: ObjectAttributes) -> int: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Delete(self, item: LightObject) -> bool: ...
    @overload
    def Delete(self, index: int, quiet: bool) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, id: Guid, ignoreDeleted: bool) -> int: ...
    @overload
    def FindId(self, id: Guid) -> LightObject: ...
    @overload
    def FindIndex(self, index: int) -> LightObject: ...
    @overload
    def FindName(self, name: str) -> LightObject: ...
    @overload
    def FindNameHash(self, nameHash: NameHash) -> LightObject: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[LightObject]: ...
    @overload
    @property
    def Skylight(self) -> Skylight: ...
    @overload
    @property
    def Sun(self) -> Sun: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Modify(self, id: Guid, light: Light) -> bool: ...
    @overload
    def Modify(self, index: int, light: Light) -> bool: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undelete(self, index: int) -> bool: ...


from .. import RhinoDoc
from ...Geometry import Light
class LightTableEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def EventType(self) -> LightTableEventType: ...
    @overload
    @property
    def LightIndex(self) -> int: ...
    @overload
    @property
    def NewState(self) -> LightObject: ...
    @overload
    @property
    def OldState(self) -> Light: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class LightTableEventType(Enum):
    Added = 0
    Deleted = 1
    Undeleted = 2
    Modified = 3
    Sorted = 4


from .. import RhinoDoc
class LinetypeTable:
    def __iter__(self) -> Iterator[Linetype]: ...
    def __getitem__(self, index: int) -> Linetype: ...
    def __setitem__(self, index: int, value: Linetype): ...
    @overload
    def Add(self, linetype: Linetype) -> int: ...
    @overload
    def Add(self, name: str, segmentLengths: Iterable[float]) -> int: ...
    @overload
    def AddReferenceLinetype(self, linetype: Linetype) -> int: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Delete(self, item: Linetype) -> bool: ...
    @overload
    def Delete(self, indices: Iterable[int], quiet: bool) -> bool: ...
    @overload
    def Delete(self, index: int, quiet: bool) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, name: str) -> int: ...
    @overload
    def Find(self, id: Guid, ignoreDeletedLinetypes: bool) -> int: ...
    @overload
    def FindId(self, id: Guid) -> Linetype: ...
    @overload
    def FindIndex(self, index: int) -> Linetype: ...
    @overload
    def FindName(self, name: str) -> Linetype: ...
    @overload
    @property
    def ActiveCount(self) -> int: ...
    @overload
    @property
    def ByLayerLinetypeName(self) -> str: ...
    @overload
    @property
    def ByParentLinetypeName(self) -> str: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def ContinuousLinetypeName(self) -> str: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def CurrentLinetype(self) -> Linetype: ...
    @overload
    @property
    def CurrentLinetypeIndex(self) -> int: ...
    @overload
    @property
    def CurrentLinetypeSource(self) -> ObjectLinetypeSource: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[Linetype]: ...
    @overload
    @property
    def LinetypeScale(self) -> float: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetUnusedLinetypeName(self) -> str: ...
    @overload
    def LinetypeIndexForObject(self, rhinoObject: RhinoObject) -> int: ...
    @overload
    def LoadDefaultLinetypes(self) -> int: ...
    @overload
    def LoadDefaultLinetypes(self, ignoreDeleted: bool) -> int: ...
    @overload
    def Modify(self, linetype: Linetype, index: int, quiet: bool) -> bool: ...
    @overload
    @CurrentLinetypeSource.setter
    def CurrentLinetypeSource(self, value: ObjectLinetypeSource) -> None: ...
    @overload
    @LinetypeScale.setter
    def LinetypeScale(self, value: float) -> None: ...
    @overload
    def SetCurrentLinetypeIndex(self, linetypeIndex: int, quiet: bool) -> bool: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undelete(self, index: int) -> bool: ...
    @overload
    def UndoModify(self, index: int) -> bool: ...


from .. import RhinoDoc
class LinetypeTableEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def EventType(self) -> LinetypeTableEventType: ...
    @overload
    @property
    def LinetypeIndex(self) -> int: ...
    @overload
    @property
    def NewState(self) -> Linetype: ...
    @overload
    @property
    def OldState(self) -> Linetype: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class LinetypeTableEventType(Enum):
    Added = 0
    Deleted = 1
    Undeleted = 2
    Modified = 3
    Sorted = 4
    Current = 5


from .. import RhinoDoc
class MaterialTable:
    def __iter__(self) -> Iterator[Material]: ...
    def __getitem__(self, index: int) -> Material: ...
    def __setitem__(self, index: int, value: Material): ...
    @overload
    def Add(self) -> int: ...
    @overload
    def Add(self, material: Material) -> int: ...
    @overload
    def Add(self, material: Material, reference: bool) -> int: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Delete(self, item: Material) -> bool: ...
    @overload
    def DeleteAt(self, materialIndex: int) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, material: Material, ignoreDeletedMaterials: bool) -> int: ...
    @overload
    def Find(self, materialName: str, ignoreDeletedMaterials: bool) -> int: ...
    @overload
    def Find(self, materialId: Guid, ignoreDeletedMaterials: bool) -> int: ...
    @overload
    def FindId(self, id: Guid) -> Material: ...
    @overload
    def FindIndex(self, index: int) -> Material: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def CurrentMaterialIndex(self) -> int: ...
    @overload
    @property
    def CurrentMaterialSource(self) -> ObjectMaterialSource: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[Material]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Modify(self, newSettings: Material, materialIndex: int, quiet: bool) -> bool: ...
    @overload
    def ResetMaterial(self, materialIndex: int) -> bool: ...
    @overload
    @CurrentMaterialIndex.setter
    def CurrentMaterialIndex(self, value: int) -> None: ...
    @overload
    @CurrentMaterialSource.setter
    def CurrentMaterialSource(self, value: ObjectMaterialSource) -> None: ...
    @overload
    def ToString(self) -> str: ...


from .. import RhinoDoc
class MaterialTableEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def EventType(self) -> MaterialTableEventType: ...
    @overload
    @property
    def Index(self) -> int: ...
    @overload
    @property
    def OldSettings(self) -> Material: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class MaterialTableEventType(Enum):
    Added = 0
    Deleted = 1
    Undeleted = 2
    Modified = 3
    Sorted = 4
    Current = 5


class ModifyType(Enum):
    Modify = 0
    Override = 1
    NotSaved = 2


from .. import RhinoDoc
from ...Geometry import Plane
class NamedConstructionPlaneTable:
    def __iter__(self) -> Iterator[ConstructionPlane]: ...
    @overload
    def Add(self, constructionPlane: ConstructionPlane) -> int: ...
    @overload
    def Add(self, name: str, plane: Plane) -> int: ...
    @overload
    def Delete(self, index: int) -> bool: ...
    @overload
    def Delete(self, name: str) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, name: str) -> int: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[ConstructionPlane]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from .. import RhinoDoc
class NamedLayerStateTable:
    @overload
    def Delete(self, name: str) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def FindName(self, name: str) -> int: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Names(self) -> Iterable[str]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Import(self, filename: str) -> int: ...
    @overload
    def Rename(self, oldName: str, newName: str) -> bool: ...
    @overload
    def Restore(self, name: str, properties: RestoreLayerProperties) -> bool: ...
    @overload
    def Restore(self, name: str, properties: RestoreLayerProperties, viewportId: Guid) -> bool: ...
    @overload
    def Save(self, name: str) -> int: ...
    @overload
    def Save(self, name: str, viewportId: Guid) -> int: ...
    @overload
    def ToString(self) -> str: ...


from .. import RhinoDoc
from ...Geometry import Transform
class NamedPositionTable:
    @overload
    def Append(self, name: str, objects: Iterable[RhinoObject]) -> bool: ...
    @overload
    def Append(self, id: Guid, objects: Iterable[RhinoObject]) -> bool: ...
    @overload
    def Append(self, name: str, objectIds: Iterable[Guid]) -> bool: ...
    @overload
    def Append(self, id: Guid, objectIds: Iterable[Guid]) -> bool: ...
    @overload
    def Delete(self, name: str) -> bool: ...
    @overload
    def Delete(self, id: Guid) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Ids(self) -> Iterable[Guid]: ...
    @overload
    @property
    def Names(self) -> Iterable[str]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Id(self, name: str) -> Guid: ...
    @overload
    def Name(self, id: Guid) -> str: ...
    @overload
    def ObjectIds(self, name: str) -> Iterable[Guid]: ...
    @overload
    def ObjectIds(self, id: Guid) -> Iterable[Guid]: ...
    @overload
    def Objects(self, name: str) -> Iterable[RhinoObject]: ...
    @overload
    def Objects(self, id: Guid) -> Iterable[RhinoObject]: ...
    @overload
    def ObjectXform(self, id: Guid, objId: Guid, xform: Transform) -> Tuple[bool, Transform]: ...
    @overload
    def ObjectXform(self, id: Guid, obj: RhinoObject, xform: Transform) -> Tuple[bool, Transform]: ...
    @overload
    def Rename(self, id: Guid, name: str) -> bool: ...
    @overload
    def Rename(self, oldName: str, name: str) -> bool: ...
    @overload
    def Restore(self, name: str) -> bool: ...
    @overload
    def Restore(self, id: Guid) -> bool: ...
    @overload
    def Save(self, name: str, objects: Iterable[RhinoObject]) -> Guid: ...
    @overload
    def Save(self, name: str, objectIds: Iterable[Guid]) -> Guid: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Update(self, id: Guid) -> bool: ...
    @overload
    def Update(self, name: str) -> bool: ...


from .. import RhinoDoc
from ...Display import RhinoViewport
from ...Display import RhinoView
class NamedViewTable:
    def __iter__(self) -> Iterator[ViewInfo]: ...
    @overload
    def Add(self, view: ViewInfo) -> int: ...
    @overload
    def Add(self, name: str, viewportId: Guid) -> int: ...
    @overload
    def Delete(self, index: int) -> bool: ...
    @overload
    def Delete(self, name: str) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def FindByName(self, name: str) -> int: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self) -> Sequence[ViewInfo]: ...
    @overload
    @property
    def Selection(self) -> Iterable[str]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Rename(self, index: int, newName: str) -> bool: ...
    @overload
    def Rename(self, oldName: str, newName: str) -> bool: ...
    @overload
    def Restore(self, index: int, viewport: RhinoViewport) -> bool: ...
    @overload
    def RestoreAnimatedConstantSpeed(self, index: int, viewport: RhinoViewport, units_per_frame: float, ms_delay: int) -> bool: ...
    @overload
    def RestoreAnimatedConstantTime(self, index: int, viewport: RhinoViewport, frames: int, ms_delay: int) -> bool: ...
    @overload
    def RestoreWithAspectRatio(self, index: int, viewport: RhinoViewport) -> bool: ...
    @overload
    def ToString(self) -> str: ...


from ...Geometry import BoundingBox
from ...Geometry import Transform
from ...Input.Custom import PickContext
from ...Geometry import Surface
from ...Geometry import Extrusion
from ...Geometry import ClippingPlaneSurface
from ...Geometry import Mesh
from ...Geometry import Brep
from ...Geometry import Plane
from ...Geometry import Hatch
from ...Geometry import MorphControl
from ...Render import RenderMaterial
from ...Render import TextureMapping
from ...Geometry import GeometryBase
from ...Geometry import Point3d
from ...Geometry import Point
from ...Geometry import TextEntity
from ...Geometry import Leader
from ...Geometry import TextDot
from ...Geometry import Line
from ...Geometry import Circle
from ...Geometry import Arc
from ...Geometry import Polyline
from ...Geometry import Curve
from ...Geometry import SubD
from ...Geometry import PointCloud
from .. import RhinoDoc
from ...Display import RhinoViewport
from ...Geometry import Point2d
from ..Custom import CustomMeshObject
from ..Custom import CustomBrepObject
from ..Custom import CustomPointObject
from ..Custom import CustomCurveObject
from ...Geometry import Point3f
from ...Collections import RhinoList
from ...Geometry import RadialDimension
from ...Geometry import Rectangle3d
from ...Geometry import Box
from ...Geometry import Ellipse
from ...Geometry import Sphere
from ...Geometry import LinearDimension
from ...Geometry import AngularDimension
from ...Geometry import OrdinateDimension
from ...Geometry import Centermark
from ...Display import Text3d
from ...Geometry import TextJustification
class ObjectTable:
    def __iter__(self) -> Iterator[RhinoObject]: ...
    def __getitem__(self, index: int) -> RhinoObject: ...
    def __setitem__(self, index: int, value: RhinoObject): ...
    @overload
    def Add(self, geometry: GeometryBase) -> Guid: ...
    @overload
    def Add(self, geometry: GeometryBase, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def Add(self, geometry: GeometryBase, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddAngularDimension(self, dimension: AngularDimension) -> Guid: ...
    @overload
    def AddAngularDimension(self, dimension: AngularDimension, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddAngularDimension(self, dimension: AngularDimension, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddArc(self, arc: Arc) -> Guid: ...
    @overload
    def AddArc(self, arc: Arc, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddArc(self, arc: Arc, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddBox(self, box: Box) -> Guid: ...
    @overload
    def AddBox(self, box: Box, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddBox(self, box: Box, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddBrep(self, brep: Brep) -> Guid: ...
    @overload
    def AddBrep(self, brep: Brep, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddBrep(self, brep: Brep, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddBrep(self, brep: Brep, attributes: ObjectAttributes, history: HistoryRecord, reference: bool, splitKinkySurfaces: bool) -> Guid: ...
    @overload
    def AddCentermark(self, centermark: Centermark, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddCircle(self, circle: Circle) -> Guid: ...
    @overload
    def AddCircle(self, circle: Circle, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddCircle(self, circle: Circle, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddClippingPlane(self, plane: Plane, uMagnitude: float, vMagnitude: float, clippedViewportIds: Iterable[Guid]) -> Guid: ...
    @overload
    def AddClippingPlane(self, plane: Plane, uMagnitude: float, vMagnitude: float, clippedViewportId: Guid) -> Guid: ...
    @overload
    def AddClippingPlane(self, plane: Plane, uMagnitude: float, vMagnitude: float, clippedViewportIds: Iterable[Guid], attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddClippingPlane(self, plane: Plane, uMagnitude: float, vMagnitude: float, clippedViewportIds: Iterable[Guid], attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddClippingPlane(self, plane: Plane, uMagnitude: float, vMagnitude: float, clippedViewportId: Guid, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddClippingPlaneSurface(self, clippingPlane: ClippingPlaneSurface, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddCurve(self, curve: Curve) -> Guid: ...
    @overload
    def AddCurve(self, curve: Curve, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddCurve(self, curve: Curve, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddEllipse(self, ellipse: Ellipse) -> Guid: ...
    @overload
    def AddEllipse(self, ellipse: Ellipse, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddEllipse(self, ellipse: Ellipse, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddExplodedInstancePieces(self, instance: InstanceObject, explodeNestedInstances: bool, deleteInstance: bool) -> Iterable[Guid]: ...
    @overload
    def AddExtrusion(self, extrusion: Extrusion) -> Guid: ...
    @overload
    def AddExtrusion(self, extrusion: Extrusion, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddExtrusion(self, extrusion: Extrusion, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddHatch(self, hatch: Hatch) -> Guid: ...
    @overload
    def AddHatch(self, hatch: Hatch, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddHatch(self, hatch: Hatch, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddInstanceObject(self, instanceDefinitionIndex: int, instanceXform: Transform) -> Guid: ...
    @overload
    def AddInstanceObject(self, instanceDefinitionIndex: int, instanceXform: Transform, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddInstanceObject(self, instanceDefinitionIndex: int, instanceXform: Transform, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddLeader(self, points: Iterable[Point3d]) -> Guid: ...
    @overload
    def AddLeader(self, leader: Leader) -> Guid: ...
    @overload
    def AddLeader(self, plane: Plane, points: Iterable[Point2d]) -> Guid: ...
    @overload
    def AddLeader(self, text: str, points: Iterable[Point3d]) -> Guid: ...
    @overload
    def AddLeader(self, leader: Leader, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddLeader(self, plane: Plane, points: Iterable[Point2d], attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddLeader(self, text: str, plane: Plane, points: Iterable[Point2d]) -> Guid: ...
    @overload
    def AddLeader(self, leader: Leader, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddLeader(self, text: str, plane: Plane, points: Iterable[Point2d], attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddLeader(self, text: str, plane: Plane, points: Iterable[Point2d], attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddLine(self, line: Line) -> Guid: ...
    @overload
    def AddLine(self, line: Line, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddLine(self, from_: Point3d, to: Point3d) -> Guid: ...
    @overload
    def AddLine(self, from_: Point3d, to: Point3d, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddLine(self, from_: Point3d, to: Point3d, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddLinearDimension(self, dimension: LinearDimension) -> Guid: ...
    @overload
    def AddLinearDimension(self, dimension: LinearDimension, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddLinearDimension(self, dimension: LinearDimension, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddMesh(self, mesh: Mesh) -> Guid: ...
    @overload
    def AddMesh(self, mesh: Mesh, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddMesh(self, mesh: Mesh, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddMesh(self, mesh: Mesh, attributes: ObjectAttributes, history: HistoryRecord, reference: bool, requireValidMesh: bool) -> Guid: ...
    @overload
    def AddMorphControl(self, morphControl: MorphControl) -> Guid: ...
    @overload
    def AddMorphControl(self, morphControl: MorphControl, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddMorphControl(self, morphControl: MorphControl, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddOrderedPointCloud(self, xCt: int, yCt: int, zCt: int, min: Point3d, max: Point3d, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddOrdinateDimension(self, dimordinate: OrdinateDimension, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddPictureFrame(self, plane: Plane, texturePath: str, asMesh: bool, width: float, height: float, selfIllumination: bool, embedBitmap: bool) -> Guid: ...
    @overload
    def AddPoint(self, point: Point3f) -> Guid: ...
    @overload
    def AddPoint(self, point: Point3d) -> Guid: ...
    @overload
    def AddPoint(self, point: Point3f, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddPoint(self, point: Point3d, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddPoint(self, x: float, y: float, z: float) -> Guid: ...
    @overload
    def AddPoint(self, point: Point, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddPoint(self, point: Point3d, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddPointCloud(self, points: Iterable[Point3d]) -> Guid: ...
    @overload
    def AddPointCloud(self, cloud: PointCloud) -> Guid: ...
    @overload
    def AddPointCloud(self, cloud: PointCloud, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddPointCloud(self, points: Iterable[Point3d], attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddPointCloud(self, points: Iterable[Point3d], attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddPointCloud(self, cloud: PointCloud, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddPoints(self, points: Iterable[Point3d]) -> RhinoList: ...
    @overload
    def AddPoints(self, points: Iterable[Point3f]) -> RhinoList: ...
    @overload
    def AddPoints(self, points: Iterable[Point3f], attributes: ObjectAttributes) -> RhinoList: ...
    @overload
    def AddPoints(self, points: Iterable[Point3d], attributes: ObjectAttributes) -> RhinoList: ...
    @overload
    def AddPolyline(self, points: Iterable[Point3d]) -> Guid: ...
    @overload
    def AddPolyline(self, points: Iterable[Point3d], attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddPolyline(self, points: Iterable[Point3d], attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddRadialDimension(self, dimension: RadialDimension) -> Guid: ...
    @overload
    def AddRadialDimension(self, dimension: RadialDimension, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddRadialDimension(self, dimension: RadialDimension, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddRectangle(self, rectangle: Rectangle3d) -> Guid: ...
    @overload
    def AddRectangle(self, rectangle: Rectangle3d, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddRectangle(self, rectangle: Rectangle3d, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddRhinoObject(self, pointObject: CustomPointObject) -> None: ...
    @overload
    def AddRhinoObject(self, brepObject: CustomBrepObject) -> None: ...
    @overload
    def AddRhinoObject(self, meshObject: CustomMeshObject) -> None: ...
    @overload
    def AddRhinoObject(self, meshObject: CustomMeshObject, history: HistoryRecord) -> None: ...
    @overload
    def AddRhinoObject(self, curveObject: CustomCurveObject, history: HistoryRecord) -> None: ...
    @overload
    def AddRhinoObject(self, curveObject: CurveObject, curve: Curve) -> None: ...
    @overload
    def AddRhinoObject(self, pointObject: PointObject, point: Point) -> None: ...
    @overload
    def AddRhinoObject(self, pointObject: CustomPointObject, history: HistoryRecord) -> None: ...
    @overload
    def AddRhinoObject(self, brepObject: CustomBrepObject, history: HistoryRecord) -> None: ...
    @overload
    def AddRhinoObject(self, meshObject: MeshObject, mesh: Mesh) -> None: ...
    @overload
    def AddRhinoObject(self, brepObject: BrepObject, brep: Brep) -> None: ...
    @overload
    def AddSphere(self, sphere: Sphere) -> Guid: ...
    @overload
    def AddSphere(self, sphere: Sphere, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddSphere(self, sphere: Sphere, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddSubD(self, subD: SubD) -> Guid: ...
    @overload
    def AddSubD(self, subD: SubD, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddSubD(self, subD: SubD, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddSurface(self, surface: Surface) -> Guid: ...
    @overload
    def AddSurface(self, surface: Surface, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddSurface(self, surface: Surface, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddText(self, text: TextEntity) -> Guid: ...
    @overload
    def AddText(self, text3d: Text3d) -> Guid: ...
    @overload
    def AddText(self, text3d: Text3d, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddText(self, text: TextEntity, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddText(self, text: TextEntity, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddText(self, text: str, plane: Plane, height: float, fontName: str, bold: bool, italic: bool) -> Guid: ...
    @overload
    def AddText(self, text: str, plane: Plane, height: float, fontName: str, bold: bool, italic: bool, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddText(self, text: str, plane: Plane, height: float, fontName: str, bold: bool, italic: bool, justification: TextJustification) -> Guid: ...
    @overload
    def AddText(self, text: str, plane: Plane, height: float, fontName: str, bold: bool, italic: bool, justification: TextJustification, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddText(self, text: str, plane: Plane, height: float, fontName: str, bold: bool, italic: bool, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddText(self, text: str, plane: Plane, height: float, fontName: str, bold: bool, italic: bool, justification: TextJustification, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AddTextDot(self, dot: TextDot) -> Guid: ...
    @overload
    def AddTextDot(self, dot: TextDot, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddTextDot(self, text: str, location: Point3d) -> Guid: ...
    @overload
    def AddTextDot(self, text: str, location: Point3d, attributes: ObjectAttributes) -> Guid: ...
    @overload
    def AddTextDot(self, dot: TextDot, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    @overload
    def AllObjectsSince(self, runtimeSerialNumber: UInt32) -> Iterable[RhinoObject]: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def Delete(self, item: RhinoObject) -> bool: ...
    @overload
    def Delete(self, objectId: Guid, quiet: bool) -> bool: ...
    @overload
    def Delete(self, objectIds: Iterable[Guid], quiet: bool) -> int: ...
    @overload
    def Delete(self, objref: ObjRef, quiet: bool) -> bool: ...
    @overload
    def Delete(self, obj: RhinoObject, quiet: bool) -> bool: ...
    @overload
    def Delete(self, objref: ObjRef, quiet: bool, ignoreModes: bool) -> bool: ...
    @overload
    def Delete(self, obj: RhinoObject, quiet: bool, ignoreModes: bool) -> bool: ...
    @overload
    def DeleteGrip(self, grip: GripObject) -> bool: ...
    @overload
    def DeleteGrip(self, gripId: Guid) -> bool: ...
    @overload
    def DeleteGrip(self, gripRef: ObjRef) -> bool: ...
    @overload
    def DeleteGrips(self, gripIds: Iterable[Guid]) -> int: ...
    @overload
    def DeleteGrips(self, grips: Iterable[GripObject]) -> int: ...
    @overload
    def DeleteGrips(self, gripRefs: Iterable[ObjRef]) -> int: ...
    @overload
    def DeleteGrips(self, owner: RhinoObject, gripIndices: Iterable[int]) -> int: ...
    @overload
    def Duplicate(self, objectId: Guid) -> Guid: ...
    @overload
    def Duplicate(self, obj: RhinoObject) -> Guid: ...
    @overload
    def Duplicate(self, objref: ObjRef) -> Guid: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, objectId: Guid) -> RhinoObject: ...
    @overload
    def Find(self, runtimeSerialNumber: UInt32) -> RhinoObject: ...
    @overload
    def FindByCrossingWindowRegion(self, viewport: RhinoViewport, region: Iterable[Point3d], inside: bool, filter: ObjectType) -> Iterable[RhinoObject]: ...
    @overload
    def FindByCrossingWindowRegion(self, viewport: RhinoViewport, screen1: Point2d, screen2: Point2d, inside: bool, filter: ObjectType) -> Iterable[RhinoObject]: ...
    @overload
    def FindByDrawColor(self, drawColor: Color, includeLights: bool) -> Iterable[RhinoObject]: ...
    @overload
    def FindByFilter(self, filter: ObjectEnumeratorSettings) -> Iterable[RhinoObject]: ...
    @overload
    def FindByGroup(self, groupIndex: int) -> Iterable[RhinoObject]: ...
    @overload
    def FindByLayer(self, layerName: str) -> Iterable[RhinoObject]: ...
    @overload
    def FindByLayer(self, layer: Layer) -> Iterable[RhinoObject]: ...
    @overload
    def FindByObjectType(self, typeFilter: ObjectType) -> Iterable[RhinoObject]: ...
    @overload
    def FindByUserString(self, key: str, value: str, caseSensitive: bool) -> Iterable[RhinoObject]: ...
    @overload
    def FindByUserString(self, key: str, value: str, caseSensitive: bool, searchGeometry: bool, searchAttributes: bool, filter: ObjectEnumeratorSettings) -> Iterable[RhinoObject]: ...
    @overload
    def FindByUserString(self, key: str, value: str, caseSensitive: bool, searchGeometry: bool, searchAttributes: bool, filter: ObjectType) -> Iterable[RhinoObject]: ...
    @overload
    def FindByWindowRegion(self, viewport: RhinoViewport, region: Iterable[Point3d], inside: bool, filter: ObjectType) -> Iterable[RhinoObject]: ...
    @overload
    def FindByWindowRegion(self, viewport: RhinoViewport, screen1: Point2d, screen2: Point2d, inside: bool, filter: ObjectType) -> Iterable[RhinoObject]: ...
    @overload
    def FindClippingPlanesForViewport(self, viewport: RhinoViewport) -> Iterable[ClippingPlaneObject]: ...
    @overload
    def FindGeometry(self, id: Guid) -> GeometryBase: ...
    @overload
    def FindId(self, id: Guid) -> RhinoObject: ...
    @overload
    @property
    def BoundingBox(self) -> BoundingBox: ...
    @overload
    @property
    def BoundingBoxVisible(self) -> BoundingBox: ...
    @overload
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def HistoryRecordCount(self) -> int: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectList(self, settings: ObjectEnumeratorSettings) -> Iterable[RhinoObject]: ...
    @overload
    def GetObjectList(self, typeFilter: type) -> Iterable[RhinoObject]: ...
    @overload
    def GetObjectList(self, typeFilter: ObjectType) -> Iterable[RhinoObject]: ...
    @overload
    def GetObjectsByType(self) -> Iterable[T]: ...
    @overload
    def GetObjectsByType(self, settings: ObjectEnumeratorSettings) -> Iterable[T]: ...
    @overload
    def GetSelectedObjectCount(self, checkSubObjects: bool) -> UInt32: ...
    @overload
    def GetSelectedObjects(self, includeLights: bool, includeGrips: bool) -> Iterable[RhinoObject]: ...
    @overload
    def GetSelectedObjectTypes(self) -> ObjectType: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GripUpdate(self, obj: RhinoObject, deleteOriginal: bool) -> RhinoObject: ...
    @overload
    def Hide(self, objref: ObjRef, ignoreLayerMode: bool) -> bool: ...
    @overload
    def Hide(self, obj: RhinoObject, ignoreLayerMode: bool) -> bool: ...
    @overload
    def Hide(self, objectId: Guid, ignoreLayerMode: bool) -> bool: ...
    @overload
    def InvalidateBoundingBox(self) -> None: ...
    @overload
    def Lock(self, objectId: Guid, ignoreLayerMode: bool) -> bool: ...
    @overload
    def Lock(self, obj: RhinoObject, ignoreLayerMode: bool) -> bool: ...
    @overload
    def Lock(self, objref: ObjRef, ignoreLayerMode: bool) -> bool: ...
    @overload
    def ModifyAttributes(self, objref: ObjRef, newAttributes: ObjectAttributes, quiet: bool) -> bool: ...
    @overload
    def ModifyAttributes(self, objectId: Guid, newAttributes: ObjectAttributes, quiet: bool) -> bool: ...
    @overload
    def ModifyAttributes(self, obj: RhinoObject, newAttributes: ObjectAttributes, quiet: bool) -> bool: ...
    @overload
    def ModifyRenderMaterial(self, objRef: ObjRef, material: RenderMaterial) -> bool: ...
    @overload
    def ModifyRenderMaterial(self, obj: RhinoObject, material: RenderMaterial) -> bool: ...
    @overload
    def ModifyRenderMaterial(self, objectId: Guid, material: RenderMaterial) -> bool: ...
    @overload
    def ModifyTextureMapping(self, objRef: ObjRef, channel: int, mapping: TextureMapping) -> bool: ...
    @overload
    def ModifyTextureMapping(self, obj: RhinoObject, channel: int, mapping: TextureMapping) -> bool: ...
    @overload
    def ModifyTextureMapping(self, objId: Guid, channel: int, mapping: TextureMapping) -> bool: ...
    @overload
    def MostRecentObject(self) -> RhinoObject: ...
    @overload
    def ObjectCount(self, filter: ObjectEnumeratorSettings) -> int: ...
    @overload
    def PickObjects(self, pickContext: PickContext) -> Iterable[ObjRef]: ...
    @overload
    def Purge(self, rhinoObject: RhinoObject) -> bool: ...
    @overload
    def Purge(self, runtimeSerialNumber: UInt32) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, extrusion: Extrusion) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, dot: TextDot) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, circle: Circle) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, circle: Circle) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, line: Line) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, line: Line) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, hatch: Hatch) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, hatch: Hatch) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, dot: TextDot) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, arc: Arc) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, leader: Leader) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, text: TextEntity) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, text: TextEntity) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, point: Point) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, point: Point) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, point: Point3d) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, point: Point3d) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, newObject: RhinoObject) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, leader: Leader) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, arc: Arc) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, pointcloud: PointCloud) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, polyline: Polyline) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, curve: Curve) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, curve: Curve) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, surface: Surface) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, surface: Surface) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, brep: Brep) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, brep: Brep) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, polyline: Polyline) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, pointcloud: PointCloud) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, extrusion: Extrusion) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, mesh: Mesh) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, subD: SubD) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, mesh: Mesh) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, subD: SubD) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, geometry: GeometryBase, ignoreModes: bool) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, geometry: GeometryBase, ignoreModes: bool) -> bool: ...
    @overload
    def Replace(self, objref: ObjRef, brep: Brep, splitKinkySurfaces: bool) -> bool: ...
    @overload
    def Replace(self, objectId: Guid, brep: Brep, splitKinkySurfaces: bool) -> bool: ...
    @overload
    def ReplaceInstanceObject(self, objectId: Guid, instanceDefinitionIndex: int) -> bool: ...
    @overload
    def ReplaceInstanceObject(self, objref: ObjRef, instanceDefinitionIndex: int) -> bool: ...
    @overload
    def Select(self, objref: ObjRef) -> bool: ...
    @overload
    def Select(self, objRefs: Iterable[ObjRef]) -> int: ...
    @overload
    def Select(self, objectIds: Iterable[Guid]) -> int: ...
    @overload
    def Select(self, objectId: Guid) -> bool: ...
    @overload
    def Select(self, objref: ObjRef, select: bool) -> bool: ...
    @overload
    def Select(self, objRefs: Iterable[ObjRef], select: bool) -> int: ...
    @overload
    def Select(self, objectId: Guid, select: bool) -> bool: ...
    @overload
    def Select(self, objectIds: Iterable[Guid], select: bool) -> int: ...
    @overload
    def Select(self, objref: ObjRef, select: bool, syncHighlight: bool) -> bool: ...
    @overload
    def Select(self, objectId: Guid, select: bool, syncHighlight: bool) -> bool: ...
    @overload
    def Select(self, objectId: Guid, select: bool, syncHighlight: bool, persistentSelect: bool) -> bool: ...
    @overload
    def Select(self, objref: ObjRef, select: bool, syncHighlight: bool, persistentSelect: bool) -> bool: ...
    @overload
    def Select(self, objectId: Guid, select: bool, syncHighlight: bool, persistentSelect: bool, ignoreGripsState: bool, ignoreLayerLocking: bool, ignoreLayerVisibility: bool) -> bool: ...
    @overload
    def Select(self, objref: ObjRef, select: bool, syncHighlight: bool, persistentSelect: bool, ignoreGripsState: bool, ignoreLayerLocking: bool, ignoreLayerVisibility: bool) -> bool: ...
    @overload
    def SelectedObjectsExist(self, objectType: ObjectType, checkSubObjects: bool) -> bool: ...
    @overload
    def Show(self, objref: ObjRef, ignoreLayerMode: bool) -> bool: ...
    @overload
    def Show(self, objectId: Guid, ignoreLayerMode: bool) -> bool: ...
    @overload
    def Show(self, obj: RhinoObject, ignoreLayerMode: bool) -> bool: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Transform(self, objectId: Guid, xform: Transform, deleteOriginal: bool) -> Guid: ...
    @overload
    def Transform(self, obj: RhinoObject, xform: Transform, deleteOriginal: bool) -> Guid: ...
    @overload
    def Transform(self, objref: ObjRef, xform: Transform, deleteOriginal: bool) -> Guid: ...
    @overload
    def TransformWithHistory(self, objectId: Guid, xform: Transform) -> Guid: ...
    @overload
    def TransformWithHistory(self, obj: RhinoObject, xform: Transform) -> Guid: ...
    @overload
    def TransformWithHistory(self, objref: ObjRef, xform: Transform) -> Guid: ...
    @overload
    def TryFindPoint(self, id: Guid) -> Tuple[bool, Point3d]: ...
    @overload
    def Undelete(self, rhinoObject: RhinoObject) -> bool: ...
    @overload
    def Undelete(self, runtimeSerialNumber: UInt32) -> bool: ...
    @overload
    def Unlock(self, objref: ObjRef, ignoreLayerMode: bool) -> bool: ...
    @overload
    def Unlock(self, objectId: Guid, ignoreLayerMode: bool) -> bool: ...
    @overload
    def Unlock(self, obj: RhinoObject, ignoreLayerMode: bool) -> bool: ...
    @overload
    def UnselectAll(self) -> int: ...
    @overload
    def UnselectAll(self, ignorePersistentSelections: bool) -> int: ...


class RestoreLayerProperties(Enum):
    # None = 0
    Current = 1
    Visible = 2
    Locked = 4
    Color = 8
    Linetype = 16
    PrintColor = 32
    PrintWidth = 64
    ViewportVisible = 128
    ViewportColor = 256
    ViewportPrintColor = 512
    ViewportPrintWidth = 1024
    RenderMaterial = 2048
    SectionStyle = 4096
    NewDetailOn = 8192
    Expanded = 16384
    All = 4294967295




from .. import RhinoDoc
class RuntimeDocumentDataTable:
    def __iter__(self) -> Iterator[KeyValuePair]: ...
    @overload
    def Add(self, key: Object, value: Object) -> None: ...
    @overload
    def Clear(self) -> None: ...
    @overload
    def ContainsKey(self, key: Object) -> bool: ...
    @overload
    def ContainsValue(self, value: Object) -> bool: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Comparer(self) -> IEqualityComparer: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Item(self, key: Object) -> Object: ...
    @overload
    @property
    def Keys(self) -> KeyCollection: ...
    @overload
    @property
    def Values(self) -> ValueCollection: ...
    @overload
    def GetEnumerator(self) -> Enumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetValue(self, key: Object, newT: Func) -> T: ...
    @overload
    def OnDeserialization(self, sender: Object) -> None: ...
    @overload
    def Remove(self, key: Object) -> bool: ...
    @overload
    @Item.setter
    def Item(self, key: Object, value: Object) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def TryGetValue(self, key: Object) -> T: ...
    @overload
    def TryGetValue(self, key: Object) -> Tuple[bool, Object]: ...


from .. import RhinoDoc
class SnapshotTable:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Names(self) -> Iterable[str]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from .. import RhinoDoc
class StringTable:
    @overload
    def Delete(self, key: str) -> None: ...
    @overload
    def Delete(self, section: str, entry: str) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def DocumentDataCount(self) -> int: ...
    @overload
    @property
    def DocumentUserTextCount(self) -> int: ...
    @overload
    def GetEntryNames(self, section: str) -> Iterable[str]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetKey(self, i: int) -> str: ...
    @overload
    def GetSectionNames(self) -> Iterable[str]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetValue(self, key: str) -> str: ...
    @overload
    def GetValue(self, i: int) -> str: ...
    @overload
    def GetValue(self, section: str, entry: str) -> str: ...
    @overload
    def SetString(self, key: str, value: str) -> str: ...
    @overload
    def SetString(self, section: str, entry: str, value: str) -> str: ...
    @overload
    def ToString(self) -> str: ...


from .. import RhinoDoc
from ...Display import RhinoView
from ...Display import ViewTypeFilter
from ...Display import DefinedViewportProjection
from ...Display import RhinoPageView
class ViewTable:
    def __iter__(self) -> Iterator[RhinoView]: ...
    @overload
    def Add(self, title: str, projection: DefinedViewportProjection, position: Rectangle, floating: bool) -> RhinoView: ...
    @overload
    def AddPageView(self, title: str) -> RhinoPageView: ...
    @overload
    def AddPageView(self, title: str, pageWidth: float, pageHeight: float) -> RhinoPageView: ...
    @overload
    def DefaultViewLayout(self) -> None: ...
    @overload
    def EnableCameraIcon(self, view: RhinoView) -> None: ...
    @overload
    def EnableRedraw(self, enable: bool, redrawDocument: bool, redrawLayers: bool) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Find(self, mainViewportId: Guid) -> RhinoView: ...
    @overload
    def Find(self, mainViewportName: str, compareCase: bool) -> RhinoView: ...
    @overload
    def FlashObjects(self, list: Iterable[RhinoObject], useSelectionColor: bool) -> None: ...
    @overload
    def FourViewLayout(self, useMatchingViews: bool) -> None: ...
    @overload
    @property
    def ActiveView(self) -> RhinoView: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def ModelSpaceIsActive(self) -> bool: ...
    @overload
    @property
    def RedrawEnabled(self) -> bool: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetPageViews(self) -> Iterable[RhinoPageView]: ...
    @overload
    def GetStandardRhinoViews(self) -> Iterable[RhinoView]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetViewList(self, filter: ViewTypeFilter) -> Iterable[RhinoView]: ...
    @overload
    def IsCameraIconVisible(self, view: RhinoView) -> bool: ...
    @overload
    def Redraw(self) -> None: ...
    @overload
    @ActiveView.setter
    def ActiveView(self, value: RhinoView) -> None: ...
    @overload
    @RedrawEnabled.setter
    def RedrawEnabled(self, value: bool) -> None: ...
    @overload
    def ThreeViewLayout(self, useMatchingViews: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...
