from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class GH_Interval_Wrapper:
    @overload
    def __init__(self, interval: Interval, wrapperdelegate: GH_IntervalWrapperDelegate): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def A(self) -> float: ...
    @overload
    @property
    def B(self) -> float: ...
    @overload
    @property
    def Increasing(self) -> str: ...
    @overload
    @property
    def Length(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def InternalInterval(self) -> Interval: ...
    @overload
    @A.setter
    def A(self) -> MutableSequence[float]: ...
    @overload
    @B.setter
    def B(self) -> MutableSequence[float]: ...
    @overload
    def ToString(self) -> str: ...


class GH_Interval_Wrapper_TypeConverter:
    @overload
    def __init__(self): ...
    @overload
    def CanConvertFrom(self, sourceType: Type) -> bool: ...
    @overload
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, destinationType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    @overload
    def ConvertFrom(self, value: Object) -> Object: ...
    @overload
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> Object: ...
    @overload
    def ConvertFromInvariantString(self, text: str) -> Object: ...
    @overload
    def ConvertFromInvariantString(self, context: ITypeDescriptorContext, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, context: ITypeDescriptorContext, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, context: ITypeDescriptorContext, culture: CultureInfo, text: str) -> Object: ...
    @overload
    def ConvertTo(self, value: Object, destinationType: Type) -> Object: ...
    @overload
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object, destinationType: Type) -> Object: ...
    @overload
    def ConvertToInvariantString(self, value: Object) -> str: ...
    @overload
    def ConvertToInvariantString(self, context: ITypeDescriptorContext, value: Object) -> str: ...
    @overload
    def ConvertToString(self, value: Object) -> str: ...
    @overload
    def ConvertToString(self, context: ITypeDescriptorContext, value: Object) -> str: ...
    @overload
    def ConvertToString(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> str: ...
    @overload
    def CreateInstance(self, propertyValues: IDictionary) -> Object: ...
    @overload
    def CreateInstance(self, context: ITypeDescriptorContext, propertyValues: IDictionary) -> Object: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetCreateInstanceSupported(self) -> bool: ...
    @overload
    def GetCreateInstanceSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetProperties(self, value: Object) -> PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ITypeDescriptorContext, value: Object) -> PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ITypeDescriptorContext, value: Object, attributes: Iterable[Attribute]) -> PropertyDescriptorCollection: ...
    @overload
    def GetPropertiesSupported(self) -> bool: ...
    @overload
    def GetPropertiesSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetStandardValues(self) -> ICollection: ...
    @overload
    def GetStandardValues(self, context: ITypeDescriptorContext) -> StandardValuesCollection: ...
    @overload
    def GetStandardValuesExclusive(self) -> bool: ...
    @overload
    def GetStandardValuesExclusive(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetStandardValuesSupported(self) -> bool: ...
    @overload
    def GetStandardValuesSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsValid(self, value: Object) -> bool: ...
    @overload
    def IsValid(self, context: ITypeDescriptorContext, value: Object) -> bool: ...
    @overload
    def ToString(self) -> str: ...


class GH_IntervalWrapperDelegate:
    @overload
    def __init__(self, TargetObject: Object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, sender: GH_Interval_Wrapper, interval: Interval, DelegateCallback: AsyncCallback, DelegateAsyncState: Object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> Object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[Object]) -> Object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> Object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def Invoke(self, sender: GH_Interval_Wrapper, interval: Interval) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GH_PlaneModifier:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    @staticmethod
    def Set_X(P: Plane, x_axis: Vector3d) -> Plane: ...
    @overload
    @staticmethod
    def Set_Y(P: Plane, y_axis: Vector3d) -> Plane: ...
    @overload
    @staticmethod
    def Set_Z(P: Plane, z_axis: Vector3d) -> Plane: ...
    @overload
    def ToString(self) -> str: ...


class GH_Point3d_Wrapper:
    @overload
    def __init__(self, pt: Point3d, wrapperdelegate: GH_Point3dWrapperDelegate): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def X(self) -> float: ...
    @overload
    @property
    def Y(self) -> float: ...
    @overload
    @property
    def Z(self) -> float: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def InternalPoint(self) -> Point3d: ...
    @overload
    @X.setter
    def X(self) -> MutableSequence[float]: ...
    @overload
    @Y.setter
    def Y(self) -> MutableSequence[float]: ...
    @overload
    @Z.setter
    def Z(self) -> MutableSequence[float]: ...
    @overload
    def ToString(self) -> str: ...


class GH_Point3d_Wrapper_TypeConverter:
    @overload
    def __init__(self): ...
    @overload
    def CanConvertFrom(self, sourceType: Type) -> bool: ...
    @overload
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, destinationType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    @overload
    def ConvertFrom(self, value: Object) -> Object: ...
    @overload
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> Object: ...
    @overload
    def ConvertFromInvariantString(self, text: str) -> Object: ...
    @overload
    def ConvertFromInvariantString(self, context: ITypeDescriptorContext, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, context: ITypeDescriptorContext, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, context: ITypeDescriptorContext, culture: CultureInfo, text: str) -> Object: ...
    @overload
    def ConvertTo(self, value: Object, destinationType: Type) -> Object: ...
    @overload
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object, destinationType: Type) -> Object: ...
    @overload
    def ConvertToInvariantString(self, value: Object) -> str: ...
    @overload
    def ConvertToInvariantString(self, context: ITypeDescriptorContext, value: Object) -> str: ...
    @overload
    def ConvertToString(self, value: Object) -> str: ...
    @overload
    def ConvertToString(self, context: ITypeDescriptorContext, value: Object) -> str: ...
    @overload
    def ConvertToString(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> str: ...
    @overload
    def CreateInstance(self, propertyValues: IDictionary) -> Object: ...
    @overload
    def CreateInstance(self, context: ITypeDescriptorContext, propertyValues: IDictionary) -> Object: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetCreateInstanceSupported(self) -> bool: ...
    @overload
    def GetCreateInstanceSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetProperties(self, value: Object) -> PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ITypeDescriptorContext, value: Object) -> PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ITypeDescriptorContext, value: Object, attributes: Iterable[Attribute]) -> PropertyDescriptorCollection: ...
    @overload
    def GetPropertiesSupported(self) -> bool: ...
    @overload
    def GetPropertiesSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetStandardValues(self) -> ICollection: ...
    @overload
    def GetStandardValues(self, context: ITypeDescriptorContext) -> StandardValuesCollection: ...
    @overload
    def GetStandardValuesExclusive(self) -> bool: ...
    @overload
    def GetStandardValuesExclusive(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetStandardValuesSupported(self) -> bool: ...
    @overload
    def GetStandardValuesSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsValid(self, value: Object) -> bool: ...
    @overload
    def IsValid(self, context: ITypeDescriptorContext, value: Object) -> bool: ...
    @overload
    def ToString(self) -> str: ...


class GH_Point3dWrapperDelegate:
    @overload
    def __init__(self, TargetObject: Object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, sender: GH_Point3d_Wrapper, point: Point3d, DelegateCallback: AsyncCallback, DelegateAsyncState: Object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> Object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[Object]) -> Object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> Object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def Invoke(self, sender: GH_Point3d_Wrapper, point: Point3d) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Types import GH_PointRefData
class GH_PointRefUV_Wrapper:
    @overload
    def __init__(self, ref: GH_PointRefData, wrapperdelegate: GH_PointRefUVWrapperDelegate): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def U(self) -> float: ...
    @overload
    @property
    def V(self) -> float: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def InternalRefence(self) -> GH_PointRefData: ...
    @overload
    @U.setter
    def U(self) -> MutableSequence[float]: ...
    @overload
    @V.setter
    def V(self) -> MutableSequence[float]: ...
    @overload
    def ToString(self) -> str: ...


class GH_PointRefUV_Wrapper_TypeConverter:
    @overload
    def __init__(self): ...
    @overload
    def CanConvertFrom(self, sourceType: Type) -> bool: ...
    @overload
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, destinationType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    @overload
    def ConvertFrom(self, value: Object) -> Object: ...
    @overload
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> Object: ...
    @overload
    def ConvertFromInvariantString(self, text: str) -> Object: ...
    @overload
    def ConvertFromInvariantString(self, context: ITypeDescriptorContext, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, context: ITypeDescriptorContext, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, context: ITypeDescriptorContext, culture: CultureInfo, text: str) -> Object: ...
    @overload
    def ConvertTo(self, value: Object, destinationType: Type) -> Object: ...
    @overload
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object, destinationType: Type) -> Object: ...
    @overload
    def ConvertToInvariantString(self, value: Object) -> str: ...
    @overload
    def ConvertToInvariantString(self, context: ITypeDescriptorContext, value: Object) -> str: ...
    @overload
    def ConvertToString(self, value: Object) -> str: ...
    @overload
    def ConvertToString(self, context: ITypeDescriptorContext, value: Object) -> str: ...
    @overload
    def ConvertToString(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> str: ...
    @overload
    def CreateInstance(self, propertyValues: IDictionary) -> Object: ...
    @overload
    def CreateInstance(self, context: ITypeDescriptorContext, propertyValues: IDictionary) -> Object: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetCreateInstanceSupported(self) -> bool: ...
    @overload
    def GetCreateInstanceSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetProperties(self, value: Object) -> PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ITypeDescriptorContext, value: Object) -> PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ITypeDescriptorContext, value: Object, attributes: Iterable[Attribute]) -> PropertyDescriptorCollection: ...
    @overload
    def GetPropertiesSupported(self) -> bool: ...
    @overload
    def GetPropertiesSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetStandardValues(self) -> ICollection: ...
    @overload
    def GetStandardValues(self, context: ITypeDescriptorContext) -> StandardValuesCollection: ...
    @overload
    def GetStandardValuesExclusive(self) -> bool: ...
    @overload
    def GetStandardValuesExclusive(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetStandardValuesSupported(self) -> bool: ...
    @overload
    def GetStandardValuesSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsValid(self, value: Object) -> bool: ...
    @overload
    def IsValid(self, context: ITypeDescriptorContext, value: Object) -> bool: ...
    @overload
    def ToString(self) -> str: ...


from ..Types import GH_PointRefData
class GH_PointRefUVWrapperDelegate:
    @overload
    def __init__(self, TargetObject: Object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, sender: GH_PointRefUV_Wrapper, ref: GH_PointRefData, DelegateCallback: AsyncCallback, DelegateAsyncState: Object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> Object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[Object]) -> Object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> Object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def Invoke(self, sender: GH_PointRefUV_Wrapper, ref: GH_PointRefData) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GH_Vector3d_Wrapper:
    @overload
    def __init__(self, vec: Vector3d, wrapperdelegate: GH_Vector3dWrapperDelegate): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Length(self) -> str: ...
    @overload
    @property
    def Tiny(self) -> str: ...
    @overload
    @property
    def X(self) -> float: ...
    @overload
    @property
    def Y(self) -> float: ...
    @overload
    @property
    def Z(self) -> float: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def InternalVector(self) -> Vector3d: ...
    @overload
    @X.setter
    def X(self) -> MutableSequence[float]: ...
    @overload
    @Y.setter
    def Y(self) -> MutableSequence[float]: ...
    @overload
    @Z.setter
    def Z(self) -> MutableSequence[float]: ...
    @overload
    def ToString(self) -> str: ...


class GH_Vector3d_Wrapper_TypeConverter:
    @overload
    def __init__(self): ...
    @overload
    def CanConvertFrom(self, sourceType: Type) -> bool: ...
    @overload
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, destinationType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    @overload
    def ConvertFrom(self, value: Object) -> Object: ...
    @overload
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> Object: ...
    @overload
    def ConvertFromInvariantString(self, text: str) -> Object: ...
    @overload
    def ConvertFromInvariantString(self, context: ITypeDescriptorContext, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, context: ITypeDescriptorContext, text: str) -> Object: ...
    @overload
    def ConvertFromString(self, context: ITypeDescriptorContext, culture: CultureInfo, text: str) -> Object: ...
    @overload
    def ConvertTo(self, value: Object, destinationType: Type) -> Object: ...
    @overload
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object, destinationType: Type) -> Object: ...
    @overload
    def ConvertToInvariantString(self, value: Object) -> str: ...
    @overload
    def ConvertToInvariantString(self, context: ITypeDescriptorContext, value: Object) -> str: ...
    @overload
    def ConvertToString(self, value: Object) -> str: ...
    @overload
    def ConvertToString(self, context: ITypeDescriptorContext, value: Object) -> str: ...
    @overload
    def ConvertToString(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> str: ...
    @overload
    def CreateInstance(self, propertyValues: IDictionary) -> Object: ...
    @overload
    def CreateInstance(self, context: ITypeDescriptorContext, propertyValues: IDictionary) -> Object: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetCreateInstanceSupported(self) -> bool: ...
    @overload
    def GetCreateInstanceSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetProperties(self, value: Object) -> PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ITypeDescriptorContext, value: Object) -> PropertyDescriptorCollection: ...
    @overload
    def GetProperties(self, context: ITypeDescriptorContext, value: Object, attributes: Iterable[Attribute]) -> PropertyDescriptorCollection: ...
    @overload
    def GetPropertiesSupported(self) -> bool: ...
    @overload
    def GetPropertiesSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetStandardValues(self) -> ICollection: ...
    @overload
    def GetStandardValues(self, context: ITypeDescriptorContext) -> StandardValuesCollection: ...
    @overload
    def GetStandardValuesExclusive(self) -> bool: ...
    @overload
    def GetStandardValuesExclusive(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetStandardValuesSupported(self) -> bool: ...
    @overload
    def GetStandardValuesSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsValid(self, value: Object) -> bool: ...
    @overload
    def IsValid(self, context: ITypeDescriptorContext, value: Object) -> bool: ...
    @overload
    def ToString(self) -> str: ...


class GH_Vector3dWrapperDelegate:
    @overload
    def __init__(self, TargetObject: Object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, sender: GH_Vector3d_Wrapper, vector: Vector3d, DelegateCallback: AsyncCallback, DelegateAsyncState: Object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> Object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[Object]) -> Object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> Object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def Invoke(self, sender: GH_Vector3d_Wrapper, vector: Vector3d) -> None: ...
    @overload
    def ToString(self) -> str: ...
