from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class IOAuth2Token:
    @overload
    @property
    def Exp(self) -> Nullable: ...
    @overload
    @property
    def IsExpired(self) -> bool: ...
    @overload
    @property
    def RawToken(self) -> str: ...
    @overload
    @property
    def Scope(self) -> IReadOnlyCollection: ...


class IOpenIDConnectToken:
    @overload
    @property
    def AdminGroups(self) -> IReadOnlyDictionary: ...
    @overload
    @property
    def AllGroups(self) -> IReadOnlyDictionary: ...
    @overload
    @property
    def AtHash(self) -> str: ...
    @overload
    @property
    def Aud(self) -> str: ...
    @overload
    @property
    def AuthTime(self) -> Nullable: ...
    @overload
    @property
    def Emails(self) -> IReadOnlyCollection: ...
    @overload
    @property
    def EmailVerified(self) -> Nullable: ...
    @overload
    @property
    def Exp(self) -> Nullable: ...
    @overload
    @property
    def Iat(self) -> Nullable: ...
    @overload
    @property
    def IsExpired(self) -> bool: ...
    @overload
    @property
    def Iss(self) -> str: ...
    @overload
    @property
    def IsUpdated(self) -> bool: ...
    @overload
    @property
    def Locale(self) -> str: ...
    @overload
    @property
    def MemberGroups(self) -> IReadOnlyDictionary: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Nonce(self) -> str: ...
    @overload
    @property
    def OwnerGroups(self) -> IReadOnlyDictionary: ...
    @overload
    @property
    def Phone(self) -> str: ...
    @overload
    @property
    def Picture(self) -> str: ...
    @overload
    @property
    def RawToken(self) -> str: ...
    @overload
    @property
    def Sub(self) -> str: ...
    @overload
    @property
    def UpdatedAt(self) -> Nullable: ...


class IRhinoAccountsManager:
    @overload
    def ExecuteProtectedCode(self, protectedCode: Action) -> None: ...
    @overload
    def ExecuteProtectedCodeAsync(self, protectedCode: Func) -> Task: ...
    @overload
    def GetAuthTokensAsync(self, clientId: str, clientSecret: str, secretKey: SecretKey, cancellationToken: CancellationToken) -> Task: ...
    @overload
    def GetAuthTokensAsync(self, clientId: str, clientSecret: str, scope: Iterable[str], prompt: str, maxAge: Nullable, showUI: bool, progress: IProgress, secretKey: SecretKey, cancellationToken: CancellationToken) -> Task: ...
    @overload
    def RevokeAuthTokenAsync(self, oauth2Token: IOAuth2Token, secretKey: SecretKey, cancellationToken: CancellationToken) -> Task: ...
    @overload
    def TryGetAuthTokens(self, clientId: str, secretKey: SecretKey) -> Tuple: ...
    @overload
    def TryGetAuthTokens(self, clientId: str, scope: Iterable[str], secretKey: SecretKey) -> Tuple: ...
    @overload
    def UpdateOpenIDConnectTokenAsync(self, currentToken: IOpenIDConnectToken, oauth2Token: IOAuth2Token, secretKey: SecretKey, cancellationToken: CancellationToken) -> Task: ...


class ProgressState(Enum):
    AwaitingLogin = 0
    RetrievingTokens = 1
    AwaitingRedirect = 2
    Other = 3


class RhinoAccoountsProgressInfo:
    @overload
    def __init__(self, state: ProgressState, metadata: Dictionary, customDescription: str): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def Metadata(self) -> Dictionary: ...
    @overload
    @property
    def State(self) -> ProgressState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsAuthTokenMismatchException(RhinoAccountsException):
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def __init__(self, currentUsername: str, newUsername: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsCannotListenException(RhinoAccountsException):
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsException:
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsGroup:
    @overload
    def __init__(self, id: str, name: str): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Id(self) -> str: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsInvalidResponseException(RhinoAccountsException):
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsInvalidStateException(RhinoAccountsException):
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsInvalidTokenException(RhinoAccountsException):
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsManager:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def ExecuteProtectedCode(protectedCode: Action) -> None: ...
    @overload
    @staticmethod
    def ExecuteProtectedCodeAsync(protectedCode: Func) -> Task: ...
    @overload
    @staticmethod
    def GetAuthTokensAsync(clientId: str, clientSecret: str, secretKey: SecretKey, cancellationToken: CancellationToken) -> Task: ...
    @overload
    @staticmethod
    def GetAuthTokensAsync(clientId: str, clientSecret: str, scope: Iterable[str], prompt: str, maxAge: Nullable, showUI: bool, progress: IProgress, secretKey: SecretKey, cancellationToken: CancellationToken) -> Task: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RevokeAuthTokenAsync(oauth2Token: IOAuth2Token, secretKey: SecretKey, cancellationToken: CancellationToken) -> Task: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def TryGetAuthTokens(clientId: str, secretKey: SecretKey) -> Tuple: ...
    @overload
    @staticmethod
    def TryGetAuthTokens(clientId: str, scope: Iterable[str], secretKey: SecretKey) -> Tuple: ...
    @overload
    @staticmethod
    def UpdateOpenIDConnectTokenAsync(currentToken: IOpenIDConnectToken, oauth2Token: IOAuth2Token, secretKey: SecretKey, cancellationToken: CancellationToken) -> Task: ...


class RhinoAccountsOperationInProgressException(RhinoAccountsException):
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def __init__(self, assembly: Assembly, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsProxyException(RhinoAccountsException):
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsServerException(RhinoAccountsException):
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class RhinoAccountsServerNotReachableException(RhinoAccountsException):
    @overload
    def __init__(self, innerException: Exception): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Data(self) -> IDictionary: ...
    @overload
    @property
    def HelpLink(self) -> str: ...
    @overload
    @property
    def HResult(self) -> int: ...
    @overload
    @property
    def InnerException(self) -> Exception: ...
    @overload
    @property
    def Message(self) -> str: ...
    @overload
    @property
    def Source(self) -> str: ...
    @overload
    @property
    def StackTrace(self) -> str: ...
    @overload
    @property
    def TargetSite(self) -> MethodBase: ...
    @overload
    def GetBaseException(self) -> Exception: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @HelpLink.setter
    def HelpLink(self, value: str) -> None: ...
    @overload
    @Source.setter
    def Source(self, value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...


class SecretKey:
    @overload
    def __init__(self): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...
