from typing import overload, Any
from collections.abc import Iterable, Iterator, Sequence, MutableSequence, Callable
from enum import Enum

from Grasshopper.Kernel import GH_GetterResult
from Grasshopper.Kernel.Types import GH_AngularDimension
from Grasshopper.Kernel.Types import GH_Arc
from Grasshopper.Kernel.Types import GH_Box
from Grasshopper.Kernel.Types import GH_Brep
from Grasshopper.Kernel.Types import GH_Centermark
from Grasshopper.Kernel.Types import GH_Circle
from Grasshopper.Kernel.Types import GH_Curve
from Grasshopper.Kernel.Types import GH_Extrusion
from Grasshopper.Kernel.Types import GH_Hatch
from Grasshopper.Kernel.Types import GH_InstanceReference
from Grasshopper.Kernel.Types import GH_Leader
from Grasshopper.Kernel.Types import GH_Light
from Grasshopper.Kernel.Types import GH_Line
from Grasshopper.Kernel.Types import GH_LinearDimension
from Grasshopper.Kernel.Types import GH_Mesh
from Grasshopper.Kernel.Types import GH_OrdinateDimension
from Grasshopper.Kernel.Types import GH_Plane
from Grasshopper.Kernel.Types import GH_Point
from Grasshopper.Kernel.Types import GH_PointCloud
from Grasshopper.Kernel.Types import GH_PointRefType
from Grasshopper.Kernel.Types import GH_RadialDimension
from Grasshopper.Kernel.Types import GH_Rectangle
from Grasshopper.Kernel.Types import GH_SubD
from Grasshopper.Kernel.Types import GH_Surface
from Grasshopper.Kernel.Types import GH_TextDot
from Grasshopper.Kernel.Types import GH_TextEntity
from Grasshopper.Kernel.Types import GH_Vector
from Grasshopper.Kernel.Types import IGH_GeometricGoo
from Rhino.Geometry import Plane
from Rhino.Geometry import Point3d



class GH_AngularDimensionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetAngularDimension() -> GH_AngularDimension: ...
    @overload
    @staticmethod
    def GetAngularDimensions() -> MutableSequence[GH_AngularDimension]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_ArcGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetArc() -> GH_Arc: ...
    @overload
    @staticmethod
    def GetArcs() -> MutableSequence[GH_Arc]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_BoxGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetBox() -> GH_Box: ...
    @overload
    @staticmethod
    def GetBoxes() -> MutableSequence[GH_Box]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_BrepGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetBrep() -> GH_Brep: ...
    @overload
    @staticmethod
    def GetBreps() -> MutableSequence[GH_Brep]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_CentermarkGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetCentermark() -> GH_Centermark: ...
    @overload
    @staticmethod
    def GetCentermarks() -> MutableSequence[GH_Centermark]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_CircleGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetCircle() -> GH_Circle: ...
    @overload
    @staticmethod
    def GetCircles() -> MutableSequence[GH_Circle]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_CurveGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetCurve() -> GH_Curve: ...
    @overload
    @staticmethod
    def GetCurves() -> MutableSequence[GH_Curve]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_ExtrusionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetExtrusion() -> GH_Extrusion: ...
    @overload
    @staticmethod
    def GetExtrusions() -> MutableSequence[GH_Extrusion]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_GeometryGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetGeometries() -> MutableSequence[IGH_GeometricGoo]: ...
    @overload
    @staticmethod
    def GetGeometry() -> IGH_GeometricGoo: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_HatchGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetHatch() -> GH_Hatch: ...
    @overload
    @staticmethod
    def GetHatches() -> MutableSequence[GH_Hatch]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_InstanceReferenceGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetInstanceReference() -> GH_InstanceReference: ...
    @overload
    @staticmethod
    def GetInstanceReferences() -> MutableSequence[GH_InstanceReference]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_LeaderGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLeader() -> GH_Leader: ...
    @overload
    @staticmethod
    def GetLeaders() -> MutableSequence[GH_Leader]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_LightGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLight() -> GH_Light: ...
    @overload
    @staticmethod
    def GetLights() -> MutableSequence[GH_Light]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_LinearDimensionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLinearDimension() -> GH_LinearDimension: ...
    @overload
    @staticmethod
    def GetLinearDimensions() -> MutableSequence[GH_LinearDimension]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_LineGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLine() -> GH_Line: ...
    @overload
    @staticmethod
    def GetLines() -> MutableSequence[GH_Line]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_MeshGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetMesh() -> GH_Mesh: ...
    @overload
    @staticmethod
    def GetMeshes() -> MutableSequence[GH_Mesh]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_OrdinateDimensionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetOrdinateDimension() -> GH_OrdinateDimension: ...
    @overload
    @staticmethod
    def GetOrdinateDimensions() -> MutableSequence[GH_OrdinateDimension]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_PlaneGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetPlane() -> GH_Plane: ...
    @overload
    @staticmethod
    def GetPlanes() -> MutableSequence[GH_Plane]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RotatePlaneX(plane: Plane, pt: Point3d) -> Plane: ...
    @overload
    @staticmethod
    def RotatePlaneY(plane: Plane, pt: Point3d) -> Plane: ...
    @overload
    def ToString(self) -> str: ...


class GH_PointCloudGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetPointCloud() -> GH_PointCloud: ...
    @overload
    @staticmethod
    def GetPointClouds() -> MutableSequence[GH_PointCloud]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_PointGetter:
    @overload
    def __init__(self): ...
    @overload
    def DefaultRefType(self) -> GH_PointRefType: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AcceptPreselected(self) -> bool: ...
    @property
    def PointRefType(self) -> GH_PointRefType: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetPoint(self) -> GH_Point: ...
    @overload
    def GetPoint(self, base: Point3d) -> GH_Point: ...
    @overload
    @staticmethod
    def GetPoint(prompt: str, basePoint: Point3d, outPoint: Point3d) -> tuple[GH_GetterResult, Point3d]: ...
    @overload
    def GetPoints(self) -> MutableSequence[GH_Point]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def RecreateSetup(self, pt: GH_Point) -> None: ...
    @AcceptPreselected.setter
    def AcceptPreselected(self, AutoPropertyValue: bool) -> None: ...
    @PointRefType.setter
    def PointRefType(self, AutoPropertyValue: GH_PointRefType) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GH_RadialDimensionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetRadialDimension() -> GH_RadialDimension: ...
    @overload
    @staticmethod
    def GetRadialDimensions() -> MutableSequence[GH_RadialDimension]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_RectangleGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetRectangle() -> GH_Rectangle: ...
    @overload
    @staticmethod
    def GetRectangles() -> MutableSequence[GH_Rectangle]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_SubDGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetSubD() -> GH_SubD: ...
    @overload
    @staticmethod
    def GetSubDs() -> MutableSequence[GH_SubD]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_SurfaceGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetSurface() -> GH_Surface: ...
    @overload
    @staticmethod
    def GetSurfaces() -> MutableSequence[GH_Surface]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_TextDotGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetTextDot() -> GH_TextDot: ...
    @overload
    @staticmethod
    def GetTextDots() -> MutableSequence[GH_TextDot]: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_TextEntityGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetTextEntities() -> MutableSequence[GH_TextEntity]: ...
    @overload
    @staticmethod
    def GetTextEntity() -> GH_TextEntity: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_TransformGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_VectorGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def GetVector() -> GH_Vector: ...
    @overload
    @staticmethod
    def GetVectors() -> MutableSequence[GH_Vector]: ...
    @overload
    def ToString(self) -> str: ...
