from typing import overload, Any, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum
from System import *
from System.Drawing import *



class DockCornerChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Canvas import GH_Canvas
from ..Canvas import GH_ObjectResponse
class GH_AlignWidget(GH_Widget):
    @overload
    def __init__(self): ...
    @overload
    @staticmethod
    def add_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def AppendToMenu(self, menu: ToolStripDropDownMenu) -> None: ...
    @overload
    def Contains(self, pt_control: Point, pt_canvas: PointF) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def Icon_24x24(self) -> Bitmap: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
    @overload
    @property
    def SharedVisible() -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    @property
    def TooltipText(self) -> str: ...
    @overload
    @property
    def Visible(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    @staticmethod
    def remove_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def Render(self, canvas: GH_Canvas) -> None: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    @Owner.setter
    def Owner(self, Value: GH_Canvas) -> None: ...
    @overload
    @SharedVisible.setter
    def SharedVisible(Value: bool) -> None: ...
    @overload
    @Visible.setter
    def Visible(self, Value: bool) -> None: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Canvas import GH_Viewport
from ..Canvas import GH_Canvas
from ..Canvas import GH_ObjectResponse
class GH_CanvasWidget_FixedObject(GH_Widget):
    @overload
    def AppendToMenu(self, menu: ToolStripDropDownMenu) -> None: ...
    @overload
    def CanvasLocation(self, vp: GH_Viewport) -> PointF: ...
    @overload
    def Contains(self, pt_control: Point, pt_canvas: PointF) -> bool: ...
    @overload
    def ControlLocation(self, vp: GH_Viewport) -> Point: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def Icon_24x24(self) -> Bitmap: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
    @overload
    @property
    def Padding(self) -> int: ...
    @overload
    @property
    def Ratio(self) -> SizeF: ...
    @overload
    @property
    def Size(self) -> Size: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    @property
    def TooltipText(self) -> str: ...
    @overload
    @property
    def Visible(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def Render(self, canvas: GH_Canvas) -> None: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    @Owner.setter
    def Owner(self, Value: GH_Canvas) -> None: ...
    @overload
    @Ratio.setter
    def Ratio(self, Value: SizeF) -> None: ...
    @overload
    @Visible.setter
    def Visible(self, Value: bool) -> None: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Canvas import GH_Canvas
from ..Canvas import GH_ObjectResponse
from ..Canvas import GH_Viewport
class GH_CompassWidget(GH_CanvasWidget_FixedObject):
    @overload
    def __init__(self): ...
    @overload
    @staticmethod
    def add_WidgetDrawModeChanged(obj: WidgetDrawModeChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def add_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def AppendToMenu(self, menu: ToolStripDropDownMenu) -> None: ...
    @overload
    def CanvasLocation(self, vp: GH_Viewport) -> PointF: ...
    @overload
    def Contains(self, pt_control: Point, pt_canvas: PointF) -> bool: ...
    @overload
    def ControlLocation(self, vp: GH_Viewport) -> Point: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def DrawObjects() -> bool: ...
    @overload
    @property
    def DrawSelectionOnly() -> bool: ...
    @overload
    @property
    def Icon_24x24(self) -> Bitmap: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
    @overload
    @property
    def Padding(self) -> int: ...
    @overload
    @property
    def Radius(self) -> int: ...
    @overload
    @property
    def Ratio(self) -> SizeF: ...
    @overload
    @property
    def SharedVisible() -> bool: ...
    @overload
    @property
    def Size(self) -> Size: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    @property
    def TooltipText(self) -> str: ...
    @overload
    @property
    def Visible(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    @staticmethod
    def remove_WidgetDrawModeChanged(obj: WidgetDrawModeChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def remove_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def Render(self, canvas: GH_Canvas) -> None: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    @DrawObjects.setter
    def DrawObjects(Value: bool) -> None: ...
    @overload
    @DrawSelectionOnly.setter
    def DrawSelectionOnly(Value: bool) -> None: ...
    @overload
    @Owner.setter
    def Owner(self, Value: GH_Canvas) -> None: ...
    @overload
    @Ratio.setter
    def Ratio(self, Value: SizeF) -> None: ...
    @overload
    @SharedVisible.setter
    def SharedVisible(Value: bool) -> None: ...
    @overload
    @Visible.setter
    def Visible(self, Value: bool) -> None: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Canvas import GH_Canvas
from ..Canvas import GH_ObjectResponse
class GH_MarkovWidget(GH_Widget):
    @overload
    def __init__(self): ...
    @overload
    @staticmethod
    def add_DockCornerChanged(obj: DockCornerChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def add_IconLimitChanged(obj: IconLimitChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def add_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def AppendToMenu(self, menu: ToolStripDropDownMenu) -> None: ...
    @overload
    def Contains(self, pt_control: Point, pt_canvas: PointF) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def DockCorner() -> GH_MarkovWidgetDock: ...
    @overload
    @property
    def Icon_24x24(self) -> Bitmap: ...
    @overload
    @property
    def IconLimit() -> int: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
    @overload
    @property
    def SharedVisible() -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    @property
    def TooltipText(self) -> str: ...
    @overload
    @property
    def Visible(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    @staticmethod
    def remove_DockCornerChanged(obj: DockCornerChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def remove_IconLimitChanged(obj: IconLimitChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def remove_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def Render(self, Canvas: GH_Canvas) -> None: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    @DockCorner.setter
    def DockCorner(Value: GH_MarkovWidgetDock) -> None: ...
    @overload
    @IconLimit.setter
    def IconLimit(Value: int) -> None: ...
    @overload
    @Owner.setter
    def Owner(self, Value: GH_Canvas) -> None: ...
    @overload
    @SharedVisible.setter
    def SharedVisible(Value: bool) -> None: ...
    @overload
    @Visible.setter
    def Visible(self, Value: bool) -> None: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GH_MarkovWidgetDock(Enum):
    TopLeft = 0
    BottomLeft = 1
    TopRight = 2
    BottomRight = 3


from ..Canvas import GH_Canvas
from ..Canvas import GH_ObjectResponse
class GH_MessageWidget(GH_Widget):
    @overload
    def __init__(self): ...
    @overload
    @staticmethod
    def add_WidgetLevelChanged(obj: WidgetLevelChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def add_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def AppendToMenu(self, menu: ToolStripDropDownMenu) -> None: ...
    @overload
    def Contains(self, pt_control: Point, pt_canvas: PointF) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def Icon_24x24(self) -> Bitmap: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
    @overload
    @property
    def SharedVisible() -> bool: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    @property
    def TooltipText(self) -> str: ...
    @overload
    @property
    def Visible(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    @staticmethod
    def remove_WidgetLevelChanged(obj: WidgetLevelChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def remove_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def Render(self, canvas: GH_Canvas) -> None: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    @Owner.setter
    def Owner(self, Value: GH_Canvas) -> None: ...
    @overload
    @SharedVisible.setter
    def SharedVisible(Value: bool) -> None: ...
    @overload
    @Visible.setter
    def Visible(self, Value: bool) -> None: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Canvas import GH_Canvas
from ..Canvas import GH_ObjectResponse
class GH_ProfilerWidget(GH_Widget):
    @overload
    def __init__(self): ...
    @overload
    @staticmethod
    def add_ProfilerThresholdChanged(obj: ProfilerThresholdChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def add_ShowDurationChanged(obj: ShowDurationChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def add_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def AppendToMenu(self, menu: ToolStripDropDownMenu) -> None: ...
    @overload
    def Contains(self, pt_control: Point, pt_canvas: PointF) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def Icon_24x24(self) -> Bitmap: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
    @overload
    @property
    def SharedVisible() -> bool: ...
    @overload
    @property
    def ShowDuration() -> bool: ...
    @overload
    @property
    def Threshold() -> int: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    @property
    def TooltipText(self) -> str: ...
    @overload
    @property
    def Visible(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    @staticmethod
    def remove_ProfilerThresholdChanged(obj: ProfilerThresholdChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def remove_ShowDurationChanged(obj: ShowDurationChangedEventHandler) -> None: ...
    @overload
    @staticmethod
    def remove_WidgetVisibleChanged(obj: WidgetVisibleChangedEventHandler) -> None: ...
    @overload
    def Render(self, Canvas: GH_Canvas) -> None: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    @Owner.setter
    def Owner(self, Value: GH_Canvas) -> None: ...
    @overload
    @SharedVisible.setter
    def SharedVisible(Value: bool) -> None: ...
    @overload
    @ShowDuration.setter
    def ShowDuration(Value: bool) -> None: ...
    @overload
    @Threshold.setter
    def Threshold(Value: int) -> None: ...
    @overload
    @Visible.setter
    def Visible(self, Value: bool) -> None: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Canvas import GH_Canvas
from ..Canvas import GH_ObjectResponse
class GH_Widget:
    @overload
    def AppendToMenu(self, menu: ToolStripDropDownMenu) -> None: ...
    @overload
    def Contains(self, pt_control: Point, pt_canvas: PointF) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def Icon_24x24(self) -> Bitmap: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
    @overload
    @property
    def TooltipEnabled(self) -> bool: ...
    @overload
    @property
    def TooltipText(self) -> str: ...
    @overload
    @property
    def Visible(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def IsTooltipRegion(self, canvas_coordinate: PointF) -> bool: ...
    @overload
    def Render(self, Canvas: GH_Canvas) -> None: ...
    @overload
    def RespondToKeyDown(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToKeyUp(self, sender: GH_Canvas, e: KeyEventArgs) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDoubleClick(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseDown(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseMove(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    def RespondToMouseUp(self, sender: GH_Canvas, e: GH_CanvasMouseEvent) -> GH_ObjectResponse: ...
    @overload
    @Owner.setter
    def Owner(self, Value: GH_Canvas) -> None: ...
    @overload
    @Visible.setter
    def Visible(self, Value: bool) -> None: ...
    @overload
    def SetupTooltip(self, canvasPoint: PointF, e: GH_TooltipDisplayEventArgs) -> None: ...
    @overload
    def ToString(self) -> str: ...


class IconLimitChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Canvas import GH_Canvas
class IGH_Widget:
    @overload
    def AppendToMenu(self, menu: ToolStripDropDownMenu) -> None: ...
    @overload
    def Contains(self, pt_control: Point, pt_canvas: PointF) -> bool: ...
    @overload
    @property
    def Description(self) -> str: ...
    @overload
    @property
    def Icon_24x24(self) -> Bitmap: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def Owner(self) -> GH_Canvas: ...
    @overload
    @property
    def TooltipText(self) -> str: ...
    @overload
    @property
    def Visible(self) -> bool: ...
    @overload
    def Render(self, Canvas: GH_Canvas) -> None: ...
    @overload
    @Owner.setter
    def Owner(self, Value: GH_Canvas) -> None: ...
    @overload
    @Visible.setter
    def Visible(self, Value: bool) -> None: ...


class ProfilerThresholdChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class ShowDurationChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class WidgetDrawModeChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class WidgetLevelChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class WidgetVisibleChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class WidgetVisibleChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class WidgetVisibleChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class WidgetVisibleChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...


class WidgetVisibleChangedEventHandler:
    @overload
    def __init__(self, TargetObject: object, TargetMethod: IntPtr): ...
    @overload
    def BeginInvoke(self, DelegateCallback: AsyncCallback, DelegateAsyncState: object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[object]) -> object: ...
    @overload
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Invoke(self) -> None: ...
    @overload
    def ToString(self) -> str: ...
