from typing import overload, Any
from collections.abc import Iterable, Iterator, Sequence, MutableSequence, Callable
from enum import Enum

from Grasshopper.Kernel import GH_Document
from Grasshopper.Kernel import IGH_ActiveObject
from Rhino import RhinoDoc
from Rhino.Commands import Command
from Rhino.Commands import Result
from Rhino.Commands import RunMode
from System import IntPtr
from System.Drawing import Bitmap



class Commands:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def BakeDocument(cls) -> GH_Document: ...
    @property
    @classmethod
    def BakeObject(cls) -> IGH_ActiveObject: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def Run_Grasshopper() -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperBake() -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperBake(doc: RhinoDoc, mode: RunMode) -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperDeveloperSettings() -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperExportHelp() -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperFolders() -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperGetSDKDocumentation() -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperOpen() -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperOpen(path: str) -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperReloadAssemblies() -> MutableSequence[str]: ...
    @overload
    @staticmethod
    def Run_GrasshopperScripted() -> bool: ...
    @overload
    @staticmethod
    def Run_GrasshopperUnloadPlugin() -> bool: ...
    @BakeDocument.setter
    @classmethod
    def BakeDocument(cls, Value: GH_Document) -> None: ...
    @BakeObject.setter
    @classmethod
    def BakeObject(cls, Value: IGH_ActiveObject) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GH_PluginUtil:
    @overload
    @staticmethod
    def BringRhinoToTop() -> None: ...
    @overload
    @staticmethod
    def BringWindowToTop(hWnd: IntPtr) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def FocusOnRhino() -> None: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def LoadGrasshopper(message: str) -> tuple[bool, str]: ...
    @overload
    @staticmethod
    def SaveSettings() -> None: ...
    @overload
    @staticmethod
    def SendKeyCodeToRhino(key: int) -> None: ...
    @overload
    @staticmethod
    def SendKeyCodeToRhino(key: str) -> None: ...
    @overload
    @staticmethod
    def SendKeyCodeToRhino(key: str) -> None: ...
    @overload
    @staticmethod
    def SendMessage(hWnd: IntPtr, msg: int, wParam: int, lParam: IntPtr) -> IntPtr: ...
    @overload
    @staticmethod
    def SetFocus(hWnd: IntPtr) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def UnloadGrasshopper() -> bool: ...


class GH_ResourceGate:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    @classmethod
    def BlackIcon(cls) -> Bitmap: ...
    @property
    @classmethod
    def Error_12x12(cls) -> Bitmap: ...
    @property
    @classmethod
    def Error_16x16(cls) -> Bitmap: ...
    @property
    @classmethod
    def Error_24x24(cls) -> Bitmap: ...
    @property
    @classmethod
    def Error_40x40(cls) -> Bitmap: ...
    @property
    @classmethod
    def Info_12x12(cls) -> Bitmap: ...
    @property
    @classmethod
    def Info_16x16(cls) -> Bitmap: ...
    @property
    @classmethod
    def Info_24x24(cls) -> Bitmap: ...
    @property
    @classmethod
    def Info_40x40(cls) -> Bitmap: ...
    @property
    @classmethod
    def OK_12x12(cls) -> Bitmap: ...
    @property
    @classmethod
    def OK_16x16(cls) -> Bitmap: ...
    @property
    @classmethod
    def OK_24x24(cls) -> Bitmap: ...
    @property
    @classmethod
    def OK_40x40(cls) -> Bitmap: ...
    @property
    @classmethod
    def Warning_12x12(cls) -> Bitmap: ...
    @property
    @classmethod
    def Warning_16x16(cls) -> Bitmap: ...
    @property
    @classmethod
    def Warning_24x24(cls) -> Bitmap: ...
    @property
    @classmethod
    def Warning_40x40(cls) -> Bitmap: ...
    @property
    @classmethod
    def WhiteIcon(cls) -> Bitmap: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_RhinoScriptInterface:
    @overload
    def __init__(self): ...
    @overload
    def AssignDataToParameter(self, parameterID: str, data: object) -> bool: ...
    @overload
    def BakeDataInObject(self, objectID: str) -> object: ...
    @overload
    def CloseAllDocuments(self) -> bool: ...
    @overload
    def CloseDocument(self) -> bool: ...
    @overload
    def DisableBanner(self) -> None: ...
    @overload
    def DisableSolver(self) -> None: ...
    @overload
    def EnableBanner(self) -> None: ...
    @overload
    def EnableSolver(self) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def HideEditor(self) -> None: ...
    @overload
    def IsEditorLoaded(self) -> bool: ...
    @overload
    def IsEditorVisible(self) -> bool: ...
    @overload
    def IsSolverEnabled(self) -> bool: ...
    @overload
    def LoadEditor(self) -> None: ...
    @overload
    def LoadedPluginGuids(self) -> Iterable[Guid]: ...
    @overload
    def LoadedPluginNames(self) -> Iterable[str]: ...
    @overload
    def OpenDocument(self, filename: str) -> bool: ...
    @overload
    def RunHeadless(self) -> None: ...
    @overload
    def RunInCommandContext(self, ghDoc: GH_Document, command: Command, rhinoDoc: RhinoDoc, mode: RunMode) -> Result: ...
    @overload
    def RunSolver(self, expireAllObjects: bool) -> None: ...
    @overload
    def SaveDocument(self) -> bool: ...
    @overload
    def SaveDocumentAs(self, filename: str) -> bool: ...
    @overload
    def SetSliderRangeAndValue(self, sliderID: str, value: float, minimum: float, maximum: float) -> bool: ...
    @overload
    def SetSliderValue(self, sliderID: str, value: float) -> bool: ...
    @overload
    def ShowEditor(self) -> None: ...
    @overload
    def ToString(self) -> str: ...
