from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum

import MetaBall

__all__ = ['MetaBall']


class BezierF:
    @overload
    def __init__(self, p0: PointF, p1: PointF, p2: PointF, p3: PointF): ...
    @overload
    def __init__(self, x0: Single, y0: Single, x1: Single, y1: Single, x2: Single, y2: Single, x3: Single, y3: Single): ...
    @overload
    def Distance(self, point: PointF) -> Single: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def Extremes(self) -> Tuple[Iterable[Single], Iterable[Single]]: ...
    @overload
    @property
    def Bounds(self) -> RectangleF: ...
    @overload
    @property
    def IsClosed(self) -> bool: ...
    @overload
    @property
    def IsEmpty(self) -> bool: ...
    @overload
    @property
    def P0(self) -> PointF: ...
    @overload
    @property
    def P1(self) -> PointF: ...
    @overload
    @property
    def P2(self) -> PointF: ...
    @overload
    @property
    def P3(self) -> PointF: ...
    @overload
    @property
    def T0(self) -> SizeF: ...
    @overload
    @property
    def T3(self) -> SizeF: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def PointAt(self, t: Single) -> PointF: ...
    @overload
    def Project(self, point: PointF) -> Single: ...
    @overload
    def Reverse(self) -> BezierF: ...
    @overload
    def TangentAt(self, t: Single) -> SizeF: ...
    @overload
    def ToString(self) -> str: ...


class BezierShape(Enum):
    Unknown = 0
    Arch = 1
    SingleInflection = 2
    DoubleInflection = 3
    Cusp = 4
    Closed = 5
    LoopAtStart = 6
    LoopAtEnd = 7
    LoopOnInterior = 8


class GH_2DIndex:
    @overload
    def __init__(self, other: GH_2DIndex): ...
    @overload
    def __init__(self, new_i: int, new_j: int): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def Set(self, new_i: int, new_j: int) -> None: ...
    @overload
    def Shift(self, offset_i: int, offset_j: int) -> None: ...
    @overload
    def ToString(self) -> str: ...




class GH_3DIndex:
    @overload
    def __init__(self, other: GH_3DIndex): ...
    @overload
    def __init__(self, new_i: int, new_j: int, new_k: int): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def Set(self, new_i: int, new_j: int, new_k: int) -> None: ...
    @overload
    def Shift(self, offset_i: int, offset_j: int, offset_k: int) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GH_NaturalComparer:
    @overload
    def __init__(self): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def ToString(self) -> str: ...


class GH_NaturalStringComparer:
    @overload
    def __init__(self): ...
    @overload
    @staticmethod
    def Compare(s1: str, s2: str) -> int: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def ToString(self) -> str: ...


