from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class GH_Interpolation(Enum):
    linear = 1
    cubic = 2


class GH_Motion:
    @overload
    def __init__(self, rec_0: Rectangle, rec_1: Rectangle, duration: int): ...
    @overload
    def __init__(self, rec_0: Rectangle, rec_1: Rectangle, time_0: Int64, time_1: Int64): ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def CurrentBox(self) -> Rectangle: ...
    @property
    def FinalBox(self) -> Rectangle: ...
    @property
    def InitialBox(self) -> Rectangle: ...
    @property
    def InMotion(self) -> bool: ...
    @property
    def Interpolation(self) -> GH_Interpolation: ...
    @property
    def Parameter(self) -> float: ...
    @property
    def t0(self) -> Int64: ...
    @property
    def t1(self) -> Int64: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def ResizeContainer(self, region: Rectangle, fit_horizontal: bool, fit_vertical: bool) -> None: ...
    @Interpolation.setter
    def Interpolation(self) -> MutableSequence[GH_Interpolation]: ...
    def ToString(self) -> str: ...


class GH_Stack:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, update_interval: int): ...
    @overload
    def __init__(self, update_interval: int, animation_length: int): ...
    @overload
    def __init__(self, update_interval: int, animation_length: int, animation_interpolation: GH_Interpolation): ...
    @overload
    def AddElement(self, rec: Rectangle) -> None: ...
    @overload
    def AddElement(self, rec_0: Rectangle, rec_1: Rectangle) -> None: ...
    @overload
    def AddElement(self, rec_0: Rectangle, rec_1: Rectangle, duration_override: int) -> None: ...
    def Clear(self) -> None: ...
    def Destroy(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def Count(self) -> int: ...
    @property
    def Duration(self) -> int: ...
    @property
    def Element_Final(self) -> Sequence[int]: ...
    @property
    def Element_Initial(self) -> Sequence[int]: ...
    @property
    def Element_Intermediate(self) -> Sequence[int]: ...
    @property
    def InMotion(self) -> bool: ...
    @property
    def InMotion(self) -> Sequence[int]: ...
    @property
    def Interpolation(self) -> GH_Interpolation: ...
    @property
    def UpdateInterval(self) -> int: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def InsertElement(self, index: int, rec: Rectangle) -> None: ...
    @overload
    def InsertElement(self, index: int, rec_0: Rectangle, rec_1: Rectangle) -> None: ...
    @overload
    def InsertElement(self, index: int, rec_0: Rectangle, rec_1: Rectangle, duration_override: int) -> None: ...
    def RemoveElement(self, index: int) -> None: ...
    def ResizeContainer(self, region: Rectangle, fit_horizontal: bool, fit_vertical: bool) -> None: ...
    @Duration.setter
    def Duration(self) -> MutableSequence[int]: ...
    @Interpolation.setter
    def Interpolation(self) -> MutableSequence[GH_Interpolation]: ...
    @UpdateInterval.setter
    def UpdateInterval(self) -> MutableSequence[int]: ...
    @overload
    def SetNewTarget(self, index: int, element: Rectangle) -> None: ...
    @overload
    def SetNewTarget(self, index: int, element: Rectangle, bAnimate: bool) -> None: ...
    @overload
    def SetOwner(self, ui_thread_owner: Control, ui_thread_update: GH_StackEventDelegate) -> None: ...
    @overload
    def SetOwner(self, ui_thread_owner: Control, ui_thread_update: GH_StackEventDelegate, ui_thread_complete: GH_StackEventDelegate) -> None: ...
    def ToString(self) -> str: ...


class GH_StackEventDelegate:
    def __init__(self, TargetObject: Object, TargetMethod: IntPtr): ...
    def BeginInvoke(self, sender: GH_Stack, DelegateCallback: AsyncCallback, DelegateAsyncState: Object) -> IAsyncResult: ...
    def Clone(self) -> Object: ...
    def DynamicInvoke(self, args: Iterable[Object]) -> Object: ...
    def EndInvoke(self, DelegateAsyncResult: IAsyncResult) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> Object: ...
    def GetHashCode(self) -> int: ...
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    def GetType(self) -> Type: ...
    def Invoke(self, sender: GH_Stack) -> None: ...
    def ToString(self) -> str: ...
