from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class BendSpaceMorph(SpaceMorph):
    @overload
    def __init__(self, start: Point3d, end: Point3d, point: Point3d, straight: bool, symmetric: bool): ...
    @overload
    def __init__(self, start: Point3d, end: Point3d, point: Point3d, angle: float, straight: bool, symmetric: bool): ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def PreserveStructure(self) -> bool: ...
    @property
    def QuickPreview(self) -> bool: ...
    @property
    def Tolerance(self) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def Morph(self, geometry: GeometryBase) -> bool: ...
    @overload
    def Morph(self, plane: Plane) -> Tuple[bool, Plane]: ...
    def MorphPoint(self, point: Point3d) -> Point3d: ...
    @PreserveStructure.setter
    def PreserveStructure(self) -> MutableSequence[bool]: ...
    @QuickPreview.setter
    def QuickPreview(self) -> MutableSequence[bool]: ...
    @Tolerance.setter
    def Tolerance(self) -> MutableSequence[float]: ...
    def ToString(self) -> str: ...


class FlowSpaceMorph(SpaceMorph):
    @overload
    def __init__(self, curve0: Curve, curve1: Curve, preventStretching: bool): ...
    @overload
    def __init__(self, curve0: Curve, curve1: Curve, reverseCurve0: bool, reverseCurve1: bool, preventStretching: bool): ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def PreserveStructure(self) -> bool: ...
    @property
    def QuickPreview(self) -> bool: ...
    @property
    def Tolerance(self) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def Morph(self, geometry: GeometryBase) -> bool: ...
    @overload
    def Morph(self, plane: Plane) -> Tuple[bool, Plane]: ...
    def MorphPoint(self, point: Point3d) -> Point3d: ...
    @PreserveStructure.setter
    def PreserveStructure(self) -> MutableSequence[bool]: ...
    @QuickPreview.setter
    def QuickPreview(self) -> MutableSequence[bool]: ...
    @Tolerance.setter
    def Tolerance(self) -> MutableSequence[float]: ...
    def ToString(self) -> str: ...


class MaelstromSpaceMorph(SpaceMorph):
    def __init__(self, plane: Plane, radius0: float, radius1: float, angle: float): ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def PreserveStructure(self) -> bool: ...
    @property
    def QuickPreview(self) -> bool: ...
    @property
    def Tolerance(self) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def Morph(self, geometry: GeometryBase) -> bool: ...
    @overload
    def Morph(self, plane: Plane) -> Tuple[bool, Plane]: ...
    def MorphPoint(self, point: Point3d) -> Point3d: ...
    @PreserveStructure.setter
    def PreserveStructure(self) -> MutableSequence[bool]: ...
    @QuickPreview.setter
    def QuickPreview(self) -> MutableSequence[bool]: ...
    @Tolerance.setter
    def Tolerance(self) -> MutableSequence[float]: ...
    def ToString(self) -> str: ...


class SplopSpaceMorph(SpaceMorph):
    @overload
    def __init__(self, plane: Plane, surface: Surface, surfaceParam: Point2d): ...
    @overload
    def __init__(self, plane: Plane, surface: Surface, surfaceParam: Point2d, scale: float): ...
    @overload
    def __init__(self, plane: Plane, surface: Surface, surfaceParam: Point2d, scale: float, angle: float): ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def PreserveStructure(self) -> bool: ...
    @property
    def QuickPreview(self) -> bool: ...
    @property
    def Tolerance(self) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def Morph(self, geometry: GeometryBase) -> bool: ...
    @overload
    def Morph(self, plane: Plane) -> Tuple[bool, Plane]: ...
    def MorphPoint(self, point: Point3d) -> Point3d: ...
    @PreserveStructure.setter
    def PreserveStructure(self) -> MutableSequence[bool]: ...
    @QuickPreview.setter
    def QuickPreview(self) -> MutableSequence[bool]: ...
    @Tolerance.setter
    def Tolerance(self) -> MutableSequence[float]: ...
    def ToString(self) -> str: ...


class SporphSpaceMorph(SpaceMorph):
    @overload
    def __init__(self, surface0: Surface, surface1: Surface): ...
    @overload
    def __init__(self, surface0: Surface, surface1: Surface, surface0Param: Point2d, surface1Param: Point2d): ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def ConstrainNormal(self) -> Vector3d: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def PreserveStructure(self) -> bool: ...
    @property
    def QuickPreview(self) -> bool: ...
    @property
    def Tolerance(self) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def Morph(self, geometry: GeometryBase) -> bool: ...
    @overload
    def Morph(self, plane: Plane) -> Tuple[bool, Plane]: ...
    def MorphPoint(self, point: Point3d) -> Point3d: ...
    @ConstrainNormal.setter
    def ConstrainNormal(self) -> MutableSequence[Vector3d]: ...
    @PreserveStructure.setter
    def PreserveStructure(self) -> MutableSequence[bool]: ...
    @QuickPreview.setter
    def QuickPreview(self) -> MutableSequence[bool]: ...
    @Tolerance.setter
    def Tolerance(self) -> MutableSequence[float]: ...
    def ToString(self) -> str: ...


class StretchSpaceMorph(SpaceMorph):
    @overload
    def __init__(self, start: Point3d, end: Point3d, point: Point3d): ...
    @overload
    def __init__(self, start: Point3d, end: Point3d, length: float): ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def PreserveStructure(self) -> bool: ...
    @property
    def QuickPreview(self) -> bool: ...
    @property
    def Tolerance(self) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def Morph(self, geometry: GeometryBase) -> bool: ...
    @overload
    def Morph(self, plane: Plane) -> Tuple[bool, Plane]: ...
    def MorphPoint(self, point: Point3d) -> Point3d: ...
    @PreserveStructure.setter
    def PreserveStructure(self) -> MutableSequence[bool]: ...
    @QuickPreview.setter
    def QuickPreview(self) -> MutableSequence[bool]: ...
    @Tolerance.setter
    def Tolerance(self) -> MutableSequence[float]: ...
    def ToString(self) -> str: ...


class TaperSpaceMorph(SpaceMorph):
    def __init__(self, start: Point3d, end: Point3d, startRadius: float, endRadius: float, bFlat: bool, infiniteTaper: bool): ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def PreserveStructure(self) -> bool: ...
    @property
    def QuickPreview(self) -> bool: ...
    @property
    def Tolerance(self) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def Morph(self, geometry: GeometryBase) -> bool: ...
    @overload
    def Morph(self, plane: Plane) -> Tuple[bool, Plane]: ...
    def MorphPoint(self, point: Point3d) -> Point3d: ...
    @PreserveStructure.setter
    def PreserveStructure(self) -> MutableSequence[bool]: ...
    @QuickPreview.setter
    def QuickPreview(self) -> MutableSequence[bool]: ...
    @Tolerance.setter
    def Tolerance(self) -> MutableSequence[float]: ...
    def ToString(self) -> str: ...


class TwistSpaceMorph(SpaceMorph):
    def __init__(self): ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def InfiniteTwist(self) -> bool: ...
    @property
    def PreserveStructure(self) -> bool: ...
    @property
    def QuickPreview(self) -> bool: ...
    @property
    def Tolerance(self) -> float: ...
    @property
    def TwistAngleRadians(self) -> float: ...
    @property
    def TwistAxis(self) -> Line: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @overload
    def Morph(self, plane: Plane) -> Tuple[bool, Plane]: ...
    @overload
    def Morph(self, geometry: GeometryBase) -> bool: ...
    def MorphPoint(self, point: Point3d) -> Point3d: ...
    @InfiniteTwist.setter
    def InfiniteTwist(self) -> MutableSequence[bool]: ...
    @PreserveStructure.setter
    def PreserveStructure(self) -> MutableSequence[bool]: ...
    @QuickPreview.setter
    def QuickPreview(self) -> MutableSequence[bool]: ...
    @Tolerance.setter
    def Tolerance(self) -> MutableSequence[float]: ...
    @TwistAngleRadians.setter
    def TwistAngleRadians(self) -> MutableSequence[float]: ...
    @TwistAxis.setter
    def TwistAxis(self) -> MutableSequence[Line]: ...
    def ToString(self) -> str: ...
