from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class GH_FormattedListItem(GH_SimpleListItem):
    def __init__(self): ...
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def Alignment(self) -> StringAlignment: ...
    @property
    def BoundingBox(self) -> Rectangle: ...
    @property
    def Colour(self) -> Color: ...
    @property
    def Font(self) -> Font: ...
    @property
    def Text(self) -> str: ...
    @property
    def Type(self) -> int: ...
    @property
    def Wrap(self) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @Alignment.setter
    def Alignment(self) -> MutableSequence[StringAlignment]: ...
    @BoundingBox.setter
    def BoundingBox(self) -> MutableSequence[Rectangle]: ...
    @Colour.setter
    def Colour(self) -> MutableSequence[Color]: ...
    @Font.setter
    def Font(self) -> MutableSequence[Font]: ...
    @Text.setter
    def Text(self) -> MutableSequence[str]: ...
    @Type.setter
    def Type(self) -> MutableSequence[int]: ...
    @Wrap.setter
    def Wrap(self) -> MutableSequence[bool]: ...
    def ToString(self) -> str: ...


class GH_SimpleListItem:
    def __init__(self): ...
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def Alignment(self) -> StringAlignment: ...
    @property
    def BoundingBox(self) -> Rectangle: ...
    @property
    def Colour(self) -> Color: ...
    @property
    def Text(self) -> str: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @Alignment.setter
    def Alignment(self) -> MutableSequence[StringAlignment]: ...
    @BoundingBox.setter
    def BoundingBox(self) -> MutableSequence[Rectangle]: ...
    @Colour.setter
    def Colour(self) -> MutableSequence[Color]: ...
    @Text.setter
    def Text(self) -> MutableSequence[str]: ...
    def ToString(self) -> str: ...




class IGH_ListItem:
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    @property
    def BoundingBox(self) -> Rectangle: ...
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @BoundingBox.setter
    def BoundingBox(self) -> MutableSequence[Rectangle]: ...


