from typing import overload, Any, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum
from System import *
from System.Drawing import *



class GH_FormattedListItem(GH_SimpleListItem):
    @overload
    def __init__(self): ...
    @overload
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def Alignment(self) -> StringAlignment: ...
    @property
    def BoundingBox(self) -> Rectangle: ...
    @property
    def Colour(self) -> Color: ...
    @property
    def Font(self) -> Font: ...
    @property
    def Text(self) -> str: ...
    @property
    def Type(self) -> int: ...
    @property
    def Wrap(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @Alignment.setter
    def Alignment(self, Value: StringAlignment) -> None: ...
    @BoundingBox.setter
    def BoundingBox(self, Value: Rectangle) -> None: ...
    @Colour.setter
    def Colour(self, Value: Color) -> None: ...
    @Font.setter
    def Font(self, Value: Font) -> None: ...
    @Text.setter
    def Text(self, Value: str) -> None: ...
    @Type.setter
    def Type(self, Value: int) -> None: ...
    @Wrap.setter
    def Wrap(self, Value: bool) -> None: ...
    @overload
    def ToString(self) -> str: ...


class GH_SimpleListItem:
    @overload
    def __init__(self): ...
    @overload
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def Alignment(self) -> StringAlignment: ...
    @property
    def BoundingBox(self) -> Rectangle: ...
    @property
    def Colour(self) -> Color: ...
    @property
    def Text(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @Alignment.setter
    def Alignment(self, Value: StringAlignment) -> None: ...
    @BoundingBox.setter
    def BoundingBox(self, Value: Rectangle) -> None: ...
    @Colour.setter
    def Colour(self, Value: Color) -> None: ...
    @Text.setter
    def Text(self, Value: str) -> None: ...
    @overload
    def ToString(self) -> str: ...




class IGH_ListItem:
    @overload
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    @property
    def BoundingBox(self) -> Rectangle: ...
    @overload
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @BoundingBox.setter
    def BoundingBox(self, Value: Rectangle) -> None: ...


