from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class GH_BackgroundSettings:
    def Equals(self, obj: Object) -> bool: ...
    @property
    def Colour1(self) -> Color: ...
    @property
    def Colour2(self) -> Color: ...
    @property
    def Hatch(self) -> HatchStyle: ...
    @property
    def Style(self) -> GH_BackgroundStyle: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @Colour1.setter
    def Colour1(self) -> MutableSequence[Color]: ...
    @Colour2.setter
    def Colour2(self) -> MutableSequence[Color]: ...
    @Hatch.setter
    def Hatch(self) -> MutableSequence[HatchStyle]: ...
    @Style.setter
    def Style(self) -> MutableSequence[GH_BackgroundStyle]: ...
    def ToString(self) -> str: ...


class GH_BackgroundStyle(Enum):
    Solid = 0
    Hatch = 1
    GradientLeftRight = 10
    GradientTopBottom = 11


class GH_ObjectSettings:
    def Equals(self, obj: Object) -> bool: ...
    @property
    def GroupColour(self) -> Color: ...
    @property
    def PanelColour(self) -> Color: ...
    @property
    def ZuiEdgeColour(self) -> Color: ...
    @property
    def ZuiFillColour(self) -> Color: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @GroupColour.setter
    def GroupColour(self) -> MutableSequence[Color]: ...
    @PanelColour.setter
    def PanelColour(self) -> MutableSequence[Color]: ...
    @ZuiEdgeColour.setter
    def ZuiEdgeColour(self) -> MutableSequence[Color]: ...
    @ZuiFillColour.setter
    def ZuiFillColour(self) -> MutableSequence[Color]: ...
    def ToString(self) -> str: ...


class GH_PageSettings:
    def Equals(self, obj: Object) -> bool: ...
    @property
    def DrawGrid(self) -> bool: ...
    @property
    def DrawPage(self) -> bool: ...
    @property
    def DrawShadow(self) -> bool: ...
    @property
    def EdgeColour(self) -> Color: ...
    @property
    def FillColour(self) -> Color: ...
    @property
    def GridColour(self) -> Color: ...
    @property
    def GridHeight(self) -> int: ...
    @property
    def GridPattern(self) -> Iterable[Single]: ...
    @property
    def GridWidth(self) -> int: ...
    @property
    def ShadowColour(self) -> Color: ...
    @property
    def ShadowSize(self) -> int: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @DrawGrid.setter
    def DrawGrid(self) -> MutableSequence[bool]: ...
    @DrawPage.setter
    def DrawPage(self) -> MutableSequence[bool]: ...
    @DrawShadow.setter
    def DrawShadow(self) -> MutableSequence[bool]: ...
    @EdgeColour.setter
    def EdgeColour(self) -> MutableSequence[Color]: ...
    @FillColour.setter
    def FillColour(self) -> MutableSequence[Color]: ...
    @GridColour.setter
    def GridColour(self) -> MutableSequence[Color]: ...
    @GridHeight.setter
    def GridHeight(self) -> MutableSequence[int]: ...
    @GridPattern.setter
    def GridPattern(self) -> MutableSequence[Iterable[Single]]: ...
    @GridWidth.setter
    def GridWidth(self) -> MutableSequence[int]: ...
    @ShadowColour.setter
    def ShadowColour(self) -> MutableSequence[Color]: ...
    @ShadowSize.setter
    def ShadowSize(self) -> MutableSequence[int]: ...
    def ToString(self) -> str: ...


from ..Canvas import GH_PaletteStyle
class GH_PaletteSettings:
    def Equals(self, obj: Object) -> bool: ...
    @property
    def ErrorSelected(self) -> GH_PaletteStyle: ...
    @property
    def ErrorStandard(self) -> GH_PaletteStyle: ...
    @property
    def HiddenSelected(self) -> GH_PaletteStyle: ...
    @property
    def HiddenStandard(self) -> GH_PaletteStyle: ...
    @property
    def LockedSelected(self) -> GH_PaletteStyle: ...
    @property
    def LockedStandard(self) -> GH_PaletteStyle: ...
    @property
    def NormalSelected(self) -> GH_PaletteStyle: ...
    @property
    def NormalStandard(self) -> GH_PaletteStyle: ...
    @property
    def WarningSelected(self) -> GH_PaletteStyle: ...
    @property
    def WarningStandard(self) -> GH_PaletteStyle: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @ErrorSelected.setter
    def ErrorSelected(self) -> MutableSequence[GH_PaletteStyle]: ...
    @ErrorStandard.setter
    def ErrorStandard(self) -> MutableSequence[GH_PaletteStyle]: ...
    @HiddenSelected.setter
    def HiddenSelected(self) -> MutableSequence[GH_PaletteStyle]: ...
    @HiddenStandard.setter
    def HiddenStandard(self) -> MutableSequence[GH_PaletteStyle]: ...
    @LockedSelected.setter
    def LockedSelected(self) -> MutableSequence[GH_PaletteStyle]: ...
    @LockedStandard.setter
    def LockedStandard(self) -> MutableSequence[GH_PaletteStyle]: ...
    @NormalSelected.setter
    def NormalSelected(self) -> MutableSequence[GH_PaletteStyle]: ...
    @NormalStandard.setter
    def NormalStandard(self) -> MutableSequence[GH_PaletteStyle]: ...
    @WarningSelected.setter
    def WarningSelected(self) -> MutableSequence[GH_PaletteStyle]: ...
    @WarningStandard.setter
    def WarningStandard(self) -> MutableSequence[GH_PaletteStyle]: ...
    def ToString(self) -> str: ...


class GH_Theme:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, other: GH_Theme): ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def BackGround(self) -> GH_BackgroundSettings: ...
    @property
    def DefaultTheme() -> GH_Theme: ...
    @property
    def Objects(self) -> GH_ObjectSettings: ...
    @property
    def Page(self) -> GH_PageSettings: ...
    @property
    def Palettes(self) -> GH_PaletteSettings: ...
    @property
    def Wires(self) -> GH_WireSettings: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def LoadTheme(self) -> None: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def SaveTheme(self) -> None: ...
    def ToString(self) -> str: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


class GH_WireSettings:
    def Equals(self, obj: Object) -> bool: ...
    @property
    def DefaultColour(self) -> Color: ...
    @property
    def EmptyColour(self) -> Color: ...
    @property
    def SelectedColour0(self) -> Color: ...
    @property
    def SelectedColour1(self) -> Color: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    @DefaultColour.setter
    def DefaultColour(self) -> MutableSequence[Color]: ...
    @EmptyColour.setter
    def EmptyColour(self) -> MutableSequence[Color]: ...
    @SelectedColour0.setter
    def SelectedColour0(self) -> MutableSequence[Color]: ...
    @SelectedColour1.setter
    def SelectedColour1(self) -> MutableSequence[Color]: ...
    def ToString(self) -> str: ...
