from typing import overload, Any, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



from ..Kernel.Types import GH_AngularDimension
from System.Collections.Generic import List
class GH_AngularDimensionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetAngularDimension() -> GH_AngularDimension: ...
    @overload
    @staticmethod
    def GetAngularDimensions() -> List: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Arc
from System.Collections.Generic import List
class GH_ArcGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetArc() -> GH_Arc: ...
    @overload
    @staticmethod
    def GetArcs() -> List: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Box
from System.Collections.Generic import List
class GH_BoxGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetBox() -> GH_Box: ...
    @overload
    @staticmethod
    def GetBoxes() -> List: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Brep
from System.Collections.Generic import List
class GH_BrepGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetBrep() -> GH_Brep: ...
    @overload
    @staticmethod
    def GetBreps() -> List: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Centermark
from System.Collections.Generic import List
class GH_CentermarkGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetCentermark() -> GH_Centermark: ...
    @overload
    @staticmethod
    def GetCentermarks() -> List: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Circle
from System.Collections.Generic import List
class GH_CircleGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetCircle() -> GH_Circle: ...
    @overload
    @staticmethod
    def GetCircles() -> List: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Curve
from System.Collections.Generic import List
class GH_CurveGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetCurve() -> GH_Curve: ...
    @overload
    @staticmethod
    def GetCurves() -> List: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Extrusion
from System.Collections.Generic import List
class GH_ExtrusionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetExtrusion() -> GH_Extrusion: ...
    @overload
    @staticmethod
    def GetExtrusions() -> List: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import IGH_GeometricGoo
from System.Collections.Generic import List
class GH_GeometryGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    @staticmethod
    def GetGeometries() -> List: ...
    @overload
    @staticmethod
    def GetGeometry() -> IGH_GeometricGoo: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Hatch
from System.Collections.Generic import List
class GH_HatchGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetHatch() -> GH_Hatch: ...
    @overload
    @staticmethod
    def GetHatches() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_InstanceReference
from System.Collections.Generic import List
class GH_InstanceReferenceGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetInstanceReference() -> GH_InstanceReference: ...
    @overload
    @staticmethod
    def GetInstanceReferences() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Leader
from System.Collections.Generic import List
class GH_LeaderGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLeader() -> GH_Leader: ...
    @overload
    @staticmethod
    def GetLeaders() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Light
from System.Collections.Generic import List
class GH_LightGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLight() -> GH_Light: ...
    @overload
    @staticmethod
    def GetLights() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_LinearDimension
from System.Collections.Generic import List
class GH_LinearDimensionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLinearDimension() -> GH_LinearDimension: ...
    @overload
    @staticmethod
    def GetLinearDimensions() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Line
from System.Collections.Generic import List
class GH_LineGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLine() -> GH_Line: ...
    @overload
    @staticmethod
    def GetLines() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Mesh
from System.Collections.Generic import List
class GH_MeshGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetMesh() -> GH_Mesh: ...
    @overload
    @staticmethod
    def GetMeshes() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_OrdinateDimension
from System.Collections.Generic import List
class GH_OrdinateDimensionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetOrdinateDimension() -> GH_OrdinateDimension: ...
    @overload
    @staticmethod
    def GetOrdinateDimensions() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from Rhino.Geometry import Plane
from Rhino.Geometry import Point3d
from ..Kernel.Types import GH_Plane
from System.Collections.Generic import List
class GH_PlaneGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetPlane() -> GH_Plane: ...
    @overload
    @staticmethod
    def GetPlanes() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def RotatePlaneX(plane: Plane, pt: Point3d) -> Plane: ...
    @overload
    @staticmethod
    def RotatePlaneY(plane: Plane, pt: Point3d) -> Plane: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_PointCloud
from System.Collections.Generic import List
class GH_PointCloudGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetPointCloud() -> GH_PointCloud: ...
    @overload
    @staticmethod
    def GetPointClouds() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_PointRefType
from ..Kernel.Types import GH_Point
from Rhino.Geometry import Point3d
from ..Kernel import GH_GetterResult
from System.Collections.Generic import List
class GH_PointGetter:
    @overload
    def __init__(self): ...
    @overload
    def DefaultRefType(self) -> GH_PointRefType: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def AcceptPreselected(self) -> bool: ...
    @property
    def PointRefType(self) -> GH_PointRefType: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetPoint(self) -> GH_Point: ...
    @overload
    def GetPoint(self, base: Point3d) -> GH_Point: ...
    @overload
    @staticmethod
    def GetPoint(prompt: str, basePoint: Point3d, outPoint: Point3d) -> Tuple[GH_GetterResult, Point3d]: ...
    @overload
    def GetPoints(self) -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def RecreateSetup(self, pt: GH_Point) -> None: ...
    @AcceptPreselected.setter
    def AcceptPreselected(self, AutoPropertyValue: bool) -> None: ...
    @PointRefType.setter
    def PointRefType(self, AutoPropertyValue: GH_PointRefType) -> None: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_RadialDimension
from System.Collections.Generic import List
class GH_RadialDimensionGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetRadialDimension() -> GH_RadialDimension: ...
    @overload
    @staticmethod
    def GetRadialDimensions() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Rectangle
from System.Collections.Generic import List
class GH_RectangleGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetRectangle() -> GH_Rectangle: ...
    @overload
    @staticmethod
    def GetRectangles() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_SubD
from System.Collections.Generic import List
class GH_SubDGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetSubD() -> GH_SubD: ...
    @overload
    @staticmethod
    def GetSubDs() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Surface
from System.Collections.Generic import List
class GH_SurfaceGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetSurface() -> GH_Surface: ...
    @overload
    @staticmethod
    def GetSurfaces() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_TextDot
from System.Collections.Generic import List
class GH_TextDotGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetTextDot() -> GH_TextDot: ...
    @overload
    @staticmethod
    def GetTextDots() -> List: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_TextEntity
from System.Collections.Generic import List
class GH_TextEntityGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetTextEntities() -> List: ...
    @overload
    @staticmethod
    def GetTextEntity() -> GH_TextEntity: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


class GH_TransformGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import GH_Vector
from System.Collections.Generic import List
class GH_VectorGetter:
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def GetVector() -> GH_Vector: ...
    @overload
    @staticmethod
    def GetVectors() -> List: ...
    @overload
    def ToString(self) -> str: ...
