from typing import overload, Any, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class GH_NetworkSorter:
    @overload
    def __init__(self): ...
    @overload
    def CreateContext(self, objs: MutableSequence[IGH_DocumentObject]) -> None: ...
    @overload
    def CreateNodeList(self, objs: MutableSequence[IGH_DocumentObject]) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Sort(self, bDamp: float, bLimit: float) -> None: ...
    @overload
    def ToString(self) -> str: ...


from Grasshopper.Kernel import IGH_DocumentObject
class GH_NetworkSorterNode:
    @overload
    def __init__(self, obj_target: IGH_DocumentObject): ...
    @overload
    def AdjustTarget(self, bDamp: float, bLimit: float) -> None: ...
    @overload
    def ConstructLinkForces(self) -> None: ...
    @overload
    def ConstructNodeForces(self, objs: MutableSequence[IGH_DocumentObject]) -> None: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToString(self) -> str: ...
