from typing import overload, Any, Iterable, Iterator, Sequence, MutableSequence, Callable
from enum import Enum

from Rhino import RhinoDoc
from Rhino.DocObjects import RhinoObject
from Rhino.FileIO import BinaryArchiveReader
from Rhino.FileIO import BinaryArchiveWriter
from Rhino.FileIO import TextLog
from Rhino.Geometry import BoundingBox
from Rhino.Geometry import Transform
from Rhino.Runtime.InteropWrappers import SimpleArrayBinaryArchiveReader
from System import Guid
from System import IntPtr




class SnapShotsClient:
    @overload
    def __init__(self): ...
    @overload
    def AnimateDocument(self, doc: RhinoDoc, dPos: float, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader) -> bool: ...
    @overload
    def AnimateObject(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, dPos: float, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader) -> tuple[bool, Transform]: ...
    @overload
    def AnimationStart(self, doc: RhinoDoc, iFrames: int) -> None: ...
    @overload
    def AnimationStop(self, doc: RhinoDoc) -> bool: ...
    @overload
    @staticmethod
    def ApplicationCategory() -> str: ...
    @overload
    def Category(self) -> str: ...
    @overload
    def ClientId(self) -> Guid: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    @staticmethod
    def DocumentCategory() -> str: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def ExtendBoundingBoxForDocumentAnimation(self, doc: RhinoDoc, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader, bbox: BoundingBox) -> tuple[BoundingBox]: ...
    @overload
    def ExtendBoundingBoxForObjectAnimation(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader, bbox: BoundingBox) -> tuple[Transform, BoundingBox]: ...
    @property
    def CppPointer(self) -> IntPtr: ...
    @property
    def SerialNumber(self) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def IsCurrentModelStateInAnySnapshot(self, doc: RhinoDoc, archive: BinaryArchiveReader, archive_array: SimpleArrayBinaryArchiveReader, text_log: TextLog) -> bool: ...
    @overload
    def IsCurrentModelStateInAnySnapshot(self, doc: RhinoDoc, doc_object: RhinoObject, archive: BinaryArchiveReader, archive_array: SimpleArrayBinaryArchiveReader, text_log: TextLog) -> bool: ...
    @overload
    @staticmethod
    def LayersCategory() -> str: ...
    @overload
    @staticmethod
    def LightsCategory() -> str: ...
    @overload
    def Name(self) -> str: ...
    @overload
    @staticmethod
    def ObjectsCategory() -> str: ...
    @overload
    def ObjectTransformNotification(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive: BinaryArchiveReader) -> tuple[bool, Transform]: ...
    @overload
    def PlugInId(self) -> Guid: ...
    @overload
    def PrepareForDocumentAnimation(self, doc: RhinoDoc, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader) -> bool: ...
    @overload
    def PrepareForObjectAnimation(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader) -> tuple[bool, Transform]: ...
    @overload
    @staticmethod
    def RegisterSnapShotClient(client: SnapShotsClient) -> bool: ...
    @overload
    @staticmethod
    def RenderingCategory() -> str: ...
    @overload
    def RestoreDocument(self, doc: RhinoDoc, archive: BinaryArchiveReader) -> bool: ...
    @overload
    def RestoreObject(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive: BinaryArchiveReader) -> tuple[bool, Transform]: ...
    @overload
    def SaveDocument(self, doc: RhinoDoc, archive: BinaryArchiveWriter) -> bool: ...
    @overload
    def SaveObject(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive: BinaryArchiveWriter) -> tuple[bool, Transform]: ...
    @SerialNumber.setter
    def SerialNumber(self, value: int) -> None: ...
    @overload
    def SnapshotRestored(self, doc: RhinoDoc) -> None: ...
    @overload
    def SupportsAnimation(self) -> bool: ...
    @overload
    def SupportsDocument(self) -> bool: ...
    @overload
    def SupportsObject(self, doc_object: RhinoObject) -> bool: ...
    @overload
    def SupportsObjects(self) -> bool: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def ViewsCategory() -> str: ...
