from typing import Tuple, Iterable, overload
from enum import Enum

import Hints

__all__ = ['Hints']




from ..Undo import GH_ObjectUndoAction
class GH_ExpressionUndoAction(GH_ObjectUndoAction):
    def __init__(self, obj: IGH_DocumentObject, expression: str): ...
    @property
    def ExpiresSolution(self) -> bool: ...


from ..Types import IGH_GeometricGoo
class GH_GeometryProxy:
    def __init__(self, nValue: IGH_GeometricGoo): ...
    @property
    def IsParsable(self) -> bool: ...


from ..Data import GH_Path
from ..Types import GH_Guid
from ..Data import IGH_Structure
from ..Data import GH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class GH_ProxyParameter:
    def __init__(self, nUUID: Guid): ...
    def CreateAttributes(self) -> None: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def InstanceDescription(self) -> str: ...
    @property
    def Kind(self) -> GH_ParamKind: ...
    @property
    def ProxyGuid(self) -> Guid: ...


from ...GUI import GH_TooltipDisplayEventArgs
from ...GUI.Canvas import GH_Canvas
from ...GUI.Canvas import GH_CanvasChannel
from ...GUI import GH_CanvasMouseEvent
class GH_ProxyParameterAttributes:
    def __init__(self, owner: GH_ProxyParameter): ...
    @property
    def HasInputGrip(self) -> bool: ...
    @property
    def HasOutputGrip(self) -> bool: ...
    @property
    def OutputGrip(self) -> PointF: ...


from ..Data import GH_Path
from ..Types import IGH_Goo
from ..Data import IGH_Structure
from ..Data import GH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class GH_Receiver:
    def __init__(self): ...
    def AppendMenuItems(self, menu: ToolStripDropDown) -> bool: ...
    def CreateAttributes(self) -> None: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def DrawTag(self) -> bool: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def InstanceDescription(self) -> str: ...
    @property
    def Kind(self) -> GH_ParamKind: ...
    @property
    def WireAppearance(self) -> GH_WireAppearance: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    @DrawTag.setter
    def DrawTag(self, Value: bool) -> None: ...
    @WireAppearance.setter
    def WireAppearance(self, Value: GH_WireAppearance) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ...GUI import GH_TooltipDisplayEventArgs
from ...GUI.Canvas import GH_Canvas
from ...GUI import GH_CanvasMouseEvent
from ...GUI.Canvas import GH_CanvasChannel
from ..Attributes import GH_FloatingParamAttributes
class GH_ReceiverAttributes(GH_FloatingParamAttributes):
    def __init__(self, owner: GH_Receiver): ...


class GH_WireAppearance(Enum):
    never = 0
    selected = 1
    always = 2


class IGH_ExpressionParameter:
    @property
    def Expression(self) -> str: ...
    @Expression.setter
    def Expression(self, Value: str) -> None: ...


class IGH_TypeHint:
    def Cast(self, data: Object) -> Tuple[bool, Object]: ...
    @property
    def HintID(self) -> Guid: ...
    @property
    def TypeName(self) -> str: ...


from ..Types import GH_Arc
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Arc:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_Boolean
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Boolean:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Invert(self) -> bool: ...
    @property
    def StateTags(self) -> GH_StateTagList: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def RemoveEffects(self) -> None: ...
    @Invert.setter
    def Invert(self, Value: bool) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ..Types import GH_Box
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Box:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_Brep
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Brep:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_Circle
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Circle:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_Colour
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Colour:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def TypeName(self) -> str: ...


from ..Types import GH_ComplexNumber
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Complex:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_Culture
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Culture:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def TypeName(self) -> str: ...


from ..Types import GH_Curve
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Curve:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @property
    def StateTags(self) -> GH_StateTagList: ...
    @property
    def TypeName(self) -> str: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def RemoveEffects(self) -> None: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ..Data import GH_Path
from ..Types import GH_Field
from ..Data import IGH_Structure
from ..Data import GH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Field:
    def __init__(self): ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_String
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_FilePath:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @property
    def AllFilesFilter() -> str: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def ExpireOnFileEvent(self) -> bool: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def FileFilter(self) -> str: ...
    @property
    def StateTags(self) -> GH_StateTagList: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    @ExpireOnFileEvent.setter
    def ExpireOnFileEvent(self, AutoPropertyValue: bool) -> None: ...
    @FileFilter.setter
    def FileFilter(self, AutoPropertyValue: str) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ..Data import GH_Structure
from ..Types import IGH_Goo
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_GenericObject:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    def GenericDataCleanup(data: GH_Structure) -> None: ...
    @property
    def AngleParameter(self) -> bool: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @property
    def StateTags(self) -> GH_StateTagList: ...
    @property
    def TypeName(self) -> str: ...
    @property
    def UseDegrees(self) -> bool: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    @AngleParameter.setter
    def AngleParameter(self, AutoPropertyValue: bool) -> None: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...
    @UseDegrees.setter
    def UseDegrees(self, AutoPropertyValue: bool) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ..Types import IGH_GeometricGoo
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Geometry:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def GeometryParameterID() -> Guid: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @property
    def TypeName(self) -> str: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Data import GH_Path
from ..Types import GH_GeometryGroup
from ..Data import IGH_Structure
from ..Data import GH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Group:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @property
    def TypeName(self) -> str: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_Guid
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Guid:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_Integer
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Integer:
    def __init__(self): ...
    def AddNamedValue(self, name: str, value: int) -> None: ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    def ClearNamedValues(self) -> None: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def HasNamedValues(self) -> bool: ...


from ..Types import GH_Interval
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Interval:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_Interval2D
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Interval2D:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def TypeName(self) -> str: ...


from ..Data import GH_Path
from ..Types import GH_Interval2D
from ..Data import IGH_Structure
from ..Data import GH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Interval2D_OBSOLETE:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_LonLatCoordinate
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_LatLonLocation:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def TypeName(self) -> str: ...


from ..Types import GH_Line
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Line:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @property
    def TypeName(self) -> str: ...
    def LineThroughBox(P: Line, B: BoundingBox) -> Line: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_Matrix
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Matrix:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_Mesh
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Mesh:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_MeshFace
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_MeshFace:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def TypeName(self) -> str: ...


from ..Types import GH_MeshingParameters
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_MeshParameters:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_Number
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Number:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @property
    def AngleParameter(self) -> bool: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def StateTags(self) -> GH_StateTagList: ...
    @property
    def UseDegrees(self) -> bool: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    @AngleParameter.setter
    def AngleParameter(self, Value: bool) -> None: ...
    @UseDegrees.setter
    def UseDegrees(self, Value: bool) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ..Types import GH_Material
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_OGLShader:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def TypeName(self) -> str: ...


from ..Types import GH_Plane
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Plane:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    def PlaneThroughBox(P: Plane, B: BoundingBox) -> PlaneSurface: ...
    def RegisterRemoteIDs(self, id_list: GH_GuidTable) -> None: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_Point
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Point:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def ClearData(self) -> None: ...
    def CreateAttributes(self) -> None: ...
    def DocumentContextChanged(self, document: GH_Document, context: GH_DocumentContext) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Expression(self) -> str: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @property
    def Locked(self) -> bool: ...
    @property
    def StateTags(self) -> GH_StateTagList: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def RemovedFromDocument(self, document: GH_Document) -> None: ...
    def RemoveEffects(self) -> None: ...
    @Expression.setter
    def Expression(self, Value: str) -> None: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...
    @Locked.setter
    def Locked(self, Value: bool) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ..Types import GH_Rectangle
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Rectangle:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def CreateAttributes(self) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import IGH_Goo
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_ScriptVariable(Param_GenericObject):
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @property
    def AllowTreeAccess(self) -> bool: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hints(self) -> List: ...
    @property
    def InstanceDescription(self) -> str: ...
    @property
    def ShowHints(self) -> bool: ...
    @property
    def TypeHint(self) -> IGH_TypeHint: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    @AllowTreeAccess.setter
    def AllowTreeAccess(self, Value: bool) -> None: ...
    @Hints.setter
    def Hints(self, Value: List) -> None: ...
    @ShowHints.setter
    def ShowHints(self, Value: bool) -> None: ...
    @TypeHint.setter
    def TypeHint(self, Value: IGH_TypeHint) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ..Types import GH_String
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_String:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_StructurePath
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_StructurePath:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_SubD
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_SubD:
    def __init__(self): ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...


from ..Types import GH_Surface
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Surface:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, obj_ids: List) -> None: ...
    @overload
    def BakeGeometry(self, doc: RhinoDoc, att: ObjectAttributes, obj_ids: List) -> None: ...
    def DrawViewportMeshes(self, args: IGH_PreviewArgs) -> None: ...
    def DrawViewportWires(self, args: IGH_PreviewArgs) -> None: ...
    @property
    def ClippingBox(self) -> BoundingBox: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def Hidden(self) -> bool: ...
    @property
    def IsBakeCapable(self) -> bool: ...
    @property
    def IsPreviewCapable(self) -> bool: ...
    @property
    def StateTags(self) -> GH_StateTagList: ...
    @property
    def TypeName(self) -> str: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def RemoveEffects(self) -> None: ...
    @Hidden.setter
    def Hidden(self, Value: bool) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


from ..Types import GH_Time
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Time:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_Transform
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Transform:
    def __init__(self): ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...


from ..Types import GH_Vector
from ..Data import GH_Structure
from ..Data import GH_Path
from ..Data import IGH_Structure
from ..Undo import IGH_UndoAction
from ..Undo import GH_UndoRecord
class Param_Vector:
    def __init__(self): ...
    def AppendAdditionalMenuItems(self, menu: ToolStripDropDown) -> None: ...
    @property
    def ComponentGuid(self) -> Guid: ...
    @property
    def Exposure(self) -> GH_Exposure: ...
    @property
    def StateTags(self) -> GH_StateTagList: ...
    @property
    def TypeName(self) -> str: ...
    @property
    def Unitize(self) -> bool: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def RemoveEffects(self) -> None: ...
    @Unitize.setter
    def Unitize(self, Value: bool) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...
