from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum

import Annotations
import Display
import Drafting
import Model
import Params
import Render

__all__ = ['Annotations', 'Display', 'Drafting', 'Model', 'Params', 'Render']


class Attributes:
    @overload
    def Clone(self) -> Attributes: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    @property
    def Name(self) -> ModelContentName: ...
    @overload
    @property
    def Notes(self) -> str: ...
    @overload
    @property
    def Parent(self) -> ModelContentName: ...
    @overload
    @property
    def Path(self) -> ModelContentName: ...
    @overload
    @property
    def Tags(self) -> ModelTags: ...
    @overload
    @property
    def UserText(self) -> ModelUserText: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @Name.setter
    def Name(self, Value: ModelContentName) -> None: ...
    @overload
    @Notes.setter
    def Notes(self, AutoPropertyValue: str) -> None: ...
    @overload
    @Parent.setter
    def Parent(self, Value: ModelContentName) -> None: ...
    @overload
    @Path.setter
    def Path(self, Value: ModelContentName) -> None: ...
    @overload
    @Tags.setter
    def Tags(self, AutoPropertyValue: ModelTags) -> None: ...
    @overload
    @UserText.setter
    def UserText(self, AutoPropertyValue: ModelUserText) -> None: ...
    @overload
    def ToDetails(self) -> str: ...
    @overload
    def ToModelData(self) -> ModelData: ...
    @overload
    def ToString(self) -> str: ...


class Attributes:
    @overload
    def Clone(self) -> Attributes: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    @property
    def Name(self) -> ModelContentName: ...
    @overload
    @property
    def Notes(self) -> str: ...
    @overload
    @property
    def Parent(self) -> ModelContentName: ...
    @overload
    @property
    def Path(self) -> ModelContentName: ...
    @overload
    @property
    def Tags(self) -> ModelTags: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @Name.setter
    def Name(self, Value: ModelContentName) -> None: ...
    @overload
    @Notes.setter
    def Notes(self, AutoPropertyValue: str) -> None: ...
    @overload
    @Parent.setter
    def Parent(self, Value: ModelContentName) -> None: ...
    @overload
    @Path.setter
    def Path(self, Value: ModelContentName) -> None: ...
    @overload
    @Tags.setter
    def Tags(self, AutoPropertyValue: ModelTags) -> None: ...
    @overload
    def ToDetails(self) -> str: ...
    @overload
    def ToModelData(self) -> ModelData: ...
    @overload
    def ToString(self) -> str: ...


class Attributes:
    @overload
    def Clone(self) -> Attributes: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToDetails(self) -> str: ...
    @overload
    def ToModelData(self) -> ModelData: ...
    @overload
    def ToString(self) -> str: ...


class ModelColor:
    @overload
    def CompareTo(self, other: ModelColor) -> int: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: ModelColor) -> bool: ...
    @overload
    @staticmethod
    def FromArgb(argb: int) -> ModelColor: ...
    @overload
    @staticmethod
    def FromArgb(r: Byte, g: Byte, b: Byte) -> ModelColor: ...
    @overload
    @staticmethod
    def FromArgb(a: Byte, r: Byte, g: Byte, b: Byte) -> ModelColor: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def __eq__(left: ModelColor, right: ModelColor) -> bool: ...
    @overload
    def __eq__(left: ModelColor, right: Color) -> bool: ...
    @overload
    def __eq__(right: ModelColor, left: Color) -> bool: ...
    @overload
    def op_Explicit(color: ModelColor) -> ColorRGBA: ...
    @overload
    def op_Implicit(color: Color) -> ModelColor: ...
    @overload
    def op_Implicit(color: ColorRGBA) -> ModelColor: ...
    @overload
    def op_Implicit(color: ModelColor) -> Color: ...
    @overload
    def __ne__(left: ModelColor, right: ModelColor) -> bool: ...
    @overload
    def __ne__(left: ModelColor, right: Color) -> bool: ...
    @overload
    def __ne__(right: ModelColor, left: Color) -> bool: ...
    @overload
    def ToArgb(self) -> int: ...
    @overload
    def ToString(self) -> str: ...


class ModelComponentContent(ModelContent):
    @overload
    def CastTo(self) -> Tuple[bool, T]: ...
    @overload
    def Equals(self, other: ModelData) -> bool: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: ModelContent) -> bool: ...
    @overload
    @property
    def DisplayName(self) -> str: ...
    @overload
    @property
    def Id(self) -> Nullable: ...
    @overload
    @property
    def IsValid(self) -> bool: ...
    @overload
    @property
    def Name(self) -> ModelContentName: ...
    @overload
    @property
    def Notes(self) -> str: ...
    @overload
    @property
    def Parent(self) -> ModelContentName: ...
    @overload
    @property
    def Path(self) -> ModelContentName: ...
    @overload
    @property
    def Tags(self) -> ModelTags: ...
    @overload
    @property
    def TypeName(self) -> str: ...
    @overload
    @property
    def UserText(self) -> ModelUserText: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToAttributes(self) -> Attributes: ...
    @overload
    def ToAttributes(self) -> Attributes: ...
    @overload
    def ToAttributes(self) -> Attributes: ...
    @overload
    def ToDetails(self) -> str: ...
    @overload
    def TooltipString(self) -> str: ...
    @overload
    def ToString(self) -> str: ...


class ModelContent(ModelData):
    @overload
    @staticmethod
    def Cast(source: object) -> ModelContent: ...
    @overload
    def CastTo(self) -> Tuple[bool, T]: ...
    @overload
    def Equals(self, other: ModelData) -> bool: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: ModelContent) -> bool: ...
    @overload
    @staticmethod
    def FromId(document: RhinoDoc, guid: Guid) -> ModelContent: ...
    @overload
    @property
    def DisplayName(self) -> str: ...
    @overload
    @property
    def Id(self) -> Nullable: ...
    @overload
    @property
    def IsValid(self) -> bool: ...
    @overload
    @property
    def Name(self) -> ModelContentName: ...
    @overload
    @property
    def Notes(self) -> str: ...
    @overload
    @property
    def Parent(self) -> ModelContentName: ...
    @overload
    @property
    def Path(self) -> ModelContentName: ...
    @overload
    @property
    def Tags(self) -> ModelTags: ...
    @overload
    @property
    def TypeName(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToAttributes(self) -> Attributes: ...
    @overload
    def ToAttributes(self) -> Attributes: ...
    @overload
    def ToDetails(self) -> str: ...
    @overload
    def TooltipString(self) -> str: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel import GH_LoadingInstruction
from ..Kernel import GH_AssemblyPriority
class ModelContentEnablerLoader(GH_AssemblyPriority):
    @overload
    def __init__(self): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def PriorityLoad(self) -> GH_LoadingInstruction: ...
    @overload
    def ToString(self) -> str: ...


class ModelContentName:
    Empty: ModelContentName
    Comparer: StringComparer
    @overload
    @staticmethod
    def Combine(paths: Iterable[ModelContentName]) -> ModelContentName: ...
    @overload
    def CompareTo(self, other: ModelContentName) -> int: ...
    @overload
    def CompareTo(self, obj: object) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: ModelContentName) -> bool: ...
    @overload
    @property
    def IsDefault(self) -> bool: ...
    @overload
    @property
    def IsDefaultOrEmpty(self) -> bool: ...
    @overload
    @property
    def IsEmpty(self) -> bool: ...
    @overload
    @property
    def Parent(self) -> ModelContentName: ...
    @overload
    @property
    def Separator() -> str: ...
    @overload
    @property
    def Stem(self) -> ModelContentName: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def __truediv__(left: ModelContentName, right: ModelContentName) -> ModelContentName: ...
    @overload
    def __eq__(left: ModelContentName, right: ModelContentName) -> bool: ...
    @overload
    def __eq__(right: ModelContentName, left: str) -> bool: ...
    @overload
    def __eq__(left: ModelContentName, right: str) -> bool: ...
    @overload
    def op_Implicit(value: str) -> ModelContentName: ...
    @overload
    def op_Implicit(value: ModelContentName) -> str: ...
    @overload
    def __ne__(left: ModelContentName, right: ModelContentName) -> bool: ...
    @overload
    def __ne__(right: ModelContentName, left: str) -> bool: ...
    @overload
    def __ne__(left: ModelContentName, right: str) -> bool: ...
    @overload
    def __invert__(value: ModelContentName) -> ModelContentName: ...
    @overload
    def Split(self) -> Iterable[str]: ...
    @overload
    def ToString(self) -> str: ...


class ModelData:
    @overload
    def CastTo(self) -> Tuple[bool, T]: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: ModelData) -> bool: ...
    @overload
    @property
    def DisplayName(self) -> str: ...
    @overload
    @property
    def IsValid(self) -> bool: ...
    @overload
    @property
    def TypeName(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def ToAttributes(self) -> Attributes: ...
    @overload
    def ToDetails(self) -> str: ...
    @overload
    def TooltipString(self) -> str: ...
    @overload
    def ToString(self) -> str: ...


from ..Kernel.Types import IGH_Goo
from ..Kernel.Types import IGH_GooProxy
from ..Kernel.Types import Q
class ModelFont:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, font: Font): ...
    @overload
    def __init__(self, familyName: str): ...
    @overload
    def CastFrom(self, source: object) -> bool: ...
    @overload
    def CastTo(self, target: Q) -> Tuple[bool, Q]: ...
    @overload
    def Duplicate(self) -> IGH_Goo: ...
    @overload
    def EmitProxy(self) -> IGH_GooProxy: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: ModelFont) -> bool: ...
    @overload
    @property
    def DisplayName(self) -> str: ...
    @overload
    @property
    def FamilyName(self) -> str: ...
    @overload
    @property
    def InstalledFamilies() -> IReadOnlyList: ...
    @overload
    @property
    def InstalledFonts() -> IReadOnlyList: ...
    @overload
    @property
    def IsInstalled(self) -> bool: ...
    @overload
    @property
    def IsValid(self) -> bool: ...
    @overload
    @property
    def IsValidWhyNot(self) -> str: ...
    @overload
    @property
    def TypeDescription(self) -> str: ...
    @overload
    @property
    def TypeName(self) -> str: ...
    @overload
    @property
    def Value(self) -> Font: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    @staticmethod
    def IsFamilyNameInstalled(familyName: str) -> bool: ...
    @overload
    def op_Implicit(familyName: str) -> ModelFont: ...
    @overload
    def op_Implicit(font: Font) -> ModelFont: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def ScriptVariable(self) -> object: ...
    @overload
    @Value.setter
    def Value(self, new_value: Font) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


class ModelMeshingParameters(ModelValue):
    @overload
    def __init__(self): ...
    @overload
    @staticmethod
    def Cast(source: object) -> ModelMeshingParameters: ...
    @overload
    def CastTo(self) -> Tuple[bool, T]: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: ModelValue) -> bool: ...
    @overload
    @property
    def DefaultAnalysis() -> ModelMeshingParameters: ...
    @overload
    @property
    def DefaultRender() -> ModelMeshingParameters: ...
    @overload
    @property
    def DisplayName(self) -> str: ...
    @overload
    @property
    def FastRender() -> ModelMeshingParameters: ...
    @overload
    @property
    def IsValid(self) -> bool: ...
    @overload
    @property
    def QualityRender() -> ModelMeshingParameters: ...
    @overload
    @property
    def TypeName(self) -> str: ...
    @overload
    @property
    def Unset() -> ModelMeshingParameters: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def op_Implicit(parameters: MeshingParameters) -> ModelMeshingParameters: ...
    @overload
    def ToMeshingParameters(self, document: RhinoDoc) -> MeshingParameters: ...
    @overload
    def TooltipString(self) -> str: ...
    @overload
    def ToString(self) -> str: ...


class ModelTags:
    @overload
    def __init__(self, source: Iterable[str]): ...
    def __iter__(self) -> Iterator[str]: ...
    Empty: ModelTags
    @overload
    def AddRange(self, source: Iterable[str]) -> ModelTags: ...
    @overload
    def CompareTo(self, obj: object) -> int: ...
    @overload
    def CompareTo(self, other: ModelTags) -> int: ...
    @overload
    def Contains(self, value: str) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: ModelTags) -> bool: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def IsDefault(self) -> bool: ...
    @overload
    @property
    def IsDefaultOrEmpty(self) -> bool: ...
    @overload
    @property
    def IsEmpty(self) -> bool: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def __add__(left: ModelTags, right: Iterable[str]) -> ModelTags: ...
    @overload
    def __eq__(left: ModelTags, right: ModelTags) -> bool: ...
    @overload
    def op_Implicit(value: ModelTags) -> str: ...
    @overload
    def op_Implicit(value: str) -> ModelTags: ...
    @overload
    def __ne__(left: ModelTags, right: ModelTags) -> bool: ...
    @overload
    def __sub__(left: ModelTags, right: Iterable[str]) -> ModelTags: ...
    @overload
    def RemoveRange(self, source: Iterable[str]) -> ModelTags: ...
    @overload
    def ToString(self) -> str: ...


class ModelUnitSystem(ModelValue):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, attributes: Value): ...
    @overload
    def __init__(self, space: ActiveSpace, document: RhinoDoc): ...
    @overload
    def AdjustDocumentUnitSystem(self, document: RhinoDoc, space: ActiveSpace, scale: bool) -> None: ...
    @overload
    @staticmethod
    def Cast(source: object) -> ModelUnitSystem: ...
    @overload
    def CastTo(self) -> Tuple[bool, T]: ...
    @overload
    @staticmethod
    def Copy(source: RhinoDoc, target: RhinoDoc, space: ActiveSpace) -> None: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: ModelValue) -> bool: ...
    @overload
    @property
    def ActiveSpace(self) -> ActiveSpace: ...
    @overload
    @property
    def BaseSystem(self) -> UnitSystem: ...
    @overload
    @property
    def DisplayName(self) -> str: ...
    @overload
    @property
    def Factor(self) -> float: ...
    @overload
    @property
    def IsValid(self) -> bool: ...
    @overload
    @property
    def MetersPerUnit(self) -> float: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def TypeName(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def op_Implicit(attributes: Value) -> ModelUnitSystem: ...
    @overload
    def op_Implicit(us: ModelUnitSystem) -> Value: ...
    @overload
    def TooltipString(self) -> str: ...
    @overload
    def ToString(self) -> str: ...


class ModelUserText:
    @overload
    def __init__(self, source: Iterable[KeyValuePair]): ...
    def __iter__(self) -> Iterator[KeyValuePair]: ...
    def __getitem__(self, index: int) -> KeyValuePair: ...
    Empty: ModelUserText
    @overload
    def ContainsKey(self, key: str) -> bool: ...
    @overload
    def EnsureRange(self, keys: Iterable[str]) -> ModelUserText: ...
    @overload
    def EnsureRange(self, source: Iterable[KeyValuePair]) -> ModelUserText: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: ModelUserText) -> bool: ...
    @overload
    @property
    def Count(self) -> int: ...
    @overload
    @property
    def IsDefault(self) -> bool: ...
    @overload
    @property
    def IsDefaultOrEmpty(self) -> bool: ...
    @overload
    @property
    def IsEmpty(self) -> bool: ...
    @overload
    @property
    def Item(self) -> Sequence[KeyValuePair]: ...
    @overload
    @property
    def Item(self, key: str) -> str: ...
    @overload
    @property
    def Keys(self) -> Iterable[str]: ...
    @overload
    @property
    def Values(self) -> Iterable[str]: ...
    @overload
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def MergeRange(self, source: Iterable[KeyValuePair]) -> ModelUserText: ...
    @overload
    def MergeRange(self, source: Iterable[str]) -> ModelUserText: ...
    @overload
    def __add__(left: ModelUserText, right: Iterable[str]) -> ModelUserText: ...
    @overload
    def __add__(left: ModelUserText, right: Iterable[KeyValuePair]) -> ModelUserText: ...
    @overload
    def __and__(left: ModelUserText, right: Iterable[str]) -> ModelUserText: ...
    @overload
    def __and__(left: ModelUserText, right: Iterable[KeyValuePair]) -> ModelUserText: ...
    @overload
    def __or__(left: ModelUserText, right: Iterable[str]) -> ModelUserText: ...
    @overload
    def __or__(left: ModelUserText, right: Iterable[KeyValuePair]) -> ModelUserText: ...
    @overload
    def __eq__(left: ModelUserText, right: ModelUserText) -> bool: ...
    @overload
    def __ne__(left: ModelUserText, right: ModelUserText) -> bool: ...
    @overload
    def __sub__(left: ModelUserText, right: Iterable[KeyValuePair]) -> ModelUserText: ...
    @overload
    def __sub__(left: ModelUserText, right: Iterable[str]) -> ModelUserText: ...
    @overload
    def RemoveRange(self, keys: Iterable[str]) -> ModelUserText: ...
    @overload
    def RemoveRange(self, source: Iterable[KeyValuePair]) -> ModelUserText: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def TryGetValue(self, key: str) -> Tuple[bool, str]: ...
    @overload
    def UpdateRange(self, keys: Iterable[str]) -> ModelUserText: ...
    @overload
    def UpdateRange(self, source: Iterable[KeyValuePair]) -> ModelUserText: ...


class ModelValue:
    @overload
    def CastTo(self) -> Tuple[bool, T]: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: ModelValue) -> bool: ...
    @overload
    @property
    def DisplayName(self) -> str: ...
    @overload
    @property
    def IsValid(self) -> bool: ...
    @overload
    @property
    def TypeName(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def TooltipString(self) -> str: ...
    @overload
    def ToString(self) -> str: ...


class Value:
    @overload
    def __init__(self, activeSpace: ActiveSpace, name: str): ...
    @overload
    def __init__(self, unitSystem: UnitSystem, name: str): ...
    @overload
    def __init__(self, unitSystem: UnitSystem, name: str, factor: float): ...
    @overload
    def __init__(self, other: Value, name: str, factor: Nullable): ...
    _MetersPerUnit: float
    @overload
    def AdjustDocumentUnitSystem(self, document: RhinoDoc, space: ActiveSpace, scale: bool) -> None: ...
    @overload
    def CompareTo(self, obj: object) -> int: ...
    @overload
    def CompareTo(self, other: Value) -> int: ...
    @overload
    def Equals(self, other: object) -> bool: ...
    @overload
    def Equals(self, other: Value) -> bool: ...
    @overload
    @property
    def ActiveSpace(self) -> ActiveSpace: ...
    @overload
    @property
    def BaseSystem(self) -> UnitSystem: ...
    @overload
    @property
    def Factor(self) -> float: ...
    @overload
    @property
    def Feet() -> Value: ...
    @overload
    @property
    def Inches() -> Value: ...
    @overload
    @property
    def Meters() -> Value: ...
    @overload
    @property
    def MetersPerUnit(self) -> float: ...
    @overload
    @property
    def Millimeters() -> Value: ...
    @overload
    @property
    def ModelUnits() -> Value: ...
    @overload
    @property
    def Name(self) -> str: ...
    @overload
    @property
    def None() -> Value: ...
    @overload
    @property
    def PageUnits() -> Value: ...
    @overload
    @property
    def Symbol(self) -> str: ...
    @overload
    @property
    def Unset() -> Value: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def __eq__(left: Value, right: Value) -> bool: ...
    @overload
    def __ne__(left: Value, right: Value) -> bool: ...
    @overload
    def ToNonCustomUnitSystem(self) -> Tuple[UnitSystem, float]: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def ToUnitSystem(self) -> Tuple[UnitSystem, float]: ...
