from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



class Solver:
    @staticmethod
    def Compute(nodes: Node2List, hull: List) -> bool: ...
    @overload
    @staticmethod
    def ComputeHull(GH_pts: Iterable[GH_Point]) -> Polyline: ...
    @overload
    @staticmethod
    def ComputeHull(pts: Node2List) -> Polyline: ...
    @overload
    @staticmethod
    def ComputeHull(GH_pts: Iterable[GH_Point], plane: Plane) -> Tuple[Polyline, Plane]: ...
    def Equals(self, obj: Object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def ToString(self) -> str: ...
