from typing import overload, Tuple, Iterable, Iterator, Sequence, MutableSequence
from enum import Enum



from ..PlugIns import PlugIn
class Command:
    @overload
    @staticmethod
    def add_BeginCommand(value: EventHandler) -> None: ...
    @overload
    @staticmethod
    def add_EndCommand(value: EventHandler) -> None: ...
    @overload
    @staticmethod
    def add_UndoRedo(value: EventHandler) -> None: ...
    @overload
    @staticmethod
    def DisplayHelp(commandId: Guid) -> None: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def EnglishName(self) -> str: ...
    @overload
    @property
    def Id(self) -> Guid: ...
    @overload
    @property
    def LastCommandId() -> Guid: ...
    @overload
    @property
    def LastCommandResult() -> Result: ...
    @overload
    @property
    def LocalName(self) -> str: ...
    @overload
    @property
    def PlugIn(self) -> PlugIn: ...
    @overload
    @property
    def Settings(self) -> PersistentSettings: ...
    @overload
    @staticmethod
    def GetCommandNames(english: bool, loaded: bool) -> Iterable[str]: ...
    @overload
    @staticmethod
    def GetCommandStack() -> Iterable[Guid]: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetMostRecentCommands() -> Iterable[MostRecentCommandDescription]: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    @staticmethod
    def InCommand() -> bool: ...
    @overload
    @staticmethod
    def InScriptRunnerCommand() -> bool: ...
    @overload
    @staticmethod
    def IsCommand(name: str) -> bool: ...
    @overload
    @staticmethod
    def IsValidCommandName(name: str) -> bool: ...
    @overload
    @staticmethod
    def LookupCommandId(name: str, searchForEnglishName: bool) -> Guid: ...
    @overload
    @staticmethod
    def LookupCommandName(commandId: Guid, englishName: bool) -> str: ...
    @overload
    @staticmethod
    def remove_BeginCommand(value: EventHandler) -> None: ...
    @overload
    @staticmethod
    def remove_EndCommand(value: EventHandler) -> None: ...
    @overload
    @staticmethod
    def remove_UndoRedo(value: EventHandler) -> None: ...
    @overload
    @staticmethod
    def RunProxyCommand(commandCallback: RunCommandDelegate, doc: RhinoDoc, data: Object) -> None: ...
    @overload
    def ToString(self) -> str: ...


class CommandEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def CommandEnglishName(self) -> str: ...
    @overload
    @property
    def CommandId(self) -> Guid: ...
    @overload
    @property
    def CommandLocalName(self) -> str: ...
    @overload
    @property
    def CommandPluginName(self) -> str: ...
    @overload
    @property
    def CommandResult(self) -> Result: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def DocumentRuntimeSerialNumber(self) -> UInt32: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def ToString(self) -> str: ...


class CommandStyleAttribute:
    @overload
    def __init__(self, styles: Style): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Styles(self) -> Style: ...
    @overload
    @property
    def TypeId(self) -> Object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def IsDefaultAttribute(self) -> bool: ...
    @overload
    def Match(self, obj: Object) -> bool: ...
    @overload
    def ToString(self) -> str: ...


class CustomUndoEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def ActionDescription(self) -> str: ...
    @overload
    @property
    def CommandId(self) -> Guid: ...
    @overload
    @property
    def CreatedByRedo(self) -> bool: ...
    @overload
    @property
    def Document(self) -> RhinoDoc: ...
    @overload
    @property
    def Tag(self) -> Object: ...
    @overload
    @property
    def UndoSerialNumber(self) -> UInt32: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def ToString(self) -> str: ...


class MostRecentCommandDescription:
    @overload
    def __init__(self): ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def DisplayString(self) -> str: ...
    @overload
    @property
    def Macro(self) -> str: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    @DisplayString.setter
    def DisplayString(self) -> MutableSequence[str]: ...
    @overload
    @Macro.setter
    def Macro(self) -> MutableSequence[str]: ...
    @overload
    def ToString(self) -> str: ...


class Result(Enum):
    Success = 0
    Cancel = 1
    Nothing = 2
    Failure = 3
    UnknownCommand = 4
    CancelModelessDialog = 5
    ExitRhino = 268435455


class RunCommandDelegate:
    @overload
    def __init__(self, object: Object, method: IntPtr): ...
    @overload
    def BeginInvoke(self, doc: RhinoDoc, mode: RunMode, data: Object, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    @overload
    def Clone(self) -> Object: ...
    @overload
    def DynamicInvoke(self, args: Iterable[Object]) -> Object: ...
    @overload
    def EndInvoke(self, result: IAsyncResult) -> Result: ...
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def Method(self) -> MethodInfo: ...
    @overload
    @property
    def Target(self) -> Object: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetInvocationList(self) -> Iterable[Delegate]: ...
    @overload
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def Invoke(self, doc: RhinoDoc, mode: RunMode, data: Object) -> Result: ...
    @overload
    def ToString(self) -> str: ...


class RunMode(Enum):
    Interactive = 0
    Scripted = 1


from ..PlugIns import PlugIn
class SelCommand(Command):
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def BeQuiet(self) -> bool: ...
    @overload
    @property
    def EnglishName(self) -> str: ...
    @overload
    @property
    def Id(self) -> Guid: ...
    @overload
    @property
    def LocalName(self) -> str: ...
    @overload
    @property
    def PlugIn(self) -> PlugIn: ...
    @overload
    @property
    def Settings(self) -> PersistentSettings: ...
    @overload
    @property
    def TestGrips(self) -> bool: ...
    @overload
    @property
    def TestLights(self) -> bool: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    @BeQuiet.setter
    def BeQuiet(self) -> MutableSequence[bool]: ...
    @overload
    @TestGrips.setter
    def TestGrips(self) -> MutableSequence[bool]: ...
    @overload
    @TestLights.setter
    def TestLights(self) -> MutableSequence[bool]: ...
    @overload
    def ToString(self) -> str: ...


class Style(Enum):
    # None = 0
    Hidden = 1
    ScriptRunner = 2
    Transparent = 4
    DoNotRepeat = 8
    NotUndoable = 16


from ..PlugIns import PlugIn
class TransformCommand(Command):
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def EnglishName(self) -> str: ...
    @overload
    @property
    def Id(self) -> Guid: ...
    @overload
    @property
    def LocalName(self) -> str: ...
    @overload
    @property
    def PlugIn(self) -> PlugIn: ...
    @overload
    @property
    def Settings(self) -> PersistentSettings: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def ToString(self) -> str: ...


class UndoRedoEventArgs:
    @overload
    def Equals(self, obj: Object) -> bool: ...
    @overload
    @property
    def CommandId(self) -> Guid: ...
    @overload
    @property
    def IsBeginRecording(self) -> bool: ...
    @overload
    @property
    def IsBeginRedo(self) -> bool: ...
    @overload
    @property
    def IsBeginUndo(self) -> bool: ...
    @overload
    @property
    def IsEndRecording(self) -> bool: ...
    @overload
    @property
    def IsEndRedo(self) -> bool: ...
    @overload
    @property
    def IsEndUndo(self) -> bool: ...
    @overload
    @property
    def IsPurgeRecord(self) -> bool: ...
    @overload
    @property
    def UndoSerialNumber(self) -> UInt32: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> Type: ...
    @overload
    def ToString(self) -> str: ...
