from typing import overload, Any, Iterable, Iterator, Sequence, MutableSequence, Callable
from enum import Enum

from GH_IO.Serialization import GH_IReader
from GH_IO.Serialization import GH_IWriter
from Grasshopper.Kernel import GH_Document
from Grasshopper.Kernel import GH_PersistentParam
from Grasshopper.Kernel import GH_State
from Grasshopper.Kernel import IGH_ActiveObject
from Grasshopper.Kernel import IGH_Component
from Grasshopper.Kernel import IGH_DocumentObject
from Grasshopper.Kernel import IGH_Param
from Grasshopper.Kernel.Undo import GH_UndoState




from Grasshopper.Kernel.Undo import GH_UndoAction
class GH_AddObjectAction(GH_UndoAction):
    @overload
    def __init__(self, obj: IGH_DocumentObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ArchivedUndoAction
class GH_AddStateAction(GH_ArchivedUndoAction):
    @overload
    def __init__(self, index: int, state: GH_State): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_DataMatchingAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_Component): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_DataModificationAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_Param): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ArchivedUndoAction
class GH_GenericObjectAction(GH_ArchivedUndoAction):
    @overload
    def __init__(self, obj: IGH_DocumentObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_HiddenAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_ActiveObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_IconDisplayAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_DocumentObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_IconOverrideAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_DocumentObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_LayoutAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_DocumentObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_LockedAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_ActiveObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_NickNameAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_DocumentObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...




from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_PivotAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_DocumentObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ArchivedUndoAction
class GH_RemoveObjectAction(GH_ArchivedUndoAction):
    @overload
    def __init__(self, obj: IGH_DocumentObject): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ArchivedUndoAction
class GH_RemoveStateAction(GH_ArchivedUndoAction):
    @overload
    def __init__(self, index: int, state: GH_State): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_UndoAction
class GH_WireAction(GH_UndoAction):
    @overload
    def __init__(self, param: IGH_Param): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...


from Grasshopper.Kernel.Undo import GH_ObjectUndoAction
class GH_WireDisplayAction(GH_ObjectUndoAction):
    @overload
    def __init__(self, obj: IGH_Param): ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @property
    def ExpiresDisplay(self) -> bool: ...
    @property
    def ExpiresSolution(self) -> bool: ...
    @property
    def State(self) -> GH_UndoState: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetType(self) -> type: ...
    @overload
    def Read(self, reader: GH_IReader) -> bool: ...
    @overload
    def Redo(self, doc: GH_Document) -> None: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def Undo(self, doc: GH_Document) -> None: ...
    @overload
    def Write(self, writer: GH_IWriter) -> bool: ...
